import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { builtinModules } from "module";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
// Read pdfjs worker source once at build time and inline via define.
// We resolve through createRequire so the path is stable under pnpm's
// .pnpm/<name>@<ver>/node_modules/<name>/ layout.
const workerPath = require.resolve(
  "pdfjs-dist/legacy/build/pdf.worker.mjs"
);
const workerSource = fs.readFileSync(workerPath, "utf8");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const oneShot = prod || (process.argv[2] === 'dev');

const prodBanner = prod ? 'console.debug = function() {};\n' : '';

const context = await esbuild.context({
  banner: {
    js: banner + prodBanner,
  },
  entryPoints: ['src/main.ts'],
  // Inline pdf.worker.mjs source as a string constant so we can hand
  // pdfjs a blob: URL without shipping a second .mjs file alongside
  // main.js (relative URL resolution is unreliable in the Obsidian
  // Electron renderer under CJS bundle — no import.meta.url).
  define: {
    __PDFJS_WORKER_SOURCE__: JSON.stringify(workerSource),
  },
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
    ...builtinModules.map((module) => `node:${module}`)],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (oneShot) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
