import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const oneShot = prod || (process.argv[2] === 'dev');

const prodBanner = prod ? 'console.debug = function() {};\n' : '';

const context = await esbuild.context({
  banner: {
    js: banner + prodBanner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    // Node builtins — both bare ("fs") and node:-prefixed ("node:fs")
    // forms are required. v1.24.0 added @aws-sdk/credential-providers
    // for Bedrock SSO/profile auth; the AWS SDK uses node:-prefixed
    // imports which esbuild treats as distinct from the bare names.
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`)],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (oneShot) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}