export const DE_TEXTS = {
    // Plugin Info
    pluginTitle: 'Karpathy LLM-Wiki-Einstellungen',
    pluginIntro: 'Dieses Plugin setzt das {{link}}-Konzept für Obsidian um. Es liest deine Notizen, nutzt KI, um Entitäten, Konzepte und Zusammenhänge zu extrahieren, und erstellt ein strukturiertes, vernetztes Wiki in deinem Vault.',
    karpathyLinkText: 'Andrej Karpathys LLM-Wiki',

    // Features Section
    featuresTitle: 'Funktionsweise',
    workflow1Title: '1. Aufnehmen',
    workflow1Desc: 'Wähle eine Notiz — KI extrahiert Entitäten, Konzepte und Zusammenhänge in Wiki-Seiten.',
    workflow2Title: '2. Anfragen',
    workflow2Desc: 'Chatte mit deinem Wiki — Antworten basieren auf deinem aufgenommenen Wissen.',
    workflow3Title: '3. Pflegen',
    workflow3Desc: 'Automatisch generierte Indizes, Querverweise und Lint-Prüfungen halten das Wiki gesund.',

    // Language Switcher
    languageTitle: 'Oberflächensprache',
    languageDesc: 'Wähle deine bevorzugte Sprache für das Einstellungsfenster. Starte das Plugin neu, um die Sprachänderungen auf die Befehlspalette anzuwenden.',
    languageEn: 'English',
    languageZh: '中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',

    // Status
    statusTitle: 'LLM-Client-Status',
    llmWikiStatusSection: 'LLM-Wiki-Status',
    statusInitialized: 'Initialisiert',
    statusReady: 'LLM bereit',
    statusNotReady: 'LLM nicht konfiguriert — Einrichtung oben abschließen und Verbindungstest bestehen',
    statusNotInitialized: 'Nicht initialisiert',
    currentProvider: 'Aktueller Anbieter',

    // Provider Configuration
    providerSection: 'LLM-Konfiguration',
    providerName: 'LLM-Anbieter',
    providerDesc: 'Vordefinierten Anbieter oder benutzerdefinierten OpenAI-kompatiblen Dienst wählen. Für Coding Plan oder ähnliche Bundles: Custom OpenAI/Anthropic wählen, Base URL und API Key des Providers manuell eingeben',

    // API Key
    apiKeyName: 'API-Schlüssel',
    apiKeyDesc: 'API-Schlüssel vom Anbieter eingeben',
    apiKeyPlaceholder: 'API-Schlüssel eingeben',

    // Base URL
    baseUrlName: 'API-Basis-URL',
    baseUrlDescCustom: 'Erforderlich: Benutzerdefinierte OpenAI-kompatible Endpunkt',
    baseUrlDescOverride: 'Optional: Voreingestellte Basis-URL überschreiben',

    // Ollama Hint
    ollamaHint: 'Ollama läuft lokal, kein API-Schlüssel erforderlich',
    lmstudioHint: 'LM Studio läuft lokal, API-Key ist optional',
    maxTokensPerCallName: 'Kontextfenster',
    maxTokensPerCallDesc: 'Tokens an das Kontextfenster des Modells anpassen. 0 = kein Limit (Cloud).',

    slugCaseName: 'Dateinamen-Schreibweise',
    slugCaseDesc: "Legt fest, ob generierte Wiki-Dateinamen kleingeschrieben werden. 'Beibehalten' empfohlen fuer Sprachen, in denen Gross-/Kleinschreibung bedeutungsrelevant ist (z. B. deutsche Substantive).",
    slugCaseLower: 'Kleinschreibung (Standard)',
    slugCasePreserve: 'Schreibweise beibehalten',

    // Model Selection
    modelSection: 'Modellauswahl',
    fetchModelsName: 'Verfügbare Modelle abrufen',
    fetchModelsDesc: 'Aktuelle Modellliste von der Anbieter-API abrufen',
    fetchModelsButton: 'Modelle abrufen',
    fetchingModels: 'Wird abgerufen...',
    fetchSuccess: 'Erfolg! {} Modelle verfügbar',
    fetchFailed: 'Abruf fehlgeschlagen oder leere Liste, bitte Modellnamen manuell eingeben',
    fetchNotSupported: 'Anbieter unterstützt keine Modelllistenabfrage',
    fetchErrorAuth: 'Authentifizierung fehlgeschlagen (HTTP 401/403). Überprüfen Sie den API-Schlüssel, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorEndpoint: 'Endpunkt nicht gefunden (HTTP 404). Überprüfen Sie die Endpunkt-URL, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorServer: 'Anbieter-Serverfehler (HTTP 5xx). Versuchen Sie es später erneut, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorEmpty: 'Dieser Endpunkt stellt keine Modellliste bereit. Geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    fetchErrorNetwork: 'Netzwerkanfrage fehlgeschlagen. Überprüfen Sie Internetverbindung, Endpunkt-URL oder Proxy-Einstellungen. Sie können auch eine Modell-ID eingeben und auf Verbindung testen klicken.',

    selectModelName: 'Modell auswählen',
    selectModelDesc: 'Aus {} verfügbaren Modellen wählen',
    customInputOption: 'Benutzerdefinierte Eingabe...',
    customInputHint: 'Um andere Modelle zu verwenden, wähle "Benutzerdefinierte Eingabe..."',

    modelName: 'Modellname',
    modelDescCustom: 'Benutzerdefiniertes Modell wird verwendet (Schaltfläche oben klicken, um Liste erneut abzurufen)',
    modelDescFetchFailed: 'Abruf der Modellliste fehlgeschlagen. Überprüfen Sie API-Schlüssel und Endpunkt-URL, oder geben Sie eine Modell-ID ein und klicken Sie auf Verbindung testen.',
    modelInputPlaceholder: 'Modell-ID eingeben, dann Verbindung testen',

    switchToDropdown: 'Zur Dropdown-Auswahl wechseln',
    useDropdownButton: 'Dropdown verwenden',

    // Test & Save
    testConnectionName: 'Verbindung testen',
    testConnectionDesc: 'Konfiguration überprüfen und LLM-API-Aufruf validieren',
    testButton: 'Verbindung testen',
    testing: 'Wird getestet...',

    saveSettingsName: 'Einstellungen speichern',
    saveSettingsDesc: 'Aktuelle Konfiguration speichern',
    saveButton: 'Einstellungen speichern',
    testConnectionSuccessful: 'Verbindung erfolgreich',
    testConnectionFailed: 'Verbindung fehlgeschlagen',
    testConnectionProvider: 'Anbieter: ',
    errorUnknown: 'Unbekannter Fehler',
    savedNotice: 'Einstellungen gespeichert!',

    // Issue #137: LLM-Fallback-Hinweise
    fallbackThinkingDialect: 'Denksteuerung: Zum Dialekt "{dialect}" gewechselt (dieser Anbieter verwendet ein anderes Format für die Denksteuerung). Ausgabe unverändert.',
    fallbackThinkingNone: 'Denksteuerung für diesen Anbieter vollständig deaktiviert. Es können weiterhin Reasoning-Inhalte erscheinen; falls ja, versuchen Sie ein anderes Modell.',
    fallbackParamStripped: 'Parameter "{field}" wird von diesem Anbieter nicht unterstützt. Aus der Anfrage entfernt; Verhalten kann von der Konfiguration abweichen.',

    // Wiki Folder
    wikiSection: 'Wiki-Konfiguration',
    wikiFolderName: 'Wiki-Ordner',
    wikiFolderDesc: 'Speicherort für generierte Wiki-Seiten',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'Bitte zunächst API-Schlüssel konfigurieren',
    llmNotReady: 'LLM ist nicht konfiguriert. Gehen Sie zu Einstellungen → Karpathy LLM Wiki, um Ihren Anbieter zu konfigurieren und den Verbindungstest zu bestehen.',
    errorFetchFailed: 'Fehlgeschlagen: {}',

    // Query Settings
    querySectionTitle: 'Wiki-Anfrage-Konfiguration',
    maxConversationHistoryName: 'Maximaler Konversationsverlauf',
    maxConversationHistoryDesc: 'Konversationsnachrichten begrenzen, um Token-Überlauf zu vermeiden',
    maxConversationHistoryHint: 'Empfehlung: 50 Runden nicht überschreiten',
    numberRangeValidation: 'Bitte eine Zahl zwischen 1 und 50 eingeben',
    numberRangeClamped: 'Wert außerhalb des Bereichs (1-500), automatisch auf {} gesetzt',
    // Query Modal UI
    queryModalTitle: 'Wiki-Anfrage — Konversationelle Abfrage',
    queryModalPlaceholder: 'Frage eingeben...',
    queryModalSendButton: 'Senden',
    queryModalStopButton: 'Stopp',
    queryModalSaveButton: 'Im Wiki speichern',
    queryModalClearButton: 'Verlauf löschen',
    queryModalHistoryCount: 'Konversationsverlauf: {}/{} Runden',
    queryModalStreaming: 'Streaming...',
    queryModalFallbackStreaming: 'Streaming nicht unterstützt, Wechsel zu Nicht-Streaming. Bitte warten...',
    queryPhaseSearching: 'Wiki-Index wird analysiert, relevante Seiten werden ausgewählt...',
    queryPhaseFoundPages: '{count} Seite(n) gefunden: {pages}',
    queryPhaseLoadingPages: 'Seiteninhalt wird geladen...',
    queryPhaseContextReady: 'Kontext bereit. Antwort wird generiert...',
    queryPhaseGenerating: 'Generierung... (verstrichen {time}s)',
    queryPhaseNonStreaming: 'Nicht-Streaming-Modus, Antwort wird generiert... (verstrichen {time}s)',
    queryModalErrorPrefix: 'Fehler: ',
    queryModalHint: 'Anfragen basieren auf Wiki-Inhalten. Klicke auf "Im Wiki speichern", um wertvolle Konversationen als Wiki-Seiten zu extrahieren.',

    // v1.20.0: Query Wiki Denkblock-Einklapp-Zusammenfassung
    queryThinkingSummary: 'Denkprozess',
    queryThinkingSteps: 'Schritte',

    // Error Messages
    errorLLMClientNotInit: 'LLM-Client nicht initialisiert. Bitte Einstellungen speichern.',
    errorIngestFailed: 'Aufnahme fehlgeschlagen: ',
    errorQueryFailed: 'Anfrage fehlgeschlagen: ',

    // Success Messages
    ingestSuccess: 'Aufnahme erfolgreich: {} Seiten erstellt, {} Seiten aktualisiert',
    querySuccess: 'Anfrage abgeschlossen',
    lintSuccess: 'Wiki-Lint abgeschlossen',
    lintReadingPages: '{count} Wiki-Seiten werden gelesen...',
    lintReadingPagesProgress: 'Wiki-Seiten werden gelesen: {current}/{total}...',
    lintScanningLinks: 'Defekte Links werden geprüft...',
    lintScanningLinksProgress: 'Defekte Links werden geprüft: {current}/{total}...',
    lintCheckingDuplicates: 'Auf doppelte Seiten wird geprüft...',
    lintCheckingDuplicatesProgress: 'Duplikate werden überprüft: Stapel {current} ...',
    lintFixingPolluted: 'Bereinigte Seite wird repariert {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Bereinigte Seiten reparieren ({count})',
    lintDuplicateCheckFailed: 'Duplikaterkennung fehlgeschlagen — Details in der Konsole',
    lintDuplicateCheckFailedDetail: 'Duplikatprüfung fehlgeschlagen bei {step}: {error}',
    lintMergeItemFailed: 'Zusammenführung fehlgeschlagen: {source} → {target} — {error}',
    lintAliasesMissing: 'Fehlende Aliase: {count} Seite(n) ohne Aliase',
    lintAliasesSection: 'Seiten ohne Aliase [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Aliase vervollständigen ({count})',
    lintAliasesFilling: 'Aliase werden generiert {current}/{total}: {page}',
    lintAliasesFilled: 'Alias-Vervollständigung abgeschlossen. {filled}/{total} Seiten ergänzt.',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: 'Tags außerhalb des Vokabulars (erkannt) [{count}]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: 'Alias-Generierung fehlgeschlagen: {page} — {error}',
    lintFixItemFailed: 'Behebung fehlgeschlagen: [[{target}]] — {error}',
    lintLinkItemFailed: 'Verlinkung fehlgeschlagen: {page} — {error}',
    lintRetrying: 'Wiederholung ({attempt}/{max}) nach Fehler...',
    lintAnalyzingLLM: 'LLM analysiert Wiki-Gesundheit...',
    saveToWikiSuccess: 'Konversation im Wiki gespeichert!',
    saveSummary: '{entities} Entitäten, {concepts} Konzepte, {pages} Seiten',
    aliasAdded: 'Alias \'{alias}\' zur Seite \'{page}\' hinzugefügt',

    // Status Messages
    ingestingSources: 'Quellen werden aufgenommen...',
    queryingWiki: 'Wiki wird angefragt...',
    lintingWiki: 'Wiki wird geprüft...',
    savingToWiki: 'Konversation wird im Wiki gespeichert...',
    clearingHistory: 'Konversationsverlauf wird gelöscht...',

    // Buttons
    ingestButton: 'Aufnehmen',
    queryButton: 'Anfragen',
    lintButton: 'Prüfen',
    cancelButton: 'Abbrechen',

    // Links
    karpathyGistLink: 'Karpathys LLM-Wiki Gist',
    obsidianPluginAPI: 'Obsidian-Plugin-API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // Other
    availableModelsLoading: 'Verfügbare Modelle werden geladen...',
    noModelsAvailable: 'Keine Modelle verfügbar',

    // LLM Language Hint
    llmLanguageHint: 'Bitte antworten Sie auf Deutsch.',

    // Schema Configuration
    schemaSection: 'Schema-Konfiguration',
    enableSchemaName: 'Schema aktivieren',
    enableSchemaDesc: 'Schema/config.md generieren und in alle LLM-Prompts einfügen, um strukturierte Wiki-Ausgabe zu ermöglichen',
    viewSchemaButton: 'Schema ansehen / bearbeiten',
    regenerateSchemaButton: 'Standard-Schema neu generieren',
    schemaRegeneratedNotice: 'Standard-Schema neu generiert.',
    schemaRegenerateFailed: 'Schema-Generierung fehlgeschlagen',

    // Wiki-Initialisierungsstatus
    wikiInitStatusReady: 'Wiki initialisiert',
    wikiInitStatusNotReady: 'Wiki nicht initialisiert — wird beim ersten Ingest automatisch erstellt',

    // Wiki Output Language
    wikiLanguageName: 'Wiki-Ausgabesprache',
    wikiLanguageDesc: 'Alle generierten Wiki-Seiten, Indizes, Protokolle und Anfrageantworten verwenden diese Sprache',
    customWikiLanguageOption: 'Benutzerdefiniert...',
    customWikiLanguageHint: 'Sprachnamen eingeben (z. B. Italienisch, Arabisch). Wird als Ausgabesprachen-Anweisung an das LLM übergeben.',
    customWikiLanguagePlaceholder: 'z. B. Italienisch',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },
    logLabels: {
      en: { createdPages: 'Created pages', updatedPages: 'Updated pages', contradictionsFound: 'Contradictions found' },
      zh: { createdPages: '创建页面', updatedPages: '更新页面', contradictionsFound: '发现矛盾' },
      ja: { createdPages: '作成ページ', updatedPages: '更新ページ', contradictionsFound: '矛盾を発見' },
      ko: { createdPages: '생성 페이지', updatedPages: '업데이트 페이지', contradictionsFound: '모순 발견' },
      de: { createdPages: 'Erstellte Seiten', updatedPages: 'Aktualisierte Seiten', contradictionsFound: 'Widersprüche gefunden' },
      fr: { createdPages: 'Pages créées', updatedPages: 'Pages mises à jour', contradictionsFound: 'Contradictions trouvées' },
      es: { createdPages: 'Páginas creadas', updatedPages: 'Páginas actualizadas', contradictionsFound: 'Contradicciones encontradas' },
      pt: { createdPages: 'Páginas criadas', updatedPages: 'Páginas atualizadas', contradictionsFound: 'Contradições encontradas' },
    },

    // Extraction Settings
    extractionSectionTitle: 'Extraktion',
    extractionGranularityName: 'Extraktions-Granularität',
    extractionGranularityDesc: 'Steuert Extraktionen pro Quelldatei. Höher = mehr Seiten/API-Verbrauch.\nFein: Tiefenanalyse. Standard: Tägliche Notizen. Grob: Schnelle Übersicht. Minimal: 100+ Dateien stapeln. Benutzerdefiniert: Eigene Limits (max 500).\nTipp: Verwenden Sie Minimal/Grob für Ordner mit vielen Dateien zur Zeit- und Kosteneinsparung.',
    extractionGranularityFine: 'Fein — Tiefenanalyse (≤100 Elemente)',
    extractionGranularityStandard: 'Standard — Tägliche Notizen (≤50 Elemente)',
    extractionGranularityCoarse: 'Grob — Schnellübersicht (≤10 Elemente)',
    extractionGranularityMinimal: 'Minimal — Stapelverarbeitung 100+ Dateien (≤5 Elemente)',
    extractionGranularityCustom: 'Benutzerdefiniert — Eigene Limits festlegen (1~500)',
    customEntityLimitName: 'Benutzerdefiniertes Entitätslimit',
    customEntityLimitDesc: 'Maximale Anzahl zu extrahierender Entitäten pro Quelldatei (1-500)',
    customConceptLimitName: 'Benutzerdefiniertes Konzeptlimit',
    customConceptLimitDesc: 'Maximale Anzahl zu extrahierender Konzepte pro Quelldatei (1-500)',

    // Issue #85 v2: Tag-Vokabular (Chip-Eingabe, in Wiki-Konfiguration eingebettet)
    tagVocabularyInlineDesc: 'Kontrolliertes Vokabular für entity- und concept-Frontmatter-Tags. Verschachtelte Obsidian-Tags mit „/" bleiben erhalten.',
    tagVocabularyModeName: 'Tag-Vokabular-Konfiguration',
    tagVocabularyModeDescDefault: 'Standard verwendet eingebaute Tags: {}. Wechseln Sie zu „Benutzerdefiniert", um Ihr eigenes Vokabular zu definieren.',
    tagVocabularyModeDescCustom: 'Benutzerdefiniert: Definieren Sie unten Ihre eigenen entity- und concept-Tags per Chip-Eingabe — Enter oder Komma zum Hinzufügen, × zum Entfernen.',
    tagVocabularyModeDefault: 'Standard (eingebaute Subtyp-Tags)',
    tagVocabularyModeCustom: 'Benutzerdefiniert (eigene)',
    customEntityTagsName: 'Benutzerdefinierte Entitäts-Tags',
    customEntityTagsDesc: 'Enter oder Komma zum Hinzufügen eines Chips, × zum Entfernen. Verschachtelte Tags mit „/" bleiben erhalten.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'Benutzerdefinierte Konzept-Tags',
    customConceptTagsDesc: 'Enter oder Komma zum Hinzufügen eines Chips, × zum Entfernen. Verschachtelte Tags mit „/" bleiben erhalten.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: 'Doppeltes Tag übersprungen',

    // Ingestion Acceleration
    accelerationSectionTitle: 'Aufnahmen-Beschleunigung',
    pageGenerationConcurrencyName: 'LLM-Parallelität',
    pageGenerationConcurrencyDesc: 'Anzahl paralleler LLM-Aufrufe während Aufnahme und Lint-Operationen. Höhere Werte beschleunigen die Verarbeitung, erhöhen aber API-Kosten und können Ratenbegrenzungen auslösen.',
    concurrencyValueSingular: 'Aktuelle Parallelität: {} (seriell — am sichersten)',
    concurrencyValuePlural: 'Aktuelle Parallelität: {} (parallel)',
    batchDelayName: 'Batch-Verzögerung (ms)',
    batchDelayDesc: 'Verzögerung zwischen parallelen Stapeln zur Vermeidung von API-Ratenbegrenzungen (100–2000 ms). Aktuell: {}ms. Erhöhen bei 429-Fehlern.',

    // Auto Maintenance
    autoMaintainSection: 'Automatische Wartung',
    autoMaintainBetaBadge: 'BETA — Experimentelle Funktion. Kann Probleme aufweisen. Nur für erfahrene Benutzer empfohlen.',
    autoWatchName: 'Ordner beobachten',
    autoWatchDesc: 'Neue oder geänderte .md-Dateien in den beobachteten Ordnern automatisch erkennen und benachrichtigen oder automatisch aufnehmen',
    watchedFoldersName: 'Beobachtete Ordner',
    watchedFoldersDesc: 'Ordner, die auf neue Inhalte überwacht werden. Klicke auf "Ordner hinzufügen", um aus deinem Vault auszuwählen.',
    addWatchedFolderButton: 'Ordner hinzufügen',
    removeWatchedFolderButton: 'Entfernen',
    webClipperPresetName: 'Clippings beobachten (Web Clipper)',
    webClipperPresetDesc: 'Den Clippings/-Ordner von Obsidian Web Clipper zur Beobachtungsliste hinzufügen. Webclips werden automatisch ins Wiki aufgenommen.',
    noWatchedFoldersHint: 'Keine Ordner konfiguriert. Füge einen Ordner hinzu oder aktiviere die Clippings-Voreinstellung.',
    autoWatchModeName: 'Beobachtungsmodus',
    autoWatchModeDesc: '"Nur benachrichtigen" zeigt eine Eingabeaufforderung. "Automatisch aufnehmen" verarbeitet still.',
    watchModeNotify: 'Nur benachrichtigen',
    watchModeAuto: 'Automatisch aufnehmen',
    autoWatchDebounceName: 'Entprell-Verzögerung (Sekunden)',
    autoWatchDebounceDesc: 'Wartezeit vor der Aufnahmeauslösung nach einer Dateiänderung (1–60 Sekunden)',
    periodicLintName: 'Periodische Prüfung',
    periodicLintDesc: 'LLM-Prüfung zeitgesteuert ausführen, nur wenn sich Quelldateien seit der letzten Prüfung geändert haben',
    periodicLintOff: 'Aus',
    periodicLintHourly: 'Stündlich',
    periodicLintDaily: 'Täglich',
    periodicLintWeekly: 'Wöchentlich',
    autoSmartFixName: 'Automatische Smart-Korrektur',
    autoSmartFixDesc: 'Wenn Lint ausgeführt wird, alle Korrekturen (Smart Fix All) automatisch anwenden, ohne das Berichts-Modal anzuzeigen. Die Zusammenfassung wird nach Abschluss weiterhin angezeigt.',
    autoSmartFixNotice: 'Automatische Smart-Korrektur: Alle Korrekturen werden angewendet...',
    startupCheckName: 'Schnellkorrekturen beim Start ausführen',
    startupCheckDesc: 'Beim Laden des Plugins低级 Formatprobleme (sources-Feld, doppelt verschachtelte Wikilinks) automatisch korrigieren und Wiki-Ordnerstruktur überprüfen. Standardmäßig aktiviert.',
    suggestSchemaCommand: 'Schema-Aktualisierungen vorschlagen',
    autoMaintainCostWarning: '⚠️ Kostenhinweis: Funktionen zur automatischen Wartung verbrauchen API-Tokens. "Automatisch aufnehmen" löst bei jeder Quelldatei-Änderung LLM-Aufrufe aus. "Periodische Prüfung" führt zeitgesteuerte LLM-Gesundheitsprüfungen durch (nur bei erkannten Quelländerungen). Sorgfältig konfigurieren, um unerwartete Kosten zu vermeiden.',

    // Notices
    startupCheckSummary: 'Wiki enthält {pages} Seiten ({entities} Entitäten, {concepts} Konzepte, {sources} Quellen)',
    watcherActiveNotice: 'Wiki: Datei-Beobachtung aktiv — beobachtete Ordner werden überwacht',
    watchIngestNotice: 'Wiki: {count} Datei(en) in sources/ geändert. "Quellen aufnehmen" ausführen, um zu verarbeiten.',
    autoIngestRunning: 'Automatische Aufnahme von {count} geänderter(n) Datei(en)...',
    autoIngestComplete: 'Automatische Aufnahme abgeschlossen: {success} erfolgreich, {fail} fehlgeschlagen',
    scheduledLintRunning: 'Geplante Wiki-Prüfung wird ausgeführt...',
    wikiLintStats: 'Wiki-Prüfung: {pages} Seiten ({entities} Entitäten, {concepts} Konzepte, {sources} Quellen)',
    wikiHealthStats: 'Wiki-Gesundheit: {pages} Seiten ({entities} Entitäten, {concepts} Konzepte, {sources} Quellen){indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki-Schnellkorrekturen abgeschlossen',
    startupCheckStructureLabel: 'Wiki-Struktur',
    startupCheckStructureOk: 'vollständig',
    startupCheckStructureMissing: 'unvollständig — wird beim ersten Ingest automatisch erstellt',
    startupCheckSourcesLabel: 'Sources normalisiert',
    startupCheckSourcesClean: 'bereits sauber',
    startupCheckSourcesCleaned: '{files} Datei(en), {entries} Eintrag/Einträge bereinigt',
    startupCheckDisableHint: 'Zum Deaktivieren: Einstellungen → Auto-Wartung → Schnellkorrekturen beim Start ausführen',
    lintWikiStart: 'Wiki-Prüfung wird gestartet...',
    lintWikiComplete: 'Wiki-Prüfung abgeschlossen',
    lintWikiFailed: 'Wiki-Prüfung fehlgeschlagen',
    analyzingSchema: 'Wiki wird analysiert und Schema-Vorschläge werden generiert...',
    schemaSuggestionGenerated: 'Schema-Vorschläge generiert, siehe wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'Keine Schema-Aktualisierungen erforderlich.',
    schemaSuggestionFailed: 'Schema-Vorschlag fehlgeschlagen',
    schemaNotFoundNotice: 'Schema-Datei nicht gefunden. Schema aktivieren, um sie zu erstellen.',
    selectFolderNoMdFiles: 'Keine Markdown-Dateien im Ordner: {path}',
    batchIngestSkipNotice: '{skipped}/{total} bereits aufgenommene Dateien werden übersprungen. {new} neue Datei(en) werden aufgenommen...',
    batchIngestAllIngested: 'Alle {total} Dateien in diesem Ordner wurden bereits aufgenommen.',
    batchIngestStarting: '{count} Datei(en) aus "{folder}" werden aufgenommen — dies kann mehrere Minuten dauern. Ein Bericht erscheint bei Abschluss.',
    batchIngestComplete: 'Batch-Aufnahme abgeschlossen: {success}/{total} erfolgreich, {fail} fehlgeschlagen',
    batchIngestFailedFiles: 'Fehlgeschlagene Dateien:',
    historyTruncated: 'Verlauf auf letzte {max} Runden gekürzt',
    historyCleared: 'Verlauf gelöscht',

    // User Feedback Loop
    reviewedPagePreserved: 'Benutzergeprüfte Inhalte werden beibehalten für: {}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: 'Im Wiki speichern?',
    querySuggestSaveDesc: 'Diese Konversation enthält wertvolles Wissen. Im Wiki speichern?',
    querySuggestSaveYes: 'Speichern',
    querySuggestSaveNo: 'Verwerfen',

    // Ingestion Report
    ingestReportElapsedTime: 'Verstrichene Zeit',
    ingestReportSkippedFiles: 'Übersprungen (bereits aufgenommen)',
    ingestReportFailedGuidance: 'Diese Elemente konnten nicht automatisch erstellt werden. Du kannst die entsprechenden Seiten manuell erstellen oder die Extraktions-Granularität senken und die Quelldatei erneut aufnehmen.',
    ingestReportCollisions: 'Cross-Type-Kollisionen (als Aliase zusammengeführt)',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: 'Einzelne Quelle aufnehmen',
    cmdIngestFolder: 'Aus Ordner aufnehmen',
    cmdQueryWiki: 'Wiki anfragen',
    cmdLintWiki: 'Wiki prüfen',
    cmdRegenerateIndex: 'Index neu generieren',
    cmdSuggestSchema: 'Schema-Aktualisierungen vorschlagen',
    cmdCancelIngestion: 'Aktuelle Aufnahme abbrechen',
    cmdIngestActiveFile: 'Aktuelle Datei aufnehmen',
    cmdViewHistory: 'Ingestionsverlauf anzeigen',
    noActiveFile: 'Keine Datei geöffnet',
    mdOnlyFile: 'Nur Markdown-Dateien können aufgenommen werden',

    // Ingestion status bar
    ingestionStatusBar: 'Aufnahme läuft... zum Abbrechen klicken',
    lintStatusBar: 'Prüfung läuft... zum Abbrechen klicken',
    ingestStatusAnalyzing: 'Aufnahme läuft... (zum Abbrechen klicken)',
    lintStatusReading: 'Prüfung läuft... (zum Abbrechen klicken)',
    lintStatusDuplicates: 'Prüfung läuft... (zum Abbrechen klicken)',
    lintStatusScanningLinks: 'Prüfung läuft... (zum Abbrechen klicken)',
    lintStatusAnalyzing: 'Prüfung läuft... (zum Abbrechen klicken)',
    ingestionCancelling: 'Wird abgebrochen — Stopp nach aktuellem Batch',
    ingestionCancelled: 'Aufnahme abgebrochen',
    crossTypeCollisionNotice: '{count} Einträge als Cross-Type-Alias zusammengeführt (Entity ↔ Concept Duplikate verhindert)',

    // Lint Report
    lintReportTitle: 'Wiki-Prüfbericht',
    lintReportSummary: 'Wiki-Statusübersicht: {total} Seiten gesamt, {aliasesMissing} Seiten ohne Aliase, {duplicates} Duplikate, {deadLinks} defekte Links ({deadLinkFromDup} betreffen Duplikate), {orphans} verwaiste Seiten ({orphanFromDup} sind Duplikate), {emptyPages} leere Seiten, {ungroundedQuotes} unbelegte Zitate, {tagViolations} Tags außerhalb des Vokabulars. Lint-Dauer: {elapsedSeconds}s',

    // Advanced LLM Settings (Issues #99 / #128)
    advancedSettingsModeName: 'Erweiterte Parametereinstellungen',
    advancedSettingsModeDesc: 'Im Standardmodus wird das Standardverhalten Ihres Providers verwendet — es werden keine Felder für Denksteuerung, Temperatur oder Wiederholungsstrafe gesendet. Dies funktioniert für die meisten Benutzer. Wechseln Sie nur dann zu „Benutzerdefiniert“, wenn Sie die Provider-Standards explizit überschreiben müssen (z. B. einen bestimmten Denksteuerungsdialekt erzwingen, eine andere als die Standardtemperatur festlegen usw.).',
    advancedSettingsDefault: 'Standard (Provider-Verhalten verwenden)',
    advancedSettingsCustom: 'Benutzerdefiniert (Provider-Standards überschreiben)',
    disableThinkingName: 'Thinking deaktivieren',
    disableThinkingDesc: 'Opt-in. Wenn aktiviert, sendet das Plugin eine Denksteuerungsanweisung an den Provider und durchläuft eine 3-stufige Dialekt-Fallback-Kette (anthropic → openai → none), falls der Provider sie ablehnt. Verwenden Sie dies nur, wenn Ihr Provider Denkinhalte in die Antwort einstreut und Sie diese unterdrücken müssen. Die meisten Provider verarbeiten Denkprozesse korrekt von selbst — sie deaktiviert zu lassen (Standard) bietet bessere Qualität.',
    // Issue #137: Kompatibilitätshinweise (kurz gehalten; keine Provider-Liste)
    extractionTemperatureName: 'Extraktionstemperatur',
    extractionTemperatureDesc: 'Bereich 0–2. Niedrigere Werte machen die LLM-Ausgabe deterministischer und originalgetreuer. Höhere Werte machen sie kreativer. Leer lassen = Provider-Standard. Lehnt Ihr Anbieter diesen Wert ab, entfernt das Plugin das Feld automatisch und zeigt einen einmaligen Hinweis.',
    chatTemperatureName: 'Abfragetemperatur',
    chatTemperatureDesc: 'Bereich 0–2. Wie Extraktionstemperatur, betrifft aber nur Chat-/Query-Antworten. Leer lassen = Provider-Standard. Lehnt Ihr Anbieter diesen Wert ab, entfernt das Plugin das Feld automatisch und zeigt einen einmaligen Hinweis.',
    repetitionPenaltyName: 'Wiederholungsstrafe',
    repetitionPenaltyDesc: 'Bereich 0–2. Höhere Werte reduzieren Wiederholungen. Leer lassen = Provider-Standard. Kompatibilitätshinweis: Viele Cloud-Anbieter akzeptieren dieses Feld nicht. Das Plugin entfernt es bei HTTP 400 automatisch und zeigt einen einmaligen Hinweis.',
    temperaturePlaceholder: 'leer = Provider-Standard',
    lintDeadLinkSection: 'Defekte Links (erkannt) [{count}]',
    lintEmptyPageSection: 'Leere Seiten (erkannt) [{count}]',
    lintOrphanSection: 'Verwaiste Seiten (erkannt) [{count}]',
    lintContradictionSection: 'Widersprüche (erkannt)',
    lintDuplicateSection: 'Doppelte Seiten (erkannt)',
    lintNoIssuesFound: 'Keine Duplikate, defekten Links, leeren Seiten, verwaisten Seiten oder unbelegten Zitate erkannt.',
    lintQuoteGroundingSection: 'Unbelegte Zitate (erkannt) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: "{quote}"',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (Seite existiert nicht){dupFlag}',
    lintDeadLinkMore: '- ... {count} weitere defekte Links',
    lintEmptyPageItem: '- [[{page}]] — weniger als 50 Zeichen substanziellen Inhalts',
    lintOrphanItem: '- [[{page}]] — keine anderen Wiki-Seiten verweisen hierher{dupFlag}',
    lintPollutedSection: 'Verschmutzte Seiten (erkannt) [{count}]',
    lintPollutedItem: '- [[{page}]] → sollte "{clean}" sein',
    lintSourcesNormalizedSection: 'Sources normalisiert (automatisch repariert) [{files} Dateien / {entries} Einträge]',
    lintSourcesNormalizedItem: '{entries} verschmutzte sources-Einträge in {files} Datei(en) bereinigt (externe Pfade, .md-Erweiterungen, Alias-Pipes entfernt und dedupliziert).',
    lintDuplicateItem: '- [[{target}]] und [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ betrifft doppelte Seite)',
    lintOrphanIsDuplicate: ' (⚠️ doppelte Seite)',
    lintContradictionOpen: 'Offene Widersprüche: {count}',
    lintContradictionAutoFixed: '({count} in diesem Durchlauf automatisch behoben)',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Erkannt',
    lintContradictionStatusPendingFix: 'Behebung ausstehend',
    lintLLMAnalysisHeading: '## LLM-Analyse',

    // Lint Analysis Prompt
    lintAnalysisPrompt: 'Du bist ein Wiki-Wartungsassistent. Überprüfe die Wiki-Gesundheit anhand der folgenden Informationen.\n\nWiki-Index:\n{index}\n\nWiki-Seiteninhalt-Stichprobe ({total} Seiten gesamt, {sample} Seiten angezeigt):\n{contentSample}\n\nErgebnisse der programmatischen Prüfung (bereits verifiziert, nicht wiederholen):\n{progReport}\n\nPrüfe die folgenden Aspekte (defekte Links/leere/verwaiste Seiten, die bereits durch programmatische Prüfungen erkannt wurden, überspringen):\n1. **Widersprüche** — ob verschiedene Seiten sich bei denselben Fakten widersprechen\n2. **Veraltung** — ob Behauptungen offensichtlich veraltet sind\n3. **Fehlend** — welche wichtigen Konzepte keine eigenständigen Seiten haben\n4. **Struktur** — ob die Seitenstruktur angemessen und Querverweise ausreichend sind\n\nAusgabeformat: Verwende Markdown, beginnend mit "## LLM-Analyse". Jede Feststellung in einer Zeile "- [konkretes Problem]". Wenn keine Probleme: "Keine offensichtlichen Probleme gefunden."',

    // Lint Fix Progress
    lintFixProgress: 'Behebung {current}/{total}: [[{target}]]',
    lintFixDeadComplete: 'Behebung defekter Links abgeschlossen. {fixed}/{total} Elemente behoben.',
    lintFillProgress: 'Erweiterung {current}/{total}: {page}',
    lintFillComplete: 'Seitenerweiterung abgeschlossen. {filled}/{total} Seiten gefüllt.',
    lintDeleteCompleted: '{count} leere Stubs gelöscht',
    lintDeleteFailed: 'Fehler beim Löschen von {failed}/{total} leeren Stubs (Details in der Konsole)',
    lintFillFailed: 'Erweiterung fehlgeschlagen: {page} — {error}',
    lintLinkProgress: 'Verlinkung {current}/{total}: {page}',
    lintLinkComplete: 'Verwaiste-Seiten-Verlinkung abgeschlossen. {linked} Seiten verlinkt.',
    lintFixNoAction: 'Keine Maßnahme ergriffen (kein Client)',
    lintFixIndexUpdated: 'Wiki-Index und Protokoll aktualisiert.',
    lintPollutedFixed: 'Beschädigte Seiten behoben: {fixed}/{total}. Index neu generiert.',
    regenerateIndexCompleted: 'Index neu generiert',
    operationFailed: 'Fehlgeschlagen: ', 
    lintFixAllComplete: 'Alle Behebungen abgeschlossen. Details im Protokoll.',

    // Lint Report Modal
    lintModalActionsTitle: 'Behebungsvorschläge (benötigt LLM-Tokens):',
    lintLogReference: 'Vollständiger Bericht in log.md gespeichert',
    lintModalFixDeadLinks: 'Defekte Links beheben ({count})',
    lintModalExpandEmpty: 'Leere Seiten erweitern ({count})',
    lintModalDeleteEmpty: 'Leere Stubs löschen ({count})',   
    lintModalLinkOrphans: 'Verwaiste Seiten verlinken ({count})',
    lintModalAnalyzeSchema: 'Schema analysieren',
    lintModalMergeDuplicates: 'Duplikate zusammenführen ({count})',
    lintModalFixAll: 'Intelligente Gesamtbehebung ({count} Probleme)',
    lintMergeProgress: 'Zusammenführung {current}/{total}: {source} → {target}',
    lintMergeComplete: 'Duplikat-Zusammenführung abgeschlossen. {merged}/{total} Paare zusammengeführt.',

    // Ingest Report Modal
    ingestReportTitle: 'Aufnahmebericht',
    ingestReportSourceFile: 'Quelldatei',
    ingestReportCreated: 'Erstellt',
    ingestReportUpdated: 'Aktualisiert',
    ingestReportContradictions: 'Widersprüche gefunden',
    ingestReportFailedTitle: 'Aufnahme fehlgeschlagen',
    ingestReportErrorDetail: 'Fehlerdetail',
    ingestReportClose: 'Schließen',
    ingestReportCreatedPages: 'Erstellte Seiten: {count}',
    ingestReportUpdatedPages: 'Aktualisierte Seiten: {count}',
    ingestReportEntitiesCount: '{count} Entitäten',
    ingestReportConceptsCount: '{count} Konzepte',
    ingestReportContradictionsFound: 'Gefundene Widersprüche: {count}',
    ingestReportEntityType: 'Entität',
    ingestReportConceptType: 'Konzept',
    timeMinutes: 'Min',
    timeSeconds: 'Sek',

    // Ratenbegrenzungs-Warnungen
    rateLimitDetected: '⚠️ Ratenbegrenzung erkannt: {count} Seite(n) mit 429-Fehlern fehlgeschlagen. Empfehlungen: (1) Parallelität auf {suggestedConcurrency} oder 1 (seriell) reduzieren, (2) Batch-Verzögerung auf {suggestedDelay}ms erhöhen, (3) Zu einem Anbieter mit höheren Ratenbegrenzungen wechseln.',
    rateLimitDetectedShort: '⚠️ Ratenbegrenzung erreicht — Reduzieren Sie die Parallelität oder erhöhen Sie die Batch-Verzögerung in Einstellungen → Aufnahmebeschleunigung.',

    longSourceNotice: '📄 "{filename}" hat {lines} Zeilen ({size}). Lange Texte erfordern iterative Stapel-Extraktion — das LLM liest das gesamte Dokument in mehreren Durchläufen. Dies kann einige Minuten dauern. Bitte haben Sie Geduld.',
    longSourceNoticeShort: '📄 Große Datei erkannt ({lines} Zeilen). Die Ingestion kann einige Zeit dauern.',

    // Ingestionsverlauf-Panel (#122) — UI-Texte
    historyButton: 'Operationsverlauf',
    historyButtonDesc: 'Letzte Ingestionen, Lint-Berichte und andere Änderungen Ihres Wikis anzeigen',
    historyButtonOpen: 'Verlauf anzeigen',
    historyModalTitle: 'Operationsverlauf',
    historyModalSubtitle: 'Letzte Änderungen Ihres LLM-Wikis',
    historyEmpty: 'Noch keine Operationen aufgezeichnet. Ingestiere eine Notiz oder führe Lint aus, um diese Liste zu füllen.',
    historyReadError: 'Operationsprotokoll konnte nicht gelesen werden: {error}',
    historyEntryKindIngest: 'Ingestion',
    historyEntryKindMaintenance: 'Wartung',
    historyEntryKindFix: 'Korrektur',
    historyEntryKindOther: 'Sonstige',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Quelle: {source}',
    historyEntrySourceUnknown: 'Unbenannter Ingest',
    historyEntryCreatedLabel: 'Erstellt',
    historyEntryUpdatedLabel: 'Aktualisiert',
    historyEntryCreatedCount: '{count} erstellt',
    historyEntryUpdatedCount: '{count} aktualisiert',
    historyEntryNoChanges: 'Keine Seitenänderungen',
    historyEntryContradictions: '⚠️ {count} Widerspruch(e)',
    historyEntrySectionCreated: 'Erstellte Seiten',
    historyEntrySectionUpdated: 'Aktualisierte Seiten',
    historyEntrySectionContradictions: 'Widersprüche',
    historyEntrySectionDetails: 'Details',
    historyEntryOpenPage: 'Öffnen',
    historyEntryDetailsNoContradictions: 'Keine Widersprüche gefunden',
    historySearchPlaceholder: '🔍 Nach Quelltitel oder Seitenpfad suchen…',
    historyFilterAll: 'Alle',
    historyFilterIngest: 'Nur Ingest',
    historyFilterMaintenance: 'Nur Wartung',
    historyFilterFix: 'Nur Korrektur',
    historyFilterContradictions: '⚠️ Mit Widersprüchen',
    historyRefreshButton: '⟳ Aktualisieren',
    historyExpandDay: 'Zum Erweitern klicken',
    historyCollapseDay: 'Zum Einklappen klicken',
    historyShowMore: '{count} ältere Einträge anzeigen',
    historyNoMatch: 'Keine Operationen entsprechen Ihrer Suche/Ihrem Filter.',
    historyCloseButton: 'Schließen',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'Berichts-Befunde',
    historyKpiPages: 'Seiten',
    historyKpiDeadLinks: 'Tote Links',
    historyKpiOrphans: 'Verwaist',
    historyKpiEmpty: 'Leer',
    historyKpiDuplicates: 'Duplikate',
    historyKpiTagViolations: 'Tag-Probleme',
    historyKpiUnsourced: 'Unbelegt',
    historyKpiDuration: 'Lint-Zeit',
    historyKpiDurationSec: '{seconds}s',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'Tote Links ({count})',
    historySectionTagViolations: 'Tag-Verstöße ({count})',
    historySectionOrphans: 'Verwaiste Seiten ({count})',
    historySectionEmptyPages: 'Leere Seiten ({count})',
    historySectionLlmAnalysis: 'LLM-Analyse ({count})',
    historyDeadLinkSource: 'Quelle',
    historyDeadLinkTarget: 'Fehlt',
    historyOpenInLog: 'In log.md öffnen',
    historyShowMoreItems: '{count} weitere ausklappen',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ unverändert',
    historyChipContradiction: 'Widerspruch',
    historyChipOutdated: 'Veraltet',
    historyChipMissing: 'Fehlt',
    historyChipStructure: 'Struktur',
    historySeverityHigh: 'Hoch',
    historySeverityMedium: 'Mittel',
    historySeverityLow: 'Niedrig',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Ihr Wiki hat {dead} tote Links, {orphans} verwaiste Seiten und {tags} Tag-Probleme. Letzte Lint-Dauer: {duration}.',
    historyGlobalInsightClean: 'Ihr Wiki ist sauber — keine toten Links, verwaisten Seiten oder Tag-Probleme erkannt.',
    historyGlobalInsightNoData: 'Noch keine Wartungsberichte — führen Sie Lint aus.',
    historyModalHeaderTitle: 'Operationsverlauf',
    historyModalSubtitleWithCount: 'Letzte Änderungen Ihres LLM-Wikis · {count} Einträge',
    historyTimeRangeAll: 'Gesamter Zeitraum',
    historyTimeRange1d: 'Letzter Tag',
    historyTimeRange3d: 'Letzte 3 Tage',
    historyTimeRange1w: 'Letzte Woche',
    historyTimeRange1m: 'Letzter Monat',
    historyIngestTotal: 'Seiten gesamt',
    historyIngestByType: 'Nach Typ',
    historyIngestSource: 'Quelldatei',
    historyIngestNoTimestamp: 'Kein Zeitstempel',
    historyIngestFirstTime: 'Erste Ingestion',
    historyIngestLatestTime: 'Letzte Ingestion',
    historyTimeRangeCustom: 'Benutzerdef. Zeitraum',
    historyCustomRangeFrom: 'Von',
    historyCustomRangeTo: 'Bis',
    historyCustomRangeApply: 'Anwenden',
    historyCustomRangeClear: 'Zurücksetzen',
} as const;