export const FR_TEXTS = {
    // Plugin Info
    pluginTitle: 'Paramètres de Karpathy LLM Wiki',
    pluginIntro: "Ce plugin implémente le concept de {{link}} pour Obsidian. Il lit vos notes, utilise l'IA pour extraire des entités et des concepts, et construit un wiki structuré et interconnecté dans votre coffre.",
    karpathyLinkText: "LLM Wiki d'Andrej Karpathy",

    // Features Section
    featuresTitle: 'Fonctionnement',
    workflow1Title: '1. Importer',
    workflow1Desc: 'Sélectionnez une note — l\'IA extrait les entités, concepts et relations dans des pages wiki.',
    workflow2Title: '2. Interroger',
    workflow2Desc: 'Discutez avec votre wiki — les réponses s\'appuient sur vos connaissances importées.',
    workflow3Title: '3. Maintenir',
    workflow3Desc: "L'index, les liens croisés et les vérifications automatiques assurent la santé du wiki.",

    // Language Switcher
    languageTitle: 'Langue de l\'interface',
    languageDesc: 'Sélectionnez la langue du panneau des paramètres. Redémarrez le plugin pour appliquer les changements de langue à la palette de commandes.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',

    // Status
    statusTitle: 'État du client LLM',
    llmWikiStatusSection: 'État LLM-Wiki',
    statusInitialized: 'Initialisé',
    statusReady: 'LLM prêt',
    statusNotReady: 'LLM non configuré — terminez la configuration ci-dessus et réussissez le test de connexion',
    statusNotInitialized: 'Non initialisé',
    currentProvider: 'Fournisseur actuel',

    // Provider Configuration
    providerSection: 'Configuration LLM',
    providerName: 'Fournisseur LLM',
    providerDesc: 'Sélectionnez un fournisseur prédéfini ou un service compatible OpenAI personnalisé. Pour Coding Plan ou bundles similaires: choisissez Custom OpenAI/Anthropic, saisissez manuellement le Base URL et API Key du fournisseur',

    // API Key
    apiKeyName: 'Clé API',
    apiKeyDesc: 'Saisissez votre clé API fournie par le fournisseur',
    apiKeyPlaceholder: 'Saisir la clé API',

    // Base URL
    baseUrlName: 'URL de base de l\'API',
    baseUrlDescCustom: 'Obligatoire : point de terminaison compatible OpenAI personnalisé',
    baseUrlDescOverride: 'Facultatif : remplacer l\'URL de base prédéfinie',

    // Ollama Hint
    ollamaHint: "Ollama fonctionne localement, aucune clé API n'est requise",
    lmstudioHint: 'LM Studio fonctionne localement, la clé API est facultative',
    maxTokensPerCallName: 'Max. tokens de sortie par appel',
    maxTokensPerCallDesc: 'Limite le nombre de tokens que le modèle peut générer en une seule réponse. Réduisez si vous utilisez un modèle local avec une petite fenêtre de contexte et que vous rencontrez des erreurs. Pour les modèles cloud, conservez la valeur par défaut (0 = aucune limite).',

    slugCaseName: 'Casse des noms de fichiers',
    slugCaseDesc: "Contrôle si les noms de fichiers Wiki générés sont mis en minuscules. 'Conserver' recommandé pour les langues où la casse est significative (ex. noms allemands).",
    slugCaseLower: 'Minuscules (défaut)',
    slugCasePreserve: 'Conserver la casse',

    // Model Selection
    modelSection: 'Sélection du modèle',
    fetchModelsName: 'Récupérer les modèles disponibles',
    fetchModelsDesc: 'Obtenir la dernière liste de modèles depuis l\'API du fournisseur',
    fetchModelsButton: 'Récupérer les modèles',
    fetchingModels: 'Récupération...',
    fetchSuccess: 'Succès ! {} modèles disponibles',
    fetchFailed: 'Échec ou liste vide, veuillez saisir le nom du modèle manuellement',
    fetchNotSupported: 'Le fournisseur ne prend pas en charge la requête de liste de modèles',
    fetchErrorAuth: 'Échec d\'authentification (HTTP 401/403). Vérifiez la clé API, ou entrez un ID de modèle puis cliquez sur Tester la connexion.',
    fetchErrorEndpoint: 'Point d\'accès introuvable (HTTP 404). Vérifiez l\'URL du point d\'accès, ou entrez un ID de modèle puis cliquez sur Tester la connexion.',
    fetchErrorServer: 'Erreur du serveur du fournisseur (HTTP 5xx). Réessayez plus tard, ou entrez un ID de modèle puis cliquez sur Tester la connexion.',
    fetchErrorEmpty: 'Ce point d\'accès n\'expose pas de liste de modèles. Entrez un ID de modèle puis cliquez sur Tester la connexion.',
    fetchErrorNetwork: 'Échec de la requête réseau. Vérifiez votre connexion Internet, l\'URL du point d\'accès ou les paramètres du proxy. Vous pouvez aussi entrer un ID de modèle puis cliquer sur Tester la connexion.',

    selectModelName: 'Sélectionner un modèle',
    selectModelDesc: 'Choisir parmi {} modèles disponibles',
    customInputOption: 'Saisie personnalisée...',
    customInputHint: 'Pour utiliser d\'autres modèles, sélectionnez "Saisie personnalisée..."',

    modelName: 'Nom du modèle',
    modelDescCustom: 'Modèle personnalisé utilisé (cliquez ci-dessus pour récupérer la liste)',
    modelDescFetchFailed: 'Échec de récupération de la liste des modèles. Vérifiez la clé API et l\'URL du point d\'accès, ou entrez un ID de modèle puis cliquez sur Tester la connexion.',
    modelInputPlaceholder: 'Saisir l\'ID du modèle, puis Tester la connexion',

    switchToDropdown: 'Passer à la sélection par liste déroulante',
    useDropdownButton: 'Utiliser la liste déroulante',

    // Test & Save
    testConnectionName: 'Tester la connexion',
    testConnectionDesc: 'Vérifier que la configuration peut appeler l\'API LLM avec succès',
    testButton: 'Tester la connexion',
    testing: 'Test en cours...',

    saveSettingsName: 'Enregistrer les paramètres',
    saveSettingsDesc: 'Enregistrer la configuration actuelle',
    saveButton: 'Enregistrer',
    testConnectionSuccessful: 'Connexion réussie',
    testConnectionFailed: 'Connexion échouée',
    testConnectionProvider: 'Fournisseur : ',
    errorUnknown: 'Erreur inconnue',
    savedNotice: 'Paramètres enregistrés !',

    // v1.24.0 (Bug C 3.4 / plan C) : notification de migration progressive
    queryHistoryMigrationNotice: 'L\'historique de Query Wiki contient des liens d\'un ancien dossier wiki. Les nouvelles requêtes utilisent automatiquement le dernier dossier. Pour actualiser tous les messages enregistrés, ouvrez le panneau Query Wiki et cliquez sur le bouton « Effacer l\'historique » qui s\'y trouve.',

    // Issue #137 : Notifications de repli LLM
    fallbackThinkingDialect: 'Contrôle de réflexion : basculé vers le dialecte « {dialect} » (ce fournisseur utilise un format différent). Le résultat est inchangé.',
    fallbackThinkingNone: 'Contrôle de réflexion entièrement désactivé pour ce fournisseur. Du contenu de raisonnement peut encore apparaître ; le cas échéant, essayez un autre modèle.',
    fallbackParamStripped: 'Le paramètre « {field} » n\'est pas pris en charge par ce fournisseur. Supprimé de la requête ; le comportement peut différer de la configuration.',

    // Wiki Folder
    wikiSection: 'Configuration du Wiki',
    wikiFolderName: 'Dossier wiki',
    // v1.24.0 : indication que le redémarrage d'Obsidian est nécessaire
    // après modification (les caches du moteur et les panneaux Query Wiki ouverts doivent être reliés à nouveau).
    wikiFolderDesc: 'Emplacement des pages wiki générées. Redémarrez Obsidian après modification — les caches du moteur et les panneaux Query Wiki ouverts doivent être reliés à nouveau.',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'Veuillez d\'abord configurer la clé API',
    llmNotReady: 'LLM non configuré. Allez dans Paramètres → Karpathy LLM Wiki pour configurer votre fournisseur et réussir le test de connexion.',
    errorFetchFailed: 'Échec : {}',

    // Query Settings
    querySectionTitle: 'Configuration de l\'interrogation du wiki',
    // v1.24.0 : renommé de « Historique maximal de conversation » à
    // « Tours de mémoire de conversation » pour plus de clarté.
    // 1 = chaque tour indépendant (aucune mémoire inter-tours).
    // Le réglage est une liste déroulante, pas besoin de lister les préréglages.
    // v1.24.0 : maxConversationHistoryHint était une clé i18n inutilisée ;
    // la recommandation est désormais intégrée à la description.
    maxConversationHistoryName: 'Tours de mémoire de conversation',
    maxConversationHistoryDesc: 'Combien de tours de conversation passés le LLM voit comme mémoire. 1 = chaque tour indépendant (aucune mémoire inter-tours) ; des valeurs plus élevées permettent au modèle de se souvenir des tours antérieurs de la session. Recommandé : 1 pour Q&R ponctuel, 10–50 pour une recherche continue.',
    numberRangeValidation: 'Veuillez saisir un nombre entre 1 et 50',
    numberRangeClamped: 'Valeur hors plage (1-500), automatiquement réglée sur {}',
    // Query Modal UI
    queryModalTitle: 'Interroger le wiki — Requête conversationnelle',
    queryModalPlaceholder: 'Saisir votre question...',
    queryModalSendButton: 'Envoyer',
    queryModalStopButton: 'Arrêter',
    queryModalSaveButton: 'Enregistrer dans le wiki',
    queryModalClearButton: 'Effacer l\'historique',
    queryModalHistoryCount: 'Historique de conversation : {}/{} tours',
    queryModalStreaming: 'Génération en continu...',
    queryModalFallbackStreaming: 'La génération en continu n\'est pas prise en charge, passage en mode non continu. Veuillez patienter...',
    queryPhaseSearching: "Analyse de l'index wiki, recherche de pages pertinentes...",
    queryPhaseFoundPages: '{count} page(s) trouvée(s) : {pages}',
    queryPhaseLoadingPages: 'Chargement du contenu des pages...',
    queryPhaseContextReady: 'Contexte prêt. Génération de la réponse...',
    queryPhaseGenerating: 'Génération en cours... (écoulé {time}s)',
    queryPhaseNonStreaming: 'Mode non continu, génération de la réponse... (écoulé {time}s)',
    queryModalErrorPrefix: 'Erreur : ',
    queryModalHint: "Les requêtes s'appuient sur le contenu du wiki. Cliquez sur « Enregistrer dans le wiki » pour extraire les conversations utiles en pages wiki.",

    // v1.20.0: Résumé du bloc de réflexion pliable de Query Wiki
    queryThinkingSummary: 'Processus de réflexion',
    queryThinkingSteps: 'étapes',

    // Error Messages
    errorLLMClientNotInit: 'Client LLM non initialisé. Veuillez enregistrer les paramètres.',
    errorIngestFailed: "Échec de l'import : ",
    errorQueryFailed: 'Échec de la requête : ',
    fileWriteFailed: "Impossible de créer ou de mettre à jour le fichier : {path}",

    // Success Messages
    ingestSuccess: 'Import réussi : {} pages créées, {} pages mises à jour',
    querySuccess: 'Requête terminée',
    lintSuccess: 'Vérification du wiki terminée',
    lintReadingPages: 'Lecture de {count} pages wiki...',
    lintReadingPagesProgress: 'Lecture des pages wiki : {current}/{total}...',
    lintScanningLinks: 'Analyse des liens cassés...',
    lintScanningLinksProgress: 'Analyse des liens cassés : {current}/{total}...',
    lintCheckingDuplicates: 'Vérification des pages dupliquées...',
    lintCheckingDuplicatesProgress: 'Vérification des doublons : lot {current} ...',
    lintFixingPolluted: 'Réparation de page polluée {current}/{total} : {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Réparer les pages polluées ({count})',
    lintDuplicateCheckFailed: 'Échec de la détection des doublons — consultez la console pour les détails',
    lintDuplicateCheckFailedDetail: 'Échec de la vérification des doublons à l\'étape {step} : {error}',
    lintMergeItemFailed: 'Échec de la fusion : {source} → {target} — {error}',
    lintAliasesMissing: 'Alias manquants : {count} page(s) sans alias',
    lintAliasesSection: 'Pages sans alias [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Compléter les alias ({count})',
    lintAliasesFilling: "Génération d'alias {current}/{total} : {page}",
    lintAliasesFilled: 'Complétion des alias terminée. {filled}/{total} pages remplies.',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: 'Tags hors vocabulaire (détectés) [{count}]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: "Échec de la génération d'alias : {page} — {error}",
    lintFixItemFailed: 'Échec de la réparation : [[{target}]] — {error}',
    lintLinkItemFailed: 'Échec du lien : {page} — {error}',
    lintRetrying: 'Nouvelle tentative ({attempt}/{max}) après erreur...',
    lintAnalyzingLLM: "L'IA analyse la santé du wiki...",
    saveToWikiSuccess: 'Conversation enregistrée dans le wiki !',
    saveSummary: '{entities} entités, {concepts} concepts, {pages} pages',
    aliasAdded: "Alias '{alias}' ajouté à la page '{page}'",

    // Status Messages
    ingestingSources: 'Import des sources en cours...',
    queryingWiki: 'Interrogation du wiki...',
    lintingWiki: 'Vérification du wiki...',
    savingToWiki: 'Enregistrement de la conversation dans le wiki...',
    clearingHistory: "Effacement de l'historique de conversation...",

    // Buttons
    ingestButton: 'Importer',
    queryButton: 'Interroger',
    lintButton: 'Vérifier',
    cancelButton: 'Annuler',

    // Links
    karpathyGistLink: "Gist LLM Wiki de Karpathy",
    obsidianPluginAPI: 'API des plugins Obsidian',
    anthropicSDK: 'SDK Anthropic',
    openaiSDK: 'SDK OpenAI',

    // Other
    availableModelsLoading: 'Chargement des modèles disponibles...',
    noModelsAvailable: 'Aucun modèle disponible',

    // LLM Language Hint
    llmLanguageHint: 'Veuillez répondre en français.',

    // Schema Configuration
    schemaSection: 'Configuration du schéma',
    enableSchemaName: 'Activer le schéma',
    enableSchemaDesc: 'Générer et injecter schema/config.md dans toutes les invites LLM pour une sortie wiki structurée',
    viewSchemaButton: 'Voir / Modifier le schéma',
    regenerateSchemaButton: 'Régénérer le schéma par défaut',
    schemaRegeneratedNotice: 'Schéma par défaut régénéré.',
    schemaRegenerateFailed: 'Échec de la génération du schéma',

    // Statut d\'initialisation du Wiki
    wikiInitStatusReady: 'Wiki initialisé',
    wikiInitStatusNotReady: 'Wiki non initialisé — création automatique lors du premier ingest',

    // Wiki Output Language
    wikiLanguageName: 'Langue de sortie du wiki',
    wikiLanguageDesc: "Toutes les pages wiki, l'index, le journal et les réponses de requête utilisent cette langue",
    customWikiLanguageOption: 'Personnalisé...',
    customWikiLanguageHint: 'Saisissez un nom de langue (p. ex. italien, arabe). Il sera transmis au LLM comme directive de langue de sortie.',
    customWikiLanguagePlaceholder: 'p. ex. Italien',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },
    logLabels: {
      en: { createdPages: 'Created pages', updatedPages: 'Updated pages', contradictionsFound: 'Contradictions found' },
      zh: { createdPages: '创建页面', updatedPages: '更新页面', contradictionsFound: '发现矛盾' },
      ja: { createdPages: '作成ページ', updatedPages: '更新ページ', contradictionsFound: '矛盾を発見' },
      ko: { createdPages: '생성 페이지', updatedPages: '업데이트 페이지', contradictionsFound: '모순 발견' },
      de: { createdPages: 'Erstellte Seiten', updatedPages: 'Aktualisierte Seiten', contradictionsFound: 'Widersprüche gefunden' },
      fr: { createdPages: 'Pages créées', updatedPages: 'Pages mises à jour', contradictionsFound: 'Contradictions trouvées' },
      es: { createdPages: 'Páginas creadas', updatedPages: 'Páginas actualizadas', contradictionsFound: 'Contradicciones encontradas' },
      pt: { createdPages: 'Páginas criadas', updatedPages: 'Páginas atualizadas', contradictionsFound: 'Contradições encontradas' },
    },

    // Extraction Settings
    extractionSectionTitle: 'Extraction',
    extractionGranularityName: 'Granularité de l\'extraction',
    extractionGranularityDesc: 'Contrôle les extractions par fichier source. Plus élevé = plus de pages/tokens API.\nFine: analyse approfondie. Standard: notes quotidiennes. Grossière: vue d\'ensemble rapide. Minimale: traitement 100+ fichiers. Personnalisée: limites propres (max 500).\nConseil: Utilisez Minimale/Grossière pour les dossiers avec nombreux fichiers pour gagner du temps et réduire les coûts.',
    extractionGranularityFine: 'Fine — analyse approfondie (≤100 éléments)',
    extractionGranularityStandard: 'Standard — notes quotidiennes (≤50 éléments)',
    extractionGranularityCoarse: 'Grossière — aperçu rapide (≤10 éléments)',
    extractionGranularityMinimal: 'Minimale — traitement par lot 100+ fichiers (≤5 éléments)',
    extractionGranularityCustom: 'Personnalisée — Définir vos propres limites (1~500)',
    customEntityLimitName: 'Limite personnalisée d\'entités',
    customEntityLimitDesc: 'Nombre maximum d\'entités à extraire par fichier source (1-500)',
    customConceptLimitName: 'Limite personnalisée de concepts',
    customConceptLimitDesc: 'Nombre maximum de concepts à extraire par fichier source (1-500)',

    // Issue #85 v2 : Vocabulaire des tags (saisie par chip, intégré à la configuration Wiki)
    tagVocabularyInlineDesc: 'Vocabulaire contrôlé pour les tags frontmatter entity et concept. Les tags imbriqués Obsidian avec « / » sont conservés.',
    tagVocabularyModeName: 'Configuration du vocabulaire des tags',
    tagVocabularyModeDescDefault: 'Par défaut utilise les tags intégrés : {}. Basculez sur « Personnalisé » pour définir votre propre vocabulaire.',
    tagVocabularyModeDescCustom: 'Personnalisé : définissez ci-dessous vos propres tags entity et concept via la saisie par chip — Entrée ou virgule pour ajouter, × pour retirer.',
    tagVocabularyModeDefault: 'Par défaut (sous-types intégrés)',
    tagVocabularyModeCustom: 'Personnalisé (défini par l\'utilisateur)',
    customEntityTagsName: 'Tags d\'entité personnalisés',
    customEntityTagsDesc: 'Entrée ou virgule pour ajouter un chip, × pour retirer. Les tags imbriqués « / » sont conservés.',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'Tags de concept personnalisés',
    customConceptTagsDesc: 'Entrée ou virgule pour ajouter un chip, × pour retirer. Les tags imbriqués « / » sont conservés.',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: 'Tag en double ignoré',

    // Ingestion Acceleration
    accelerationSectionTitle: 'Accélération de l\'import',
    pageGenerationConcurrencyName: 'Parallélisme LLM',
    pageGenerationConcurrencyDesc: 'Nombre d\'appels LLM en parallèle pendant l\'ingest et les opérations de lint. Des valeurs plus élevées accélèrent le traitement mais augmentent les coûts API et peuvent déclencher des limites de débit.',
    concurrencyValueSingular: 'Concurrence actuelle : {} (séquentiel — le plus sûr)',
    concurrencyValuePlural: 'Concurrence actuelle : {} (parallèle)',
    batchDelayName: 'Délai entre lots (ms)',
    batchDelayDesc: 'Délai entre lots parallèles pour éviter la limitation de débit de l\'API (100-2000ms). Actuel : {}ms. Augmentez si vous voyez des erreurs 429.',

    // Auto Maintenance
    autoMaintainSection: 'Maintenance automatique',
    autoMaintainBetaBadge: 'BÊTA — Fonctionnalité expérimentale. Peut présenter des problèmes. Recommandé uniquement pour les utilisateurs avancés.',
    autoWatchName: 'Surveiller des dossiers',
    autoWatchDesc: "Détecter automatiquement les nouveaux fichiers .md ou les modifications dans les dossiers surveillés et notifier ou importer automatiquement",
    watchedFoldersName: 'Dossiers surveillés',
    watchedFoldersDesc: "Dossiers à surveiller pour les nouveaux contenus. Cliquez sur « Ajouter un dossier » pour sélectionner depuis votre coffre.",
    addWatchedFolderButton: 'Ajouter un dossier',
    removeWatchedFolderButton: 'Retirer',
    webClipperPresetName: 'Surveiller les captures (Web Clipper)',
    webClipperPresetDesc: "Ajouter le dossier Clippings/ utilisé par Obsidian Web Clipper à la liste de surveillance. Vos captures web seront importées automatiquement dans le wiki.",
    noWatchedFoldersHint: "Aucun dossier configuré. Ajoutez un dossier ou activez le préréglage Clippings.",
    autoWatchModeName: 'Mode de surveillance',
    autoWatchModeDesc: '"Notifier seulement" affiche une invite. "Import automatique" traite silencieusement.',
    watchModeNotify: 'Notifier seulement',
    watchModeAuto: 'Import automatique',
    autoWatchDebounceName: "Délai d'anti-rebond (secondes)",
    autoWatchDebounceDesc: "Temps d'attente avant de déclencher l'import après une modification de fichier (1-60 secondes)",
    periodicLintName: 'Vérification périodique',
    periodicLintDesc: "Exécuter une vérification LLM planifiée, uniquement lorsque les fichiers sources ont changé depuis la dernière vérification",
    periodicLintOff: 'Désactivé',
    periodicLintDaily: 'Quotidien',
    periodicLintWeekly: 'Hebdomadaire',
    periodicLintMonthly: 'Mensuel',
    autoSmartFixName: 'Correction intelligente automatique',
    autoSmartFixDesc: 'Lors de l\'exécution du lint, applique automatiquement toutes les corrections (Smart Fix All) sans afficher le modal de rapport. Le résumé des corrections s\'affiche toujours à la fin.',
    autoSmartFixNotice: 'Correction intelligente automatique : application de toutes les corrections...',

    autoIngestLevelName: "Notification d'ingestion automatique",
    autoIngestLevelDesc: 'Comment notifier lorsque l\'ingestion automatique se termine. "Avis" (transitoire) est non bloquant. "Modal" ouvre le rapport complet. Désactivé lorsque le mode Watch est "Avis uniquement".',
    autoIngestLevelNotice: 'Avis (non bloquant)',
    autoIngestLevelModal: 'Modal (rapport complet)',
    startupCheckName: 'Exécuter les corrections rapides au démarrage',
    startupCheckDesc: "Corrige automatiquement les problèmes de format de bas niveau (champ sources, wikilinks doublement imbriqués) au chargement du plugin. Vérifie la structure du dossier Wiki. Activé par défaut.",
    suggestSchemaCommand: 'Suggérer des mises à jour du schéma',
    autoMaintainCostWarning: "⚠️ Avertissement sur les coûts : Les fonctionnalités de maintenance automatique consomment des tokens API. L'« Import automatique » déclenche des appels LLM à chaque modification de fichier source. La « Vérification périodique » exécute des contrôles de santé LLM selon un planning (uniquement lorsque des modifications de source sont détectées). Configurez avec soin pour éviter des frais imprévus.",

    // Notices
    startupCheckSummary: "Le wiki comporte {pages} pages ({entities} entités, {concepts} concepts, {sources} sources)",
    watcherActiveNotice: 'Wiki : surveillance de fichiers active — dossiers surveillés en cours de suivi',
    watchIngestNotice: 'Wiki : {count} fichier(s) modifié(s) dans sources/. Exécutez « Importer les sources » pour traiter.',
    autoIngestRunning: "Import automatique de {count} fichier(s) modifié(s) en cours...",
    autoIngestComplete: "Import automatique terminé : {success} réussi(s), {fail} échoué(s)",
    scheduledLintRunning: 'Exécution de la vérification périodique du wiki...',
    wikiLintStats: "Vérification wiki : {pages} pages ({entities} entités, {concepts} concepts, {sources} sources)",
    wikiHealthStats: "Santé du wiki : {pages} pages ({entities} entités, {concepts} concepts, {sources} sources){indexStatus}",

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Corrections rapides Wiki terminées',
    startupCheckStructureLabel: 'Structure Wiki',
    startupCheckStructureOk: 'complète',
    startupCheckStructureMissing: 'incomplète — sera créée automatiquement au premier ingest',
    startupCheckSourcesLabel: 'Sources normalisés',
    startupCheckSourcesClean: 'déjà propre',
    startupCheckSourcesCleaned: '{files} fichier(s), {entries} entrée(s) nettoyée(s)',
    startupCheckIncompleteClean: 'pages incomplètes : aucune',
    startupCheckIncompleteArchived: 'pages incomplètes : {count} archivée(s) (récupérable depuis .trash)',
    startupCheckDisableHint: 'Pour désactiver : Paramètres → Maintenance automatique → Exécuter les corrections rapides au démarrage',
    lintWikiStart: 'Démarrage de la vérification du wiki...',
    lintWikiComplete: 'Vérification du wiki terminée',
    lintWikiFailed: 'Échec de la vérification du wiki',
    analyzingSchema: "Analyse du wiki et génération des suggestions de schéma...",
    schemaSuggestionGenerated: 'Suggestions de schéma générées, consultez wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'Aucune mise à jour du schéma nécessaire.',
    schemaSuggestionFailed: 'Échec de la suggestion de schéma',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Aperçu de mise à jour du schéma',
    schemaDiffSummary: '+{add} / -{del} lignes',
    schemaDiffRegenerateLabel: 'Affiner la suggestion (optionnel) :',
    schemaDiffRegenerateBtn: 'Régénérer',
    schemaDiffOpenFileBtn: 'Ouvrir le fichier',
    schemaDiffApplyBtn: 'Appliquer',
    schemaDiffApplied: 'Schéma mis à jour. Sauvegarde : {path}',
    schemaDiffEmptyTitle: 'LLM ne recommande aucune modification',
    schemaDiffFailed: 'Échec de l\'application du schéma : {reason}',
    schemaDiffRestoreHint: 'Sauvegarde enregistrée dans {path}. Pour restaurer, renommez ce fichier en "wiki/schema/config.md" dans l\'explorateur de fichiers. Les 3 sauvegardes les plus récentes sont conservées.',
    schemaRegenerateNoBody: 'Régénération réussie mais le LLM n\'a pas renvoyé de nouveau schéma.',
    schemaNotFoundNotice: "Fichier de schéma introuvable. Activez le schéma pour le créer.",
    selectFolderNoMdFiles: 'Aucun fichier Markdown dans le dossier : {path}',
    batchIngestSkipNotice: '{skipped}/{total} fichiers déjà importés ignorés. Import de {new} nouveau(x) fichier(s)...',
    batchIngestAllIngested: 'Tous les {total} fichiers de ce dossier ont déjà été importés.',
    batchIngestStarting: "Import de {count} fichier(s) depuis « {folder} » — cela peut prendre plusieurs minutes. Un rapport apparaîtra une fois terminé.",
    batchIngestComplete: "Import par lot terminé : {success}/{total} réussi(s), {fail} échoué(s)",
    batchIngestFailedFiles: 'Fichiers ayant échoué :',
    historyTruncated: 'Historique tronqué aux {max} derniers tours',
    historyCleared: 'Historique effacé',

    // User Feedback Loop
    reviewedPagePreserved: 'Préservation du contenu révisé par l\'utilisateur pour : {}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: 'Enregistrer dans le wiki ?',
    querySuggestSaveDesc: 'Cette conversation contient des connaissances utiles. Voulez-vous les enregistrer dans votre wiki ?',
    querySuggestSaveYes: 'Enregistrer',
    querySuggestSaveNo: 'Ignorer',

    // Ingestion Report
    ingestReportElapsedTime: 'Temps écoulé',
    ingestReportSkippedFiles: 'Ignorés (déjà importés)',
    ingestReportRejectedFiles: 'Ignorés',
    rejectionReasonEmpty: 'vide',
    rejectionReasonType: 'type non pris en charge',
    rejectionReasonDuplicate: 'contenu en double',
    ingestReportFailedGuidance: "Ces éléments n'ont pas pu être créés automatiquement. Vous pouvez créer manuellement les pages correspondantes, ou réduire la granularité d'extraction et réimporter le fichier source.",
    ingestReportCollisions: 'Collisions cross-type (fusionnées comme alias)',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: 'Importer une source unique',
    cmdIngestFolder: 'Importer depuis un dossier',
    cmdIngestMultipleFiles: 'Importer plusieurs fichiers',
    cmdQueryWiki: 'Interroger le wiki',
    cmdLintWiki: 'Vérifier le wiki',
    cmdRegenerateIndex: 'Régénérer l\'index',
    cmdSuggestSchema: 'Suggérer des mises à jour du schéma',
    cmdCancelIngestion: "Annuler l'ingestion en cours",
    cmdIngestActiveFile: 'Ingérer le fichier actif',
    cmdViewHistory: 'Voir l\'historique d\'ingestion',
    noActiveFile: 'Aucun fichier ouvert',
    mdOnlyFile: 'Seuls les fichiers Markdown peuvent être ingérés',

    // Ingestion status bar
    ingestionStatusBar: 'Ingestion en cours... cliquer pour annuler',
    lintStatusBar: 'Vérification en cours... cliquer pour annuler',
    ingestStatusAnalyzing: 'Ingestion… (cliquer pour annuler)',
    lintStatusReading: 'Vérification… (cliquer pour annuler)',
    lintStatusDuplicates: 'Vérification… (cliquer pour annuler)',
    lintStatusScanningLinks: 'Vérification… (cliquer pour annuler)',
    lintStatusAnalyzing: 'Vérification… (cliquer pour annuler)',
    ingestionCancelling: 'Annulation — arrêt après le lot en cours',
    ingestionCancelled: 'Ingestion annulée',
    crossTypeCollisionNotice: '{count} éléments fusionnés comme alias cross-type (doublons entité ↔ concept évités)',

    // Lint Report
    lintReportTitle: 'Rapport de vérification du wiki',
    lintReportSummary: "Aperçu de l'état du wiki : {total} pages au total, {aliasesMissing} pages sans alias, {duplicates} pages dupliquées, {deadLinks} liens cassés ({deadLinkFromDup} impliquent des doublons), {orphans} pages orphelines ({orphanFromDup} sont des doublons), {emptyPages} pages vides, {ungroundedQuotes} citations non fondées, {tagViolations} tags hors vocabulaire. Durée du lint : {elapsedSeconds}s",

    // Advanced LLM Settings (Issues #99 / #128)
    advancedSettingsModeName: 'Paramètres avancés',
    advancedSettingsModeDesc: 'Le mode par défaut suit les recommandations de votre fournisseur. Passez en mode Personnalisé uniquement si vous avez une raison spécifique de le faire (par exemple, un modèle particulier nécessite une température fixe, ou vous souhaitez supprimer la sortie de raisonnement).',
    advancedSettingsDefault: 'Par défaut (suivre le fournisseur)',
    advancedSettingsCustom: 'Personnalisé (remplacer le fournisseur)',
    disableThinkingName: 'Désactiver le raisonnement',
    disableThinkingDesc: 'Désactive l\'affichage de la chaîne de pensée/du raisonnement dans la réponse. Désactivé par défaut — le modèle décide lui-même d\'afficher ou non son raisonnement, ce qui donne généralement la meilleure réponse. Activez-le uniquement si votre fournisseur insère du texte de raisonnement brut dans la réponse et que vous souhaitez une réponse propre.',
    // Issue #137 : Notes de compatibilité (courtes ; pas de liste de fournisseurs)
    extractionTemperatureName: 'Température d\'extraction',
    extractionTemperatureDesc: 'Contrôle si le modèle est plutôt conservateur ou créatif lors de l\'écriture de pages entity/concept. Valeurs basses = plus déterministe et fidèle ; valeurs hautes = plus varié. La plupart des utilisateurs laissent ce champ vide.',
    chatTemperatureName: 'Température de requête',
    chatTemperatureDesc: 'Même concept que la température d\'extraction, mais n\'affecte que la façon dont Query Wiki répond aux questions. Valeurs basses = réponses plus littérales ; valeurs hautes = réponses plus conversationnelles. La plupart des utilisateurs laissent ce champ vide.',
    repetitionPenaltyName: 'Pénalité de répétition',
    repetitionPenaltyDesc: 'Empêche le modèle de répéter les mêmes mots ou phrases. Des valeurs plus élevées réduisent la répétition. Seuls certains fournisseurs de modèles locaux (Ollama, LM Studio, llama.cpp) acceptent ce paramètre ; les fournisseurs cloud l\'ignorent silencieusement. La plupart des utilisateurs laissent ce champ vide.',
    temperaturePlaceholder: 'laisser vide = valeur par défaut du fournisseur',
    lintDeadLinkSection: 'Liens cassés (détectés) [{count}]',
    lintEmptyPageSection: 'Pages vides (détectées) [{count}]',
    lintOrphanSection: 'Pages orphelines (détectées) [{count}]',
    lintContradictionSection: 'Contradictions (détectées)',
    lintDuplicateSection: 'Pages dupliquées (détectées)',
    lintNoIssuesFound: 'Aucun doublon, lien cassé, page vide, page orpheline ou citation non fondée détecté.',
    lintQuoteGroundingSection: 'Citations non fondées (détectées) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: « {quote} »',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (la page n\'existe pas){dupFlag}',
    lintDeadLinkMore: '- ... {count} liens cassés supplémentaires',
    lintEmptyPageItem: '- [[{page}]] — moins de 50 caractères de contenu substantiel',
    lintOrphanItem: '- [[{page}]] — aucune autre page wiki ne pointe vers ici{dupFlag}',
    lintPollutedSection: 'Pages polluées (détectées) [{count}]',
    lintPollutedItem: '- [[{page}]] → devrait être "{clean}"',
    lintSourcesNormalizedSection: 'Sources normalisées (auto-corrigées) [{files} fichiers / {entries} entrées]',
    lintSourcesNormalizedItem: "Nettoyé {entries} entrées de sources polluées dans {files} fichier(s) (chemins externes, extensions .md, pipes d'alias supprimés et déduplication).",
    lintDuplicateItem: '- [[{target}]] et [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ implique une page dupliquée)',
    lintOrphanIsDuplicate: ' (⚠️ page dupliquée)',
    lintHubLinkDensitySection: 'Problèmes de densité de liens sur les hubs (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} entrants, {relatedCount} liens associés, distinctivité {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ retirer',
    lintHubLinkDensityReview: '🔍 examiner',
    lintHubLinkDensityKeep: '✅ conserver',
    lintHubLinkDensitySummary: 'Résumé : {strip} page(s) recommandée(s) pour suppression, {review} page(s) recommandée(s) pour examen.',
    lintHubLinkDensityNoRelated: ' (aucune section ## Related trouvée)',
    lintContradictionOpen: 'Contradictions non résolues : {count}',
    lintContradictionAutoFixed: '({count} corrigé(s) automatiquement cette exécution)',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Détecté',
    lintContradictionStatusPendingFix: 'Correction en attente',
    lintLLMAnalysisHeading: '## Analyse LLM',

    // Lint Analysis Prompt
    lintAnalysisPrompt: "Vous êtes un assistant de maintenance wiki. Vérifiez la santé du wiki sur la base des informations suivantes.\n\nIndex wiki :\n{index}\n\nÉchantillon de contenu des pages wiki ({total} pages au total, {sample} pages affichées) :\n{contentSample}\n\nRésultats des vérifications programmatiques (déjà vérifiés, ne pas répéter) :\n{progReport}\n\nVérifiez les aspects suivants (ignorez les liens cassés/pages vides/pages orphelines déjà détectés par les vérifications programmatiques) :\n1. **Contradictions** — des pages différentes se contredisent-elles sur les mêmes faits\n2. **Obsolescence** — certaines affirmations sont-elles clairement dépassées\n3. **Manquants** — quels concepts importants n'ont pas de page dédiée\n4. **Structure** — la structure des pages est-elle raisonnable et les références croisées sont-elles adéquates\n\nFormat de sortie : utilisez Markdown, en commençant par « ## Analyse LLM ». Chaque constatation sur une ligne « - [problème spécifique] ». S'il n'y a pas de problèmes, écrivez « Aucun problème évident trouvé. »",
    lintAnalysisProgReportEmpty: 'Aucun problème détecté par les vérifications programmatiques.',

    // Lint Fix Progress
    lintFixProgress: 'Réparation {current}/{total} : [[{target}]]',
    lintFixDeadComplete: 'Réparation des liens cassés terminée. {fixed}/{total} éléments réparés.',
    lintFillProgress: 'Expansion {current}/{total} : {page}',
    lintFillComplete: 'Expansion des pages terminée. {filled}/{total} pages remplies.',
    lintDeleteCompleted: '{count} stubs vides supprimés',
    lintDeleteFailed: 'Échec de suppression de {failed}/{total} stubs vides (voir la console)',
    lintFillFailed: "Échec de l'expansion : {page} — {error}",
    lintLinkProgress: 'Lien {current}/{total} : {page}',
    lintLinkComplete: 'Liens des pages orphelines terminés. {linked} pages liées.',
    lintFixNoAction: "Aucune action entreprise (pas de client)",
    lintFixIndexUpdated: "L'index et le journal wiki ont été mis à jour.",
    lintPollutedFixed: 'Pages polluées corrigées : {fixed}/{total}. Index régénéré.',
    regenerateIndexCompleted: 'Index régénéré',
    operationFailed: 'Échec : ', 
    lintFixAllComplete: 'Toutes les réparations sont terminées. Consultez le journal pour les détails.',

    // Lint Report Modal
    lintModalActionsTitle: 'Suggestions de réparation (nécessite des tokens LLM) :',
    lintLogReference: 'Rapport complet enregistré dans log.md',
    lintModalFixDeadLinks: 'Réparer les liens cassés ({count})',
    lintModalExpandEmpty: 'Étendre les pages vides ({count})',
    lintModalDeleteEmpty: 'Supprimer les stubs vides ({count})',   
    lintModalLinkOrphans: 'Lier les pages orphelines ({count})',
    lintModalAnalyzeSchema: 'Analyser le schéma',
    lintModalMergeDuplicates: 'Fusionner les doublons ({count})',
    lintModalFixAll: 'Réparation intelligente de tout ({count} problèmes)',
    lintMergeProgress: 'Fusion {current}/{total} : {source} → {target}',
    lintMergeComplete: 'Fusion des doublons terminée. {merged}/{total} paires fusionnées.',

    // Ingest Report Modal
    ingestReportTitle: "Rapport d'import",
    ingestReportSourceFile: 'Fichier source',
    ingestReportCreated: 'Créées',
    ingestReportUpdated: 'Mises à jour',
    ingestReportContradictions: 'Contradictions trouvées',
    ingestReportFailedTitle: "Échec de l'import",
    ingestReportErrorDetail: "Détail de l'erreur",
    ingestReportClose: 'Fermer',
    ingestReportCreatedPages: 'Pages créées : {count}',
    ingestReportUpdatedPages: 'Pages mises à jour : {count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki Journal des opérations',
    logHeaderSubtitle: 'Chaque ingestion, exécution de lint et opération de maintenance est enregistrée ici automatiquement. Pour une meilleure visualisation, utilisez le panneau **Historique des opérations** :',
    logHeaderShortcut: "Cmd+P → \"Afficher l'historique des opérations\"",
    logHeaderSettingsShortcut: 'Ou via Paramètres → Maintenance automatique → Historique des opérations',
    ingestionCreatedPages: '{count} page(s) créée(s)',
    ingestionUpdatedPages: '{count} page(s) mise(s) à jour',
    ingestionNoticeHistoryHint: 'Voir l\'historique des opérations pour plus de détails',
    ingestReportEntitiesCount: '{count} entités',
    ingestReportConceptsCount: '{count} concepts',
    ingestReportContradictionsFound: 'Contradictions trouvées : {count}',
    ingestReportEntityType: 'Entité',
    ingestReportConceptType: 'Concept',
    timeMinutes: 'min',
    timeSeconds: 's',

    // Avertissements de limite de débit
    rateLimitDetected: "⚠️ Limite de débit détectée : {count} page(s) ont échoué avec des erreurs 429. Suggestions : (1) Réduire la concurrence à {suggestedConcurrency} ou 1 (séquentiel), (2) Augmenter le délai entre lots à {suggestedDelay}ms, (3) Passer à un fournisseur avec des limites de débit plus élevées.",
    rateLimitDetectedShort: "⚠️ Limite de débit atteinte — envisagez de réduire la concurrence ou d'augmenter le délai entre lots dans Paramètres → Accélération d'import.",

    sourceRejectedEmpty: '⏭️ « {filename} » n\'a aucun contenu à ingérer — ignoré. Les notes vides ou ne contenant que des métadonnées ne créent pas de pages wiki.',
    sourceRejectedType: '⏭️ « {filename} » n\'est pas un type de fichier pris en charge — ignoré. Seules les notes texte (.md, .txt, etc.) peuvent être ingérées.',
    sourceRejectedDuplicate: '⏭️ « {filename} » ignoré — son contenu est déjà dans le wiki.',
    ingestRejectedSummary: '{count} fichier(s) ignoré(s) (vide, doublon ou type non pris en charge).',
    reingestConfirmTitle: 'Ré-ingérer ce fichier ?',
    reingestConfirmBody: 'Le contenu de « {filename} » est déjà dans le wiki. Le ré-ingérer quand même ?',
    reingestConfirmYes: 'Ré-ingérer',
    reingestConfirmNo: 'Ignorer',
    longSourceNotice: '📄 "{filename}" contient {lines} lignes ({size}). Les textes longs nécessitent une extraction itérative par lots — le LLM lit le document complet en plusieurs passes. Cela peut prendre plusieurs minutes. Veuillez patienter.',
    longSourceNoticeShort: '📄 Fichier volumineux détecté ({lines} lignes). Ingestion peut prendre du temps.',

    // Panneau Historique d'ingestion (#122) — textes UI
    historyButton: 'Historique des opérations',
    historyButtonDesc: 'Afficher les ingestions récentes, les rapports Lint et autres modifications du Wiki',
    historyButtonOpen: 'Voir l\'historique',
    historyModalTitle: 'Historique des opérations',
    historyModalSubtitle: 'Modifications récentes de votre LLM-Wiki',
    historyEmpty: 'Aucune opération enregistrée. Ingérez une note ou exécutez Lint pour remplir cette liste.',
    historyReadError: 'Impossible de lire le journal d\'opérations : {error}',
    historyEntryKindIngest: 'Ingestion',
    historyEntryKindMaintenance: 'Maintenance',
    historyEntryKindFix: 'Correction',
    historyEntryKindOther: 'Autre',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Source : {source}',
    historyEntrySourceUnknown: 'Ingestion sans titre',
    historyEntryCreatedLabel: 'Créées',
    historyEntryUpdatedLabel: 'Mises à jour',
    historyEntryCreatedCount: '{count} créées',
    historyEntryUpdatedCount: '{count} mises à jour',
    historyEntryNoChanges: 'Aucun changement de page',
    historyEntryContradictions: '⚠️ {count} contradiction(s)',
    historyEntrySectionCreated: 'Pages créées',
    historyEntrySectionUpdated: 'Pages mises à jour',
    historyEntrySectionContradictions: 'Contradictions',
    historyEntrySectionDetails: 'Détails',
    historyEntryOpenPage: 'Ouvrir',
    historyEntryDetailsNoContradictions: 'Aucune contradiction trouvée',
    historySearchPlaceholder: '🔍 Rechercher par titre de source ou chemin de page…',
    historyFilterAll: 'Toutes',
    historyFilterIngest: 'Ingestions seules',
    historyFilterMaintenance: 'Maintenance seule',
    historyFilterFix: 'Corrections seules',
    historyFilterContradictions: '⚠️ Avec contradictions',
    historyRefreshButton: '⟳ Actualiser',
    historyExpandDay: 'Cliquer pour déplier',
    historyCollapseDay: 'Cliquer pour replier',
    historyShowMore: 'Afficher les {count} entrées plus anciennes',
    historyNoMatch: 'Aucune opération ne correspond à votre recherche/filtre.',
    historyCloseButton: 'Fermer',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'Résultats du rapport',
    historyKpiPages: 'Pages',
    historyKpiDeadLinks: 'Liens morts',
    historyKpiOrphans: 'Orphelins',
    historyKpiEmpty: 'Vides',
    historyKpiDuplicates: 'Doublons',
    historyKpiTagViolations: 'Tags',
    historyKpiUnsourced: 'Sans source',
    historyKpiDuration: 'Durée Lint',
    historyKpiDurationSec: '{seconds}s',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'Liens morts ({count})',
    historySectionTagViolations: 'Tags ({count})',
    historySectionOrphans: 'Pages orphelines ({count})',
    historySectionEmptyPages: 'Pages vides ({count})',
    historySectionLlmAnalysis: 'Analyse LLM ({count})',
    historyDeadLinkSource: 'Source',
    historyDeadLinkTarget: 'Manquant',
    historyOpenInLog: 'Ouvrir dans log.md',
    historyShowMoreItems: 'Afficher {count} de plus',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ stable',
    historyChipContradiction: 'Contradiction',
    historyChipOutdated: 'Obsolète',
    historyChipMissing: 'Manquant',
    historyChipStructure: 'Structure',
    historySeverityHigh: 'Haute',
    historySeverityMedium: 'Moyenne',
    historySeverityLow: 'Basse',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Votre Wiki contient {dead} lien(s) mort(s), {orphans} page(s) orpheline(s) et {tags} problème(s) de tag. Dernière Lint : {duration}.',
    historyGlobalInsightClean: 'Votre Wiki est sain — aucun lien mort, page orpheline ou problème de tag détecté.',
    historyGlobalInsightNoData: 'Aucun rapport de maintenance — exécutez Lint.',
    historyModalHeaderTitle: 'Historique des opérations',
    historyModalSubtitleWithCount: 'Modifications récentes de votre LLM-Wiki · {count} entrées',
    historyTimeRangeAll: 'Toute la période',
    historyTimeRange1d: 'Dernier jour',
    historyTimeRange3d: '3 derniers jours',
    historyTimeRange1w: 'Semaine dernière',
    historyTimeRange1m: 'Mois dernier',
    historyIngestTotal: 'Pages totales',
    historyIngestByType: 'Par type',
    historyIngestSource: 'Fichier source',
    historyIngestNoTimestamp: "Pas d'horodatage",
    historyIngestFirstTime: 'Première ingestion',
    historyIngestLatestTime: 'Dernière ingestion',
    historyTimeRangeCustom: 'Période personnalisée',
    historyCustomRangeFrom: 'Du',
    historyCustomRangeTo: 'Au',
    historyCustomRangeApply: 'Appliquer',
    historyCustomRangeClear: 'Effacer',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    // Welcome content (5 sections + 14 keys) is LLM-dynamically translated at write time per D8.
    // Only plugin UI surfaces are localized; no hardcoded 10-language template.
    welcomeNoteTierANotice: 'Karpathy Wiki : le vault est vide. Créez votre première note source et lancez Ingest pour commencer.',
    welcomeNoteTierBNotice: 'Karpathy Wiki : une note Welcome a été créée. Ouvrez-la pour déclarer vos domaines et choisir 2-3 notes sources pour amorcer le graphe de liens.',
    welcomeNoteRecreateCommand: 'Recréer la note Welcome Wiki',
    welcomeNoteRecreateCommandTooltip: 'Recrée la note Welcome dans <wikiFolder>/Welcome.md avec les domaines actuels et le test de configuration LLM. Le fichier existant est écrasé.',
    welcomeNoteSettingsToggle: 'Créer une note Welcome Wiki au premier lancement',
    welcomeNoteSettingsToggleDesc: 'Au premier démarrage (lorsque le dossier wiki est vide), crée une note d\'introduction d\'une page dans <wikiFolder>/Welcome.md. Elle explique ce qu\'est LLM-Wiki, vous invite à déclarer votre domaine d\'intérêt, et vous guide dans l\'ingestion de vos 2-3 premières notes sources. La note est écrite en anglais par défaut, ou dans votre langue wiki si le LLM est configuré. Désactivez si vous connaissez déjà le plugin et ne souhaitez pas de note d\'introduction.',
    welcomeNoteRunConfigTest: 'Note Welcome écrite en anglais. Ouvre Paramètres → LLM Provider → Test Connection pour la localiser à la prochaine recréation.',
    welcomeNoteRecreated: 'Note Welcome Wiki recréée à {path}',
    welcomeNoteNotRecreated: 'La note Welcome n\'a pas été recréée. Vérifie la configuration LLM.',
    welcomeNoteGenerating: 'Note Welcome Wiki : génération en arrière-plan — une notification apparaîtra à la fin.',
    welcomeNoteGenerationFailed: 'Échec de la génération de la note Welcome Wiki : {error}',
    startupCheckWelcomePending: 'Note Welcome : génération en arrière-plan (une notification apparaîtra à la fin).',
    welcomeNoteFileName: 'Bienvenue sur Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Note Welcome créée à {path}',
    // v1.23.0 Phase 5.1.5 : bouton « Tout annuler » de la modale de sélection multiple.
    // Annule tous les jobs en attente et en cours d'exécution dans la file.
    // Les jobs terminés et échoués restent affichés.
    cancelAllQueueJobs: 'Tout annuler',
    // v1.23.0 Phase 5.1.5: modale de sélection multiple (cmdIngestMultipleFiles).
    // Titre, indice, placeholder de recherche, boutons, étiquettes d'état,
    // placeholder de file vide.
    multiFileModalTitle: 'Importer plusieurs fichiers',
    multiFileModalHint: 'Sélectionne les notes sources à importer. Le panneau droit affiche la file d\'attente en direct et la progression.',
    multiFileSearchPlaceholder: 'Filtrer les fichiers par chemin…',
    multiFileAddToQueue: 'Ajouter à la file',
    multiFileSelectAll: 'Tout sélectionner',
    multiFileFileCount: '{count} fichier(s)',
    multiFileNoFilesAvailable: 'Aucun fichier disponible à importer.',
    multiFileNoFilesMatch: 'Aucun fichier ne correspond à "{q}".',
    multiFileQueueEmpty: 'File vide. Coche des fichiers à gauche pour les ajouter.',
    multiFileStatusPending: 'En attente',
    multiFileStatusRunning: 'En cours',
    multiFileStatusCompleted: 'Terminé',
    multiFileStatusFailed: 'Échoué',
    multiFileCancelAria: 'Annuler ce fichier',
    startupCheckNoticeLevelName: 'Afficher le résultat des correctifs rapides',
    startupCheckNoticeLevelDesc: 'Les QuickFixes s\'exécutent toujours au démarrage du plugin (note Welcome, structure des dossiers, normalisation des sources, pages incomplètes, en-tête du journal). Choisis d\'afficher ou non la notice récapitulative après le démarrage. Le mode silencieux n\'écrit que dans la console développeur et le panneau Historique des opérations.',
    startupCheckNoticeVisible: 'Visible (afficher la notice)',
    startupCheckNoticeSilent: 'Silencieux (aucune notice)',
} as const;