export const IT_TEXTS = {
    // Informazioni Plugin
    pluginTitle: 'Impostazioni Karpathy LLM Wiki',
    pluginIntro: "Questo plugin implementa il concetto di {{link}} per Obsidian. Legge le tue note, usa l'IA per estrarre entità e concetti, e costruisce una Wiki strutturata e interconnessa nel tuo vault.",
    karpathyLinkText: 'LLM Wiki di Andrej Karpathy',

    // Sezione Funzionalità
    featuresTitle: 'Come funziona',
    workflow1Title: '1. Acquisisci',
    workflow1Desc: "Seleziona una nota — l'IA estrae entità, concetti e relazioni in pagine Wiki.",
    workflow2Title: '2. Interroga',
    workflow2Desc: 'Conversa con la tua Wiki — le risposte si basano sulla conoscenza acquisita.',
    workflow3Title: '3. Mantieni',
    workflow3Desc: 'Indice auto-generato, collegamenti incrociati e controlli Lint mantengono la Wiki in salute.',

    // Selettore Lingua
    languageTitle: 'Lingua interfaccia',
    languageDesc: 'Seleziona la lingua preferita per il pannello delle impostazioni. Riavvia il plugin per applicare le modifiche di lingua alla palette dei comandi.',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',

    // Stato
    statusTitle: 'Stato client LLM',
    llmWikiStatusSection: 'Stato LLM-Wiki',
    statusInitialized: 'Inizializzato',
    statusNotInitialized: 'Non inizializzato',
    statusReady: 'LLM pronto',
    statusNotReady: 'LLM non configurato — completa la configurazione e supera il test di connessione',
    currentProvider: 'Provider attuale',

    // Configurazione Provider
    providerSection: 'Configurazione LLM',
    providerName: 'Provider LLM',
    providerDesc: "Seleziona un provider predefinito o un servizio personalizzato compatibile con OpenAI. Per Coding Plan o pacchetti simili, scegli Custom OpenAI/Anthropic e inserisci manualmente l'URL di base e la chiave API del provider",

    // Chiave API
    apiKeyName: 'Chiave API',
    apiKeyDesc: 'Inserisci la chiave API del tuo provider',
    apiKeyPlaceholder: 'Inserisci la chiave API',

    // URL di base
    baseUrlName: 'URL di base API',
    baseUrlDescCustom: 'Obbligatorio: endpoint personalizzato compatibile con OpenAI',
    baseUrlDescOverride: "Facoltativo: sovrascrivi l'URL di base predefinito",

    // Suggerimento Ollama
    ollamaHint: 'Ollama gira in locale, nessuna chiave API richiesta',
    // Suggerimento LM Studio
    lmstudioHint: 'LM Studio gira in locale, la chiave API è facoltativa',

    // Limite esecuzione LLM
    maxTokensPerCallName: 'Max token di output per chiamata',
    maxTokensPerCallDesc: 'Limita quanti token il modello può generare in una singola risposta. Riduci se usi un modello locale con finestra di contesto piccola e vedi errori. Per i modelli cloud, mantieni il valore predefinito (0 = nessun limite).',

    // Issue #111: maiuscole/minuscole slug
    slugCaseName: 'Maiuscole/minuscole nome file',
    slugCaseDesc: 'Controlla se i nomi dei file wiki generati vengono convertiti in minuscolo. "Preserva" è consigliato per le lingue in cui il minuscolo cambia il significato (es. i sostantivi tedeschi).',
    slugCaseLower: 'Minuscolo (predefinito)',
    slugCasePreserve: 'Preserva maiuscole/minuscole',

    // Selezione Modello
    modelSection: 'Selezione modello',
    fetchModelsName: 'Recupera modelli disponibili',
    fetchModelsDesc: 'Ottieni la lista più recente di modelli dalla API del provider',
    fetchModelsButton: 'Recupera modelli',
    fetchingModels: 'Recupero in corso...',
    fetchSuccess: 'Riuscito! {} modelli disponibili',
    fetchFailed: 'Operazione fallita o lista vuota, inserisci manualmente il nome del modello',
    fetchNotSupported: 'Il provider non supporta la query della lista modelli',
    fetchErrorAuth: 'Autenticazione fallita (HTTP 401/403). Verifica la tua chiave API, oppure inserisci un ID modello qui sotto e clicca Testa connessione per validare.',
    fetchErrorEndpoint: "Endpoint non trovato (HTTP 404). Verifica l'URL di base, oppure inserisci un ID modello e clicca Testa connessione per validare.",
    fetchErrorServer: 'Errore del server del provider (HTTP 5xx). Riprova più tardi, oppure inserisci un ID modello e clicca Testa connessione per validare.',
    fetchErrorEmpty: "Il provider non ha un endpoint per la lista modelli. Inserisci un ID modello qui sotto e clicca Testa connessione per validare.",
    fetchErrorNetwork: "Richiesta di rete fallita. Controlla la connessione internet, l'URL di base o le impostazioni del proxy. Puoi anche inserire un ID modello qui sotto e cliccare Testa connessione per validare.",

    selectModelName: 'Seleziona modello',
    selectModelDesc: 'Scegli tra {} modelli disponibili',
    customInputOption: 'Inserimento personalizzato...',
    customInputHint: 'Per usare altri modelli, seleziona "Inserimento personalizzato..."',

    modelName: 'Nome modello',
    modelDescCustom: 'Uso di modello personalizzato (clicca il pulsante sopra per ri-recuperare la lista)',
    modelDescFetchFailed: "Recupero della lista modelli fallito. Verifica la tua chiave API e l'URL dell'endpoint, oppure inserisci un ID modello qui sotto e clicca Testa connessione per validare.",
    modelInputPlaceholder: 'Inserisci ID modello, poi Testa connessione',

    switchToDropdown: 'Passa alla selezione a tendina',
    useDropdownButton: 'Usa menu a tendina',

    // Test e Salvataggio
    testConnectionName: 'Testa connessione',
    testConnectionDesc: 'Verifica che la configurazione possa chiamare con successo la API LLM',
    testButton: 'Testa connessione',
    testing: 'Test in corso...',

    saveSettingsName: 'Salva impostazioni',
    saveSettingsDesc: 'Salva la configurazione attuale',
    saveButton: 'Salva impostazioni',
    savedNotice: 'Impostazioni salvate!',

    // v1.24.0 (Bug C 3.4 / plan C): notifica di migrazione graduale
    queryHistoryMigrationNotice: 'La cronologia di Query Wiki contiene link da una cartella wiki precedente. Le nuove query usano automaticamente la cartella più recente. Per aggiornare tutti i messaggi memorizzati, apri il pannello Query Wiki e fai clic sul pulsante "Cancella cronologia" al suo interno.',

    // Test Connessione
    testConnectionSuccessful: 'Connessione riuscita',
    testConnectionFailed: 'Connessione fallita',
    testConnectionProvider: 'Provider: ',
    errorUnknown: 'Errore sconosciuto',

    // Issue #137: avvisi di fallback LLM (mostrati quando avviene un
    // fallback del dialetto di ragionamento o uno strip di parametri durante una richiesta).
    fallbackThinkingDialect: 'Controllo ragionamento: passato al dialetto "{dialect}" (questo provider usa un formato di controllo del ragionamento diverso). L\'output rimane invariato.',
    fallbackThinkingNone: 'Controllo del ragionamento completamente disabilitato per questo provider. Il contenuto del ragionamento potrebbe comunque apparire; in tal caso, prova un modello diverso.',
    fallbackParamStripped: 'Parametro "{field}" non supportato da questo provider. Rimosso dalla richiesta; il comportamento potrebbe differire dalla configurazione.',

    // Stato Inizializzazione Wiki
    wikiInitStatusReady: 'Wiki inizializzata',
    wikiInitStatusNotReady: 'Wiki non inizializzata — verrà creata automaticamente alla prima acquisizione',

    // Cartella Wiki
    wikiSection: 'Configurazione Wiki',
    wikiFolderName: 'Cartella Wiki',
    // v1.24.0: indica che è necessario riavviare Obsidian dopo la modifica
    // (le cache del motore e i pannelli aperti di Query Wiki devono ricollegarsi).
    wikiFolderDesc: 'Posizione delle pagine Wiki generate. Riavvia Obsidian dopo la modifica — le cache del motore e i pannelli aperti di Query Wiki devono ricollegarsi.',
    wikiFolderPlaceholder: 'wiki',

    // Errori
    errorNoApiKey: 'Configura prima la chiave API',
    llmNotReady: 'LLM non configurato. Vai su Impostazioni → Karpathy LLM Wiki per configurare il tuo provider, recuperare i modelli disponibili e superare il test di connessione.',
    errorFetchFailed: 'Fallito: {}',

    // Impostazioni Query
    querySectionTitle: 'Configurazione query Wiki',
    // v1.24.0: rinominato da "Cronologia conversazione massima" a
    // "Turni di memoria della conversazione" per maggiore chiarezza.
    // 1 = ogni turno indipendente (nessuna memoria tra turni).
    // L'impostazione è un menu a discesa, non serve elencare i valori preimpostati.
    // v1.24.0: maxConversationHistoryHint era una chiave i18n inutilizzata;
    // il consiglio è stato integrato nella descrizione.
    maxConversationHistoryName: 'Turni di memoria della conversazione',
    maxConversationHistoryDesc: 'Quanti turni di conversazione passati il LLM vede come memoria. 1 = ogni turno indipendente (nessuna memoria tra turni); valori più alti permettono al modello di ricordare turni precedenti della sessione. Consigliato: 1 per Q&A occasionale, 10–50 per ricerca continuativa.',
    numberRangeValidation: 'Inserisci un numero tra 1 e 50',
    numberRangeClamped: 'Il valore supera il range (1-500), impostato automaticamente a {}',

    // UI Modale Query
    queryModalTitle: 'Query Wiki - Query conversazionale',
    queryModalPlaceholder: 'Inserisci una domanda...',
    queryModalSendButton: 'Invia',
    queryModalStopButton: 'Ferma',
    queryModalSaveButton: 'Salva nella Wiki',
    queryModalClearButton: 'Cancella cronologia',
    queryModalHistoryCount: 'Cronologia conversazione: {}/{} turni',
    queryModalStreaming: 'Streaming...',
    queryModalFallbackStreaming: 'Streaming non supportato, passato a non-streaming. Attendere...',
    queryPhaseSearching: "Analisi dell'indice Wiki, selezione delle pagine pertinenti...",
    queryPhaseFoundPages: 'Trovate {count} pagina/e: {pages}',
    queryPhaseLoadingPages: 'Caricamento del contenuto della pagina...',
    queryPhaseContextReady: 'Contesto pronto. Generazione della risposta...',
    queryPhaseGenerating: 'Generazione... (trascorsi {time}s)',
    queryPhaseNonStreaming: 'Modalità non-streaming, generazione della risposta... (trascorsi {time}s)',
    queryModalErrorPrefix: 'Errore: ',
    queryModalHint: 'Le query si basano sul contenuto della Wiki. Clicca "Salva nella Wiki" per estrarre le conversazioni preziose come pagine Wiki.',

    // v1.20.0: riepilogo collassabile del blocco di ragionamento in Query Wiki
    queryThinkingSummary: 'Processo di ragionamento',
    queryThinkingSteps: 'passaggi',

    // Messaggi di errore
    errorLLMClientNotInit: 'Client LLM non inizializzato. Salva le impostazioni.',
    errorIngestFailed: 'Acquisizione fallita: ',
    errorQueryFailed: 'Query fallita: ',
    fileWriteFailed: 'Impossibile creare o aggiornare il file: {path}',

    // Messaggi di successo
    ingestSuccess: 'Acquisizione riuscita: {} pagine create, {} pagine aggiornate',
    querySuccess: 'Query completata',
    lintSuccess: 'Lint della Wiki completato',
    lintReadingPages: 'Lettura di {count} pagine Wiki...',
    lintReadingPagesProgress: 'Lettura pagine Wiki: {current}/{total}...',
    lintScanningLinks: 'Scansione dei collegamenti interrotti...',
    lintScanningLinksProgress: 'Scansione collegamenti interrotti: {current}/{total}...',
    lintCheckingDuplicates: 'Controllo delle pagine duplicate...',
    lintCheckingDuplicatesProgress: 'Verifica duplicati: batch {current} ...',
    lintFixingPolluted: 'Correzione pagina inquinata {current}/{total}: {title} → {newTitle}',
    lintModalFixPolluted: '🧹 Correggi pagine inquinate ({count})',
    lintDuplicateCheckFailed: 'Rilevamento duplicati fallito — vedi la console per i dettagli',
    lintDuplicateCheckFailedDetail: 'Controllo duplicati fallito a {step}: {error}',
    lintMergeItemFailed: 'Unione fallita: {source} → {target} — {error}',
    lintAliasesMissing: 'Alias mancanti: {count} pagina/e senza alias',
    lintAliasesSection: 'Pagine senza alias [{count}]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: 'Completa alias ({count})',
    lintAliasesFilling: 'Generazione alias {current}/{total}: {page}',
    lintAliasesFilled: 'Completamento alias terminato. Compilate {filled}/{total} pagine.',
    lintAliasesFillFailed: 'Generazione alias fallita: {page} — {error}',
    // Issue #85 v7: notifiche di ri-tagging per violazione tag
    lintTagViolationFiring: 'Ri-tagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Ri-tagging fallito per {path}: {error}',
    lintTagViolationFixed: 'Ri-tagging completato. Corrette {fixed}/{total} pagina/e.',
    lintTagViolationFixedNone: "Ri-tagging completato. Nessuna pagina necessitava correzioni (l'LLM ha mantenuto i tag attuali).",
    lintTagViolationSection: 'Pagine con tag fuori vocabolario [{count}]',
    lintTagViolationItem: '- [[{path}]] — non validi: {tags}',
    lintTagViolationRetagBtn: '🏷️ Ri-tagga {count} pagina/e con LLM',
    lintFixItemFailed: 'Correzione fallita: [[{target}]] — {error}',
    lintLinkItemFailed: 'Collegamento fallito: {page} — {error}',
    lintRetrying: 'Nuovo tentativo ({attempt}/{max}) dopo errore...',
    lintAnalyzingLLM: "LLM sta analizzando la salute della Wiki...",
    saveToWikiSuccess: 'Conversazione salvata nella Wiki!',
    saveSummary: '{entities} entità, {concepts} concetti, {pages} pagine',
    aliasAdded: "Aggiunto alias '{alias}' alla pagina '{page}'",

    // Messaggi di stato
    ingestingSources: 'Acquisizione delle sorgenti...',
    queryingWiki: 'Interrogazione della Wiki...',
    lintingWiki: 'Lint della Wiki...',
    savingToWiki: 'Salvataggio della conversazione nella Wiki...',
    clearingHistory: 'Cancellazione della cronologia conversazione...',

    // Pulsanti
    ingestButton: 'Acquisisci',
    queryButton: 'Interroga',
    lintButton: 'Lint',
    cancelButton: 'Annulla',

    // Collegamenti
    karpathyGistLink: 'Gist della LLM Wiki di Karpathy',
    obsidianPluginAPI: 'Obsidian Plugin API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // Altro
    availableModelsLoading: 'Caricamento dei modelli disponibili...',
    noModelsAvailable: 'Nessun modello disponibile',

    // Suggerimento Lingua LLM
    llmLanguageHint: 'Rispondi in italiano.',

    // Configurazione Schema
    schemaSection: 'Configurazione Schema',
    enableSchemaName: 'Abilita Schema',
    enableSchemaDesc: 'Genera e inietta schema/config.md in tutti i prompt LLM per un output Wiki strutturato',
    viewSchemaButton: 'Visualizza / Modifica Schema',
    regenerateSchemaButton: 'Rigenera Schema predefinito',
    schemaRegeneratedNotice: 'Schema predefinito rigenerato.',
    schemaRegenerateFailed: 'Generazione dello Schema fallita',

    // Lingua di output Wiki
    wikiLanguageName: 'Lingua di output Wiki',
    wikiLanguageDesc: "Tutte le pagine wiki generate, l'indice, il log e le risposte alle query usano questa lingua",
    customWikiLanguageOption: 'Personalizzata...',
    customWikiLanguageHint: "Inserisci il nome di una lingua (es. Italiano, Arabo). Verrà passato all'LLM come direttiva di lingua di output.",
    customWikiLanguagePlaceholder: 'es. Italiano',

    // Etichette Indice e Log (per lingua)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },
    logLabels: {
      en: { createdPages: 'Created pages', updatedPages: 'Updated pages', contradictionsFound: 'Contradictions found' },
      zh: { createdPages: '创建页面', updatedPages: '更新页面', contradictionsFound: '发现矛盾' },
      ja: { createdPages: '作成ページ', updatedPages: '更新ページ', contradictionsFound: '矛盾を発見' },
      ko: { createdPages: '생성 페이지', updatedPages: '업데이트 페이지', contradictionsFound: '모순 발견' },
      de: { createdPages: 'Erstellte Seiten', updatedPages: 'Aktualisierte Seiten', contradictionsFound: 'Widersprüche gefunden' },
      fr: { createdPages: 'Pages créées', updatedPages: 'Pages mises à jour', contradictionsFound: 'Contradictions trouvées' },
      es: { createdPages: 'Páginas creadas', updatedPages: 'Páginas actualizadas', contradictionsFound: 'Contradicciones encontradas' },
      pt: { createdPages: 'Páginas criadas', updatedPages: 'Páginas atualizadas', contradictionsFound: 'Contradições encontradas' },
    },

    // Impostazioni Estrazione
    extractionSectionTitle: 'Estrazione',
    extractionGranularityName: 'Granularità estrazione',
    extractionGranularityDesc: 'Controlla le entità/concetti estratti per file sorgente. Più alto = più pagine, più token API.\nFine: analisi approfondita. Standard: note quotidiane. Grossolana: panoramica rapida. Minima: batch di oltre 100 file. Personalizzata: imposta i tuoi limiti (fino a 500).\nSuggerimento: usa Minima/Grossolana per cartelle con molti file per risparmiare tempo e costi.',
    extractionGranularityFine: 'Fine — analisi approfondita (≤100 elementi)',
    extractionGranularityStandard: 'Standard — note quotidiane (≤50 elementi)',
    extractionGranularityCoarse: 'Grossolana — panoramica rapida (≤10 elementi)',
    extractionGranularityMinimal: 'Minima — batch di oltre 100 file (≤5 elementi)',
    extractionGranularityCustom: 'Personalizzata — imposta i tuoi limiti (1~500)',
    customEntityLimitName: 'Limite entità personalizzato',
    customEntityLimitDesc: 'Numero massimo di entità da estrarre per file sorgente (1-500)',
    customConceptLimitName: 'Limite concetti personalizzato',
    customConceptLimitDesc: 'Numero massimo di concetti da estrarre per file sorgente (1-500)',

    // Issue #85 v2: Vocabolario tag (UX a chip, integrato in Configurazione Wiki)
    tagVocabularyInlineDesc: 'Vocabolario controllato per i tag del frontmatter di entità e concetti. I tag annidati di Obsidian con "/" vengono preservati.',
    tagVocabularyModeName: 'Configurazione vocabolario tag',
    tagVocabularyModeDescDefault: 'Il predefinito usa i tag integrati: {}. Passa a Personalizzato per definire i tuoi.',
    tagVocabularyModeDescCustom: 'Personalizzato: definisci qui sotto i tuoi tag per entità e concetti. Usa l\'input a chip — Invio o virgola per aggiungere, × per rimuovere.',
    tagVocabularyModeDefault: 'Predefinito (tag di sottotipo integrati)',
    tagVocabularyModeCustom: 'Personalizzato (definito dall\'utente)',
    customEntityTagsName: 'Tag entità personalizzati',
    customEntityTagsDesc: 'Premi Invio o virgola per aggiungere una chip. Clicca × per rimuovere. I tag annidati con "/" vengono preservati.',
    customEntityTagsPlaceholder: 'persona, organizzazione, progetto, luogo',
    customConceptTagsName: 'Tag concetti personalizzati',
    customConceptTagsDesc: 'Premi Invio o virgola per aggiungere una chip. Clicca × per rimuovere. I tag annidati con "/" vengono preservati.',
    customConceptTagsPlaceholder: 'teoria, metodo, campo, fenomeno, termine',
    chipDuplicateHint: 'Tag duplicato ignorato',

    // Accelerazione Acquisizione
    accelerationSectionTitle: 'Accelerazione acquisizione',
    pageGenerationConcurrencyName: 'Concorrenza LLM',
    pageGenerationConcurrencyDesc: 'Numero di chiamate LLM in parallelo durante le operazioni di acquisizione e lint. Valori più alti accelerano l\'elaborazione ma aumentano i costi API e possono attivare limiti di frequenza.',
    concurrencyValueSingular: 'Concorrenza attuale: {} (seriale — più sicura)',
    concurrencyValuePlural: 'Concorrenza attuale: {} (parallela)',
    batchDelayName: 'Ritardo batch (ms)',
    batchDelayDesc: 'Ritardo tra batch paralleli per prevenire il rate limiting delle API (100-2000ms). Attuale: {}ms. Aumentalo se vedi errori 429.',

    // Manutenzione Automatica
    autoMaintainSection: 'Manutenzione automatica',
    autoMaintainBetaBadge: 'BETA — Funzionalità sperimentale. Potrebbe presentare problemi. Consigliata solo per utenti esperti.',
    autoWatchName: 'Monitora cartelle',
    autoWatchDesc: 'Rileva automaticamente i file .md nuovi o modificati nelle cartelle monitorate e notifica o acquisisce automaticamente',
    watchedFoldersName: 'Cartelle monitorate',
    watchedFoldersDesc: 'Cartelle da monitorare per nuovi contenuti. Clicca "Aggiungi cartella" per selezionarla dal tuo vault.',
    addWatchedFolderButton: 'Aggiungi cartella',
    removeWatchedFolderButton: 'Rimuovi',
    webClipperPresetName: 'Monitora Clippings (Web Clipper)',
    webClipperPresetDesc: 'Aggiungi alla lista di monitoraggio la cartella Clippings/ usata da Obsidian Web Clipper. I tuoi ritagli web verranno acquisiti automaticamente nella Wiki.',
    noWatchedFoldersHint: 'Nessuna cartella configurata. Aggiungi una cartella o abilita il preset Clippings.',
    autoWatchModeName: 'Modalità monitoraggio',
    autoWatchModeDesc: '"Solo notifica" mostra un avviso. "Acquisizione automatica" elabora in silenzio.',
    watchModeNotify: 'Solo notifica',
    watchModeAuto: 'Acquisizione automatica',
    autoWatchDebounceName: 'Ritardo debounce (secondi)',
    autoWatchDebounceDesc: 'Tempo di attesa prima di avviare l\'acquisizione dopo una modifica di file (1-60 secondi)',
    periodicLintName: 'Lint periodico',
    periodicLintDesc: 'Esegui il lint LLM su pianificazione, solo quando i file sorgente sono cambiati dall\'ultimo controllo',
    periodicLintOff: 'Disattivato',
    periodicLintDaily: 'Giornaliero',
    periodicLintWeekly: 'Settimanale',
    periodicLintMonthly: 'Mensile',
    autoSmartFixName: 'Correzione intelligente automatica',
    autoSmartFixDesc: 'Quando viene eseguito il lint, applica automaticamente tutte le correzioni (Correzione intelligente totale) senza mostrare la modale del report. Il riepilogo delle correzioni viene comunque mostrato al completamento.',
    autoSmartFixNotice: 'Correzione intelligente automatica: applicazione di tutte le correzioni...',

    autoIngestLevelName: 'Notifica di acquisizione automatica',
    autoIngestLevelDesc: 'Come notificare quando l\'acquisizione automatica viene completata. "Notifica" (transitoria) non blocca. "Modale" apre il rapporto completo. Disabilitato quando la modalità Watch è "Solo notifica".',
    autoIngestLevelNotice: 'Notifica (non bloccante)',
    autoIngestLevelModal: 'Modale (rapporto completo)',
    startupCheckName: 'Esegui correzioni rapide all\'avvio',
    startupCheckDesc: 'Corregge automaticamente problemi di formato di basso livello (sorgenti, collegamenti doppiamente annidati) al caricamento del plugin. Verifica la struttura della cartella Wiki. Predefinito ATTIVO.',
    suggestSchemaCommand: 'Suggerisci aggiornamenti Schema',
    autoMaintainCostWarning: '⚠️ Avviso costi: le funzionalità di manutenzione automatica consumano token API. "Acquisizione automatica" attiva chiamate LLM a ogni modifica di file sorgente. "Lint periodico" esegue controlli di salute LLM su pianificazione (solo quando vengono rilevate modifiche alle sorgenti). Configura con attenzione per evitare addebiti imprevisti.',

    // Avvisi
    startupCheckSummary: 'La Wiki ha {pages} pagine ({entities} entità, {concepts} concetti, {sources} sorgenti)',
    watcherActiveNotice: 'Wiki: monitoraggio file attivo — sorveglianza delle cartelle monitorate',
    watchIngestNotice: 'Wiki: {count} file modificati in sources/. Esegui "Acquisisci sorgenti" per elaborarli.',

    // Dettagli correzioni rapide all'avvio (Issue #81)
    startupCheckTitle: 'Correzioni rapide della Wiki completate',
    startupCheckStructureLabel: 'Struttura Wiki',
    startupCheckStructureOk: 'completa',
    startupCheckStructureMissing: 'incompleta — verrà creata automaticamente alla prima acquisizione',
    startupCheckSourcesLabel: 'Sorgenti normalizzate',
    startupCheckSourcesClean: 'già pulite',
    startupCheckSourcesCleaned: 'pulite {files} file, {entries} voce/i',
    startupCheckIncompleteClean: 'pagine incomplete: nessuna',
    startupCheckIncompleteArchived: 'pagine incomplete: {count} archiviate (recuperabili da .trash)',
    startupCheckDisableHint: 'Per disabilitare, vai su Impostazioni → Manutenzione automatica → Esegui correzioni rapide all\'avvio',
    autoIngestRunning: 'Acquisizione automatica di {count} file modificato/i...',
    autoIngestComplete: 'Acquisizione automatica completata: {success} riusciti, {fail} falliti',
    scheduledLintRunning: 'Esecuzione del lint Wiki pianificato...',
    wikiLintStats: 'Lint Wiki: {pages} pagine ({entities} entità, {concepts} concetti, {sources} sorgenti)',
    wikiHealthStats: 'Salute Wiki: {pages} pagine ({entities} entità, {concepts} concetti, {sources} sorgenti){indexStatus}',
    lintWikiStart: 'Avvio del lint Wiki...',
    lintWikiComplete: 'Lint Wiki completato',
    lintWikiFailed: 'Lint Wiki fallito',
    analyzingSchema: 'Analisi della Wiki e generazione di suggerimenti per lo schema...',
    schemaSuggestionGenerated: 'Suggerimenti schema generati, vedi wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: 'Nessun aggiornamento dello schema necessario.',
    schemaSuggestionFailed: 'Suggerimento dello schema fallito',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Anteprima aggiornamento schema',
    schemaDiffSummary: '+{add} / -{del} righe',
    schemaDiffRegenerateLabel: 'Affina il suggerimento (opzionale):',
    schemaDiffRegenerateBtn: 'Rigenera',
    schemaDiffOpenFileBtn: 'Apri file',
    schemaDiffApplyBtn: 'Applica',
    schemaDiffApplied: 'Schema aggiornato. Backup: {path}',
    schemaDiffEmptyTitle: 'LLM non consiglia modifiche',
    schemaDiffFailed: 'Applicazione schema non riuscita: {reason}',
    schemaDiffRestoreHint: 'Backup salvato in {path}. Per ripristinare, rinomina quel file in "wiki/schema/config.md" nell\'esplora file. Vengono conservati i 3 backup più recenti.',
    schemaRegenerateNoBody: 'Rigenerazione riuscita ma l\'LLM non ha restituito un nuovo schema.',
    schemaNotFoundNotice: 'File schema non trovato. Abilita lo schema per crearlo.',
    selectFolderNoMdFiles: 'Nessun file Markdown nella cartella: {path}',
    batchIngestSkipNotice: 'Saltati {skipped}/{total} file già acquisiti. Acquisizione di {new} nuovi file...',
    batchIngestAllIngested: 'Tutti i {total} file in questa cartella sono già stati acquisiti.',
    batchIngestStarting: 'Acquisizione di {count} file da "{folder}" — potrebbe richiedere alcuni minuti. Un report apparirà al completamento.',
    batchIngestComplete: 'Acquisizione batch completata: {success}/{total} riusciti, {fail} falliti',
    batchIngestFailedFiles: 'File falliti:',
    historyTruncated: 'Cronologia troncata agli ultimi {max} turni',
    historyCleared: 'Cronologia cancellata',

    // Ciclo di feedback utente
    reviewedPagePreserved: 'Conservazione del contenuto revisionato dall\'utente per: {}',

    // Feedback da Query a Wiki
    querySuggestSaveTitle: 'Salvare nella Wiki?',
    querySuggestSaveDesc: 'Questa conversazione contiene conoscenza preziosa. Salvarla nella tua Wiki?',
    querySuggestSaveYes: 'Salva',
    querySuggestSaveNo: 'Ignora',

    // Report Acquisizione
    ingestReportElapsedTime: 'Tempo trascorso',
    ingestReportSkippedFiles: 'Saltati (già acquisiti)',
    ingestReportRejectedFiles: 'Saltati',
    rejectionReasonEmpty: 'vuoto',
    rejectionReasonType: 'tipo non supportato',
    rejectionReasonDuplicate: 'contenuto duplicato',
    sourceRejectedEmpty: '⏭️ "{filename}" non ha contenuto da acquisire — saltato. Le note vuote o con solo frontmatter non creano pagine wiki.',
    sourceRejectedType: '⏭️ "{filename}" non è un tipo di file supportato — saltato. Possono essere acquisite solo note di testo (.md, .txt, ecc.).',
    sourceRejectedDuplicate: '⏭️ "{filename}" saltato — il suo contenuto è già nel wiki.',
    ingestRejectedSummary: '{count} file saltati (vuoti, duplicati o di tipo non supportato).',
    reingestConfirmTitle: 'Riacquisire questo file?',
    reingestConfirmBody: 'Il contenuto di "{filename}" è già nel wiki. Riacquisirlo comunque?',
    reingestConfirmYes: 'Riacquisisci',
    reingestConfirmNo: 'Salta',
    ingestReportFailedGuidance: 'Questi elementi non sono stati creati automaticamente. Puoi creare manualmente le pagine corrispondenti, oppure abbassare la granularità di estrazione e ri-acquisire il file sorgente.',
    ingestReportCollisions: 'Collisioni inter-tipo (unite come alias)',

    // Nomi Comandi (sentence case secondo la regola 1 dell'Obsidian Bot)
    cmdIngestSource: 'Acquisisci singola sorgente',
    cmdIngestFolder: 'Acquisisci da cartella',
    cmdIngestMultipleFiles: 'Acquisisci più file',
    cmdQueryWiki: 'Interroga wiki',
    cmdLintWiki: 'Lint wiki',
    cmdRegenerateIndex: 'Rigenera indice',
    cmdSuggestSchema: 'Suggerisci aggiornamenti schema',
    cmdCancelIngestion: 'Annulla acquisizione corrente',
    cmdIngestActiveFile: 'Acquisisci file corrente',
    cmdViewHistory: 'Visualizza cronologia acquisizioni',
    noActiveFile: 'Nessun file è attualmente aperto',
    mdOnlyFile: 'Solo i file Markdown possono essere acquisiti',

    // Barra di stato acquisizione
    ingestionStatusBar: 'Acquisizione... clicca per annullare',
    lintStatusBar: 'Lint... clicca per annullare',
    ingestStatusAnalyzing: 'Acquisizione… (clicca per annullare)',
    lintStatusReading: 'Lint… (clicca per annullare)',
    lintStatusDuplicates: 'Lint… (clicca per annullare)',
    lintStatusScanningLinks: 'Lint… (clicca per annullare)',
    lintStatusAnalyzing: 'Lint… (clicca per annullare)',
    ingestionCancelling: 'Annullamento — si fermerà al completamento del batch corrente',
    ingestionCancelled: 'Acquisizione annullata',
    crossTypeCollisionNotice: '{count} elementi uniti come alias inter-tipo (duplicati entità ↔ concetto prevenuti)',

    // Report Lint
    lintReportTitle: 'Report lint Wiki',
    lintReportSummary: 'Panoramica stato Wiki: {total} pagine totali, {aliasesMissing} pagine senza alias, {duplicates} pagine duplicate, {deadLinks} collegamenti interrotti ({deadLinkFromDup} coinvolgono duplicati), {orphans} pagine orfane ({orphanFromDup} sono duplicati), {emptyPages} pagine vuote, {ungroundedQuotes} citazioni non fondate, {tagViolations} tag fuori vocabolario. Lint completato in: {elapsedSeconds}s',

    // Impostazioni LLM avanzate (v1.20.0: predefinito = nessun override specifico del provider)
    advancedSettingsModeName: 'Impostazioni parametri avanzate',
    advancedSettingsModeDesc: 'La modalità predefinita segue le raccomandazioni del tuo provider. Passa a Personalizzato solo se hai un motivo specifico per sovrascrivere (ad esempio, un modello particolare ha bisogno di una temperatura fissa, o vuoi sopprimere l\'output di ragionamento).',
    advancedSettingsDefault: 'Predefinito (segui provider)',
    advancedSettingsCustom: 'Personalizzato (sovrascrivi provider)',
    disableThinkingName: 'Disabilita ragionamento',
    disableThinkingDesc: 'Disattiva la catena di pensiero/ragionamento nella risposta del modello. Spento per impostazione predefinita — il modello decide se mostrare il ragionamento, il che di solito dà la risposta migliore. Attivalo solo se il tuo provider inserisce testo di ragionamento grezzo nella risposta e desideri una risposta pulita.',
    // Issue #137: suggerimenti di compatibilità per le impostazioni avanzate (tenuti brevi; nessuna
    // lista di provider per evitare oneri di manutenzione quando i provider cambiano).
    extractionTemperatureName: 'Temperatura estrazione',
    extractionTemperatureDesc: 'Controlla se il modello è più conservatore o creativo nello scrivere pagine entity/concept. Valori bassi = più deterministico e fedele; valori alti = più vario. La maggior parte degli utenti lascia vuoto.',
    chatTemperatureName: 'Temperatura query',
    chatTemperatureDesc: 'Stesso concetto della temperatura di estrazione, ma influisce solo su come Query Wiki risponde alle domande. Valori bassi = risposte più letterali; valori alti = risposte più colloquiali. La maggior parte degli utenti lascia vuoto.',
    repetitionPenaltyName: 'Penalità di ripetizione',
    repetitionPenaltyDesc: 'Impedisce al modello di ripetere le stesse parole o frasi. Valori più alti riducono la ripetizione. Solo alcuni provider di modelli locali (Ollama, LM Studio, llama.cpp) accettano questo parametro; i provider cloud lo ignorano silenziosamente. La maggior parte degli utenti lascia vuoto.',
    temperaturePlaceholder: 'lasciare vuoto = predefinito provider',
    lintDeadLinkSection: 'Collegamenti interrotti (rilevati) [{count}]',
    lintEmptyPageSection: 'Pagine vuote (rilevate) [{count}]',
    lintOrphanSection: 'Pagine orfane (rilevate) [{count}]',
    lintContradictionSection: 'Contraddizioni (rilevate)',
    lintDuplicateSection: 'Pagine duplicate (rilevate)',
    lintPollutedSection: 'Pagine inquinate (rilevate) [{count}]',
    lintPollutedItem: '- [[{page}]] → dovrebbe essere "{clean}"',
    lintSourcesNormalizedSection: 'Sorgenti normalizzate (corrette automaticamente) [{files} file / {entries} voci]',
    lintSourcesNormalizedItem: 'Pulite {entries} voci sorgenti inquinate in {files} file (percorsi esterni, estensioni .md, pipe degli alias rimossi e deduplicati).',
    lintNoIssuesFound: 'Nessun duplicato, collegamento interrotto, pagina vuota, pagina orfana o citazione non fondata rilevato.',
    lintQuoteGroundingSection: 'Citazioni non fondate (rilevate) [{count}]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: "{quote}"',
    lintDeadLinkItem: '- [[{source}]] → **{target}** (la pagina non esiste){dupFlag}',
    lintDeadLinkMore: '- ... {count} altri collegamenti interrotti',
    lintEmptyPageItem: '- [[{page}]] — meno di 50 caratteri di contenuto sostanziale',
    lintOrphanItem: '- [[{page}]] — nessun\'altra pagina Wiki collega qui{dupFlag}',
    lintDuplicateItem: '- [[{target}]] e [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' (⚠️ coinvolge una pagina duplicata)',
    lintOrphanIsDuplicate: ' (⚠️ pagina duplicata)',
    lintHubLinkDensitySection: 'Problemi di densità dei link sugli hub (Issue #157 / #175) [{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — {inDegree} entranti, {relatedCount} link correlati, distintività {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ rimuovi',
    lintHubLinkDensityReview: '🔍 esamina',
    lintHubLinkDensityKeep: '✅ mantieni',
    lintHubLinkDensitySummary: 'Riepilogo: {strip} pagina/e consigliate per la rimozione, {review} pagina/e consigliate per la revisione.',
    lintHubLinkDensityNoRelated: ' (nessuna sezione ## Related trovata)',
    lintContradictionOpen: 'Contraddizioni aperte: {count}',
    lintContradictionAutoFixed: '({count} corrette automaticamente in questa esecuzione)',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: 'Rilevata',
    lintContradictionStatusPendingFix: 'Correzione in attesa',
    lintLLMAnalysisHeading: '## Analisi LLM',

    // Prompt di analisi Lint
    lintAnalysisPrompt: 'Sei un assistente per la manutenzione della Wiki. Controlla la salute della Wiki in base alle seguenti informazioni.\n\nIndice Wiki:\n{index}\n\nCampione di contenuto delle pagine Wiki ({total} pagine totali, mostrate {sample} pagine):\n{contentSample}\n\nRisultati dei controlli programmatici (già verificati, non ripetere):\n{progReport}\n\nControlla i seguenti aspetti (salta collegamenti interrotti/vuoti/orfani già rilevati dai controlli programmatici):\n1. **Contraddizioni** — se pagine diverse si contraddicono sugli stessi fatti\n2. **Obsolescenza** — se qualche affermazione è chiaramente datata\n3. **Mancanti** — quali concetti importanti mancano di pagine autonome\n4. **Struttura** — se la struttura delle pagine è ragionevole e i riferimenti incrociati sono adeguati\n\nFormato di output: usa Markdown, iniziando con "## Analisi LLM". Ogni risultato su una riga "- [problema specifico]". Se non ci sono problemi, scrivi "Nessun problema evidente trovato."',
    lintAnalysisProgReportEmpty: 'Nessun problema rilevato dai controlli programmatici.',

    // Avanzamento Correzioni Lint
    lintFixProgress: 'Correzione {current}/{total}: [[{target}]]',
    lintFixDeadComplete: 'Correzione collegamenti interrotti completata. Corretti {fixed}/{total} elementi.',
    lintFillProgress: 'Espansione {current}/{total}: {page}',
    lintFillComplete: 'Espansione delle pagine completata. Compilate {filled}/{total} pagine.',
    lintDeleteCompleted: 'Eliminati {count} stub vuoti',
    lintDeleteFailed: 'Eliminazione fallita di {failed}/{total} stub vuoti (vedi la console per i dettagli)',
    lintFillFailed: 'Espansione fallita: {page} — {error}',
    lintLinkProgress: 'Collegamento {current}/{total}: {page}',
    lintLinkComplete: 'Collegamento delle orfane completato. Collegate {linked} pagine.',
    lintFixNoAction: 'Nessuna azione intrapresa (nessun client)',
    lintFixIndexUpdated: 'Indice e log della Wiki aggiornati.',
    lintFixAllComplete: 'Tutte le correzioni completate. Vedi il log per i dettagli.',
    lintPollutedFixed: 'Pagine inquinate corrette: {fixed}/{total}. Indice rigenerato.',
    regenerateIndexCompleted: 'Indice rigenerato',
    operationFailed: 'Fallito: ',

    // Modale Report Lint
    lintModalActionsTitle: 'Suggerimenti di correzione (richiede token LLM):',
    lintLogReference: 'Report completo salvato in log.md',
    lintModalFixDeadLinks: 'Correggi collegamenti interrotti ({count})',
    lintModalExpandEmpty: 'Espandi pagine vuote ({count})',
    lintModalDeleteEmpty: 'Elimina stub vuoti ({count})',
    lintModalLinkOrphans: 'Collega pagine orfane ({count})',
    lintModalAnalyzeSchema: 'Analizza schema',
    lintModalMergeDuplicates: 'Unisci duplicati ({count})',
    lintModalFixAll: 'Correzione intelligente totale ({count} problemi)',
    lintMergeProgress: 'Unione {current}/{total}: {source} → {target}',
    lintMergeComplete: 'Unione duplicati completata. Unite {merged}/{total} coppie.',

    // Modale Report Acquisizione
    ingestReportTitle: 'Report acquisizione',
    ingestReportSourceFile: 'File sorgente',
    ingestReportCreated: 'Create',
    ingestReportUpdated: 'Aggiornate',
    ingestReportContradictions: 'Contraddizioni trovate',
    ingestReportFailedTitle: 'Acquisizione fallita',
    ingestReportErrorDetail: 'Dettaglio errore',
    ingestReportClose: 'Chiudi',
    ingestReportCreatedPages: 'Pagine create: {count}',
    ingestReportUpdatedPages: 'Pagine aggiornate: {count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki Registro operazioni',
    logHeaderSubtitle: 'Ogni acquisizione, esecuzione lint e operazione di manutenzione viene registrata qui automaticamente. Per una migliore visualizzazione, usa il pannello **Cronologia operazioni**:',
    logHeaderShortcut: 'Cmd+P → "Visualizza cronologia operazioni"',
    logHeaderSettingsShortcut: 'Oppure da Impostazioni → Manutenzione automatica → Cronologia operazioni',
    ingestionCreatedPages: '{count} pagina/e creata/e',
    ingestionUpdatedPages: '{count} pagina/e aggiornata/e',
    ingestionNoticeHistoryHint: 'Visualizza cronologia operazioni per i dettagli',
    ingestReportEntitiesCount: '{count} entità',
    ingestReportConceptsCount: '{count} concetti',
    ingestReportContradictionsFound: 'Contraddizioni trovate: {count}',
    ingestReportEntityType: 'Entità',
    ingestReportConceptType: 'Concetto',
    timeMinutes: 'min',
    timeSeconds: 'sec',

    // Avvisi Limite di Frequenza
    rateLimitDetected: '⚠️ Limite di frequenza rilevato: {count} pagina/e fallita/e con errori 429. Prova: (1) Abbassa la concorrenza a {suggestedConcurrency} o 1 (seriale), (2) Aumenta il ritardo batch a {suggestedDelay}ms, (3) Passa a un provider con limiti di frequenza più alti.',
    rateLimitDetectedShort: '⚠️ Limite di frequenza raggiunto — considera di abbassare la concorrenza o aumentare il ritardo batch in Impostazioni → Accelerazione acquisizione.',

    // Avviso sorgente lunga
    longSourceNotice: '📄 "{filename}" ha {lines} righe ({size}). I testi lunghi richiedono un\'estrazione iterativa a batch — l\'LLM legge l\'intero documento in più passaggi. Questo potrebbe richiedere alcuni minuti. Abbi pazienza.',
    longSourceNoticeShort: '📄 File di grandi dimensioni rilevato ({lines} righe). L\'acquisizione potrebbe richiedere del tempo.',

    // Pannello Cronologia Acquisizioni (#122) — testi UI
    historyButton: 'Cronologia operazioni',
    historyButtonDesc: 'Visualizza acquisizioni recenti, report Lint e altre modifiche del tuo Wiki',
    historyButtonOpen: 'Visualizza cronologia',
    historyModalTitle: 'Cronologia operazioni',
    historyModalSubtitle: 'Modifiche recenti del tuo LLM-Wiki',
    historyEmpty: 'Nessuna operazione registrata. Acquisisci una nota o esegui Lint per popolare questo elenco.',
    historyReadError: 'Impossibile leggere il registro operazioni: {error}',
    historyEntryKindIngest: 'Acquisizione',
    historyEntryKindMaintenance: 'Manutenzione',
    historyEntryKindFix: 'Correzione',
    historyEntryKindOther: 'Altro',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'Sorgente: {source}',
    historyEntrySourceUnknown: 'Acquisizione senza titolo',
    historyEntryCreatedLabel: 'Create',
    historyEntryUpdatedLabel: 'Aggiornate',
    historyEntryCreatedCount: '{count} create',
    historyEntryUpdatedCount: '{count} aggiornate',
    historyEntryNoChanges: 'Nessuna modifica alle pagine',
    historyEntryContradictions: '⚠️ {count} contraddizione/i',
    historyEntrySectionCreated: 'Pagine create',
    historyEntrySectionUpdated: 'Pagine aggiornate',
    historyEntrySectionContradictions: 'Contraddizioni',
    historyEntrySectionDetails: 'Dettagli',
    historyEntryOpenPage: 'Apri',
    historyEntryDetailsNoContradictions: 'Nessuna contraddizione trovata',
    historySearchPlaceholder: '🔍 Cerca per titolo sorgente o percorso pagina…',
    historyFilterAll: 'Tutte',
    historyFilterIngest: 'Solo acquisizioni',
    historyFilterMaintenance: 'Solo manutenzione',
    historyFilterFix: 'Solo correzioni',
    historyFilterContradictions: '⚠️ Con contraddizioni',
    historyRefreshButton: '⟳ Aggiorna',
    historyExpandDay: 'Clicca per espandere',
    historyCollapseDay: 'Clicca per comprimere',
    historyShowMore: 'Mostra {count} voci più vecchie',
    historyNoMatch: 'Nessuna operazione corrisponde alla tua ricerca/filtro.',
    historyCloseButton: 'Chiudi',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'Risultati del rapporto',
    historyKpiPages: 'Pagine',
    historyKpiDeadLinks: 'Link morti',
    historyKpiOrphans: 'Orfane',
    historyKpiEmpty: 'Vuote',
    historyKpiDuplicates: 'Duplicate',
    historyKpiTagViolations: 'Tag',
    historyKpiUnsourced: 'Senza fonte',
    historyKpiDuration: 'Durata Lint',
    historyKpiDurationSec: '{seconds}s',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'Link morti ({count})',
    historySectionTagViolations: 'Tag ({count})',
    historySectionOrphans: 'Pagine orfane ({count})',
    historySectionEmptyPages: 'Pagine vuote ({count})',
    historySectionLlmAnalysis: 'Analisi LLM ({count})',
    historyDeadLinkSource: 'Origine',
    historyDeadLinkTarget: 'Mancante',
    historyOpenInLog: 'Apri in log.md',
    historyShowMoreItems: 'Mostra altri {count}',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ stabile',
    historyChipContradiction: 'Contraddizione',
    historyChipOutdated: 'Obsoleto',
    historyChipMissing: 'Mancante',
    historyChipStructure: 'Struttura',
    historySeverityHigh: 'Alta',
    historySeverityMedium: 'Media',
    historySeverityLow: 'Bassa',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Il tuo Wiki ha {dead} link morto/i, {orphans} pagina/e orfana/e e {tags} problema/i di tag. Ultima Lint: {duration}.',
    historyGlobalInsightClean: 'Il tuo Wiki è pulito — nessun link morto, pagina orfana o problema di tag.',
    historyGlobalInsightNoData: 'Nessun rapporto di manutenzione — esegui Lint.',
    historyModalHeaderTitle: 'Cronologia operazioni',
    historyModalSubtitleWithCount: 'Modifiche recenti del tuo LLM-Wiki · {count} voci',
    historyTimeRangeAll: 'Tutto il periodo',
    historyTimeRange1d: 'Ultimo giorno',
    historyTimeRange3d: 'Ultimi 3 giorni',
    historyTimeRange1w: 'Ultima settimana',
    historyTimeRange1m: 'Ultimo mese',
    historyIngestTotal: 'Pagine totali',
    historyIngestByType: 'Per tipo',
    historyIngestSource: 'File sorgente',
    historyIngestNoTimestamp: 'Nessun timestamp',
    historyIngestFirstTime: 'Prima acquisizione',
    historyIngestLatestTime: 'Ultima acquisizione',
    historyTimeRangeCustom: 'Intervallo personalizzato',
    historyCustomRangeFrom: 'Da',
    historyCustomRangeTo: 'A',
    historyCustomRangeApply: 'Applica',
    historyCustomRangeClear: 'Pulisci',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    // Welcome content (5 sections + 14 keys) is LLM-dynamically translated at write time per D8.
    // Only plugin UI surfaces are localized; no hardcoded 10-language template.
    welcomeNoteTierANotice: 'Karpathy Wiki: il vault è vuoto. Crea la tua prima nota-sorgente ed esegui Ingest per iniziare.',
    welcomeNoteTierBNotice: 'Karpathy Wiki: nota Welcome creata. Aprila per dichiarare i tuoi domini e scegliere 2-3 note-sorgente per seminare il grafo dei collegamenti.',
    welcomeNoteRecreateCommand: 'Ricrea la nota Welcome Wiki',
    welcomeNoteRecreateCommandTooltip: 'Ricrea la nota Welcome in <wikiFolder>/Welcome.md con i semi di dominio attuali e il test di configurazione LLM. Il file esistente viene sovrascritto.',
    welcomeNoteSettingsToggle: 'Crea la nota Welcome Wiki al primo avvio',
    welcomeNoteSettingsToggleDesc: 'Al primo avvio (quando la cartella wiki è vuota), crea una nota introduttiva di una pagina in <wikiFolder>/Welcome.md. Spiega cos\'è LLM-Wiki, ti invita a dichiarare il tuo focus di dominio, e ti guida nell\'inserimento delle prime 2-3 note sorgente. La nota è scritta in inglese per impostazione predefinita, o nella tua lingua wiki se LLM è configurato. Disabilita se conosci già il plugin e non desideri la nota introduttiva.',
    welcomeNoteRunConfigTest: 'Nota Welcome scritta in inglese. Apri Impostazioni → LLM Provider → Test Connection per localizzarla alla prossima ricreazione.',
    welcomeNoteRecreated: 'Nota Welcome Wiki ricreata in {path}',
    welcomeNoteNotRecreated: 'La nota Welcome non è stata ricreata. Controlla la configurazione LLM.',
    welcomeNoteGenerating: 'Nota Welcome Wiki: generazione in background — apparirà un avviso al termine.',
    welcomeNoteGenerationFailed: 'Generazione della nota Welcome Wiki non riuscita: {error}',
    startupCheckWelcomePending: 'Nota Welcome: generazione in background (apparirà un avviso al termine).',
    welcomeNoteFileName: 'Benvenuto in Karpathy LLM Wiki',
    startupCheckWelcomeCreated: 'Nota Welcome creata in {path}',
    // v1.23.0 Phase 5.1.5: pulsante "Annulla tutto" del modale di selezione multipla.
    // Annulla tutti i lavori in attesa e in esecuzione nella coda.
    // I lavori completati e falliti vengono mantenuti per la visualizzazione.
    cancelAllQueueJobs: 'Annulla tutto',
    // v1.23.0 Phase 5.1.5: modale di selezione multipla (cmdIngestMultipleFiles).
    // Titolo, suggerimento, placeholder di ricerca, pulsanti, etichette di
    // stato, placeholder di coda vuota.
    multiFileModalTitle: 'Acquisisci più file',
    multiFileModalHint: 'Seleziona le note di origine da acquisire. Il pannello destro mostra la coda in tempo reale e l\'avanzamento.',
    multiFileSearchPlaceholder: 'Filtra file per percorso…',
    multiFileAddToQueue: 'Aggiungi alla coda',
    multiFileSelectAll: 'Seleziona tutto',
    multiFileFileCount: '{count} file',
    multiFileNoFilesAvailable: 'Nessun file disponibile per l\'acquisizione.',
    multiFileNoFilesMatch: 'Nessun file corrisponde a "{q}".',
    multiFileQueueEmpty: 'Coda vuota. Seleziona i file a sinistra per aggiungerli.',
    multiFileStatusPending: 'In attesa',
    multiFileStatusRunning: 'In esecuzione',
    multiFileStatusCompleted: 'Completato',
    multiFileStatusFailed: 'Fallito',
    multiFileCancelAria: 'Annulla questo file',
    startupCheckNoticeLevelName: 'Mostra risultato correzioni rapide',
    startupCheckNoticeLevelDesc: 'Le QuickFixes vengono sempre eseguite all\'avvio del plugin (nota Welcome, struttura cartelle, normalizzazione sorgenti, pagine incomplete, intestazione log). Scegli se mostrare l\'avviso riepilogativo dopo l\'avvio. La modalità silenziosa registra solo nella console sviluppatore e nel pannello Cronologia operazioni.',
    startupCheckNoticeVisible: 'Visibile (mostra avviso)',
    startupCheckNoticeSilent: 'Silenzioso (nessun avviso)',
} as const;