export const JA_TEXTS = {
    // Plugin Info
    pluginTitle: 'Karpathy LLM Wiki 設定',
    pluginIntro: '本プラグインはObsidian用に{{link}}の概念を実装しています。ノートを読み込み、AIでエンティティと概念を抽出し、Vault内に構造化された相互リンクWikiを構築します。',
    karpathyLinkText: 'Andrej KarpathyのLLM Wiki',

    // Features Section
    featuresTitle: '仕組み',
    workflow1Title: '1. 取り込み',
    workflow1Desc: 'ノートを選択 — AIがエンティティ、概念、関係を抽出してWikiページにまとめます。',
    workflow2Title: '2. 問い合わせ',
    workflow2Desc: 'Wikiとチャット — 回答は取り込んだ知識に基づいています。',
    workflow3Title: '3. 維持管理',
    workflow3Desc: '自動生成のインデックス、相互リンク、LintチェックでWikiの健全性を保ちます。',

    // Language Switcher
    languageTitle: 'インターフェース言語',
    languageDesc: '設定パネルの表示言語を選択してください。言語変更をコマンドパレットに適用するには、プラグインを再起動してください。',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',

    // Status
    statusTitle: 'LLM Client の状態',
    llmWikiStatusSection: 'LLM-Wiki 状態',
    statusInitialized: '初期化済み',
    statusReady: 'LLM 準備完了',
    statusNotReady: 'LLM 未設定 — 上記の設定と接続テストを完了してください',
    statusNotInitialized: '未初期化',
    currentProvider: '現在のプロバイダー',

    // Provider Configuration
    providerSection: 'LLM 設定',
    providerName: 'LLM プロバイダー',
    providerDesc: '定義済みプロバイダーまたはカスタムOpenAI互換サービスを選択。Coding Plan等のバンドルの場合、カスタムOpenAI/Anthropicを選択し、プロバイダーのBase URLとAPI Keyを手動入力',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: 'プロバイダーから発行されたAPI Keyを入力してください',
    apiKeyPlaceholder: 'API Keyを入力',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: '必須：カスタムOpenAI互換エンドポイント',
    baseUrlDescOverride: '任意：定義済みBase URLを上書き',

    // Ollama Hint
    ollamaHint: 'Ollamaはローカルで動作するため、API Keyは不要です',
    lmstudioHint: 'LM Studioはローカルで動作します。API Keyは任意です',
    maxTokensPerCallName: '1回呼び出しの最大出力トークン数',
    maxTokensPerCallDesc: 'モデルが1回の応答で生成できるトークン量を制限します。小さいコンテキストウィンドウのローカルモデルを使っていてエラーが出る場合は下げてください。クラウドモデルではデフォルト（0 = 制限なし）のままで問題ありません。',

    slugCaseName: 'ファイル名の大文字小文字',
    slugCaseDesc: '生成される Wiki ファイル名を小文字化するかどうかを制御します。大文字小文字に意味のある言語（ドイツ語の名詞など）では「保持」を推奨。',
    slugCaseLower: '小文字（デフォルト）',
    slugCasePreserve: '大文字小文字を保持',

    // Model Selection
    modelSection: 'モデル選択',
    fetchModelsName: '利用可能なモデルを取得',
    fetchModelsDesc: 'プロバイダーAPIから最新のモデル一覧を取得します',
    fetchModelsButton: 'モデルを取得',
    fetchingModels: '取得中...',
    fetchSuccess: '取得成功！{}件のモデルが利用可能です',
    fetchFailed: '取得に失敗したかリストが空です。モデル名を手動で入力してください',
    fetchNotSupported: 'このプロバイダーはモデル一覧の取得に対応していません',
    fetchErrorAuth: '認証に失敗しました（HTTP 401/403）。API キーを確認するか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorEndpoint: 'エンドポイントが見つかりません（HTTP 404）。BaseURL を確認するか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorServer: 'プロバイダーサーバーエラー（HTTP 5xx）。後でもう一度お試しいただくか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorEmpty: 'このエンドポイントはモデル一覧を提供していません。モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    fetchErrorNetwork: 'ネットワークリクエストが失敗しました。インターネット接続、BaseURL、またはプロキシ設定を確認してください。モデル ID を直接入力して「テスト接続」をクリックして検証することもできます。',

    selectModelName: 'モデルを選択',
    selectModelDesc: '{}件の利用可能なモデルから選択',
    customInputOption: 'カスタム入力...',
    customInputHint: '他のモデルを使用するには「カスタム入力...」を選択してください',

    modelName: 'モデル名',
    modelDescCustom: 'カスタムモデルを使用中（上のボタンをクリックして一覧を再取得）',
    modelDescFetchFailed: 'モデル一覧の取得に失敗しました。API キーとエンドポイント URL を確認するか、モデル ID を直接入力して「テスト接続」をクリックして検証してください。',
    modelInputPlaceholder: 'モデル ID を入力してテスト接続',

    switchToDropdown: 'ドロップダウン選択に切り替え',
    useDropdownButton: 'ドロップダウンを使用',

    // Test & Save
    testConnectionName: '接続テスト',
    testConnectionDesc: '設定が正常にLLM APIを呼び出せるか確認します',
    testButton: '接続テスト',
    testing: 'テスト中...',

    saveSettingsName: '設定を保存',
    saveSettingsDesc: '現在の設定を保存します',
    saveButton: '設定を保存',
    testConnectionSuccessful: '接続成功',
    testConnectionFailed: '接続失敗',
    testConnectionProvider: 'プロバイダー：',
    errorUnknown: '不明なエラー',
    savedNotice: '設定を保存しました！',

    // Issue #137: LLM フォールバック通知
    fallbackThinkingDialect: '思考制御：「{dialect}」方言に切り替えました（このプロバイダーは別の思考制御フィールド形式を使用します）。出力は変わりません。',
    fallbackThinkingNone: 'このプロバイダーでは思考制御を完全に無効化しました。推論コンテンツが引き続き表示される場合があります。その場合は別のモデルを試してください。',
    fallbackParamStripped: 'パラメータ「{field}」はこのプロバイダーでサポートされていません。リクエストから削除されました。動作は設定と異なる場合があります。',

    // Wiki Folder
    wikiSection: 'Wiki設定',
    wikiFolderName: 'Wiki フォルダー',
    wikiFolderDesc: '生成されたWikiページの保存先',
    wikiFolderPlaceholder: 'wiki',

    // Errors
    errorNoApiKey: 'まずAPI Keyを設定してください',
    llmNotReady: 'LLMが設定されていません。設定 → Karpathy LLM Wiki でプロバイダーを設定し、モデルを取得して接続テストに合格してください。',
    errorFetchFailed: '失敗：{}',

    // Query Settings
    querySectionTitle: 'Wiki 問い合わせ設定',
    maxConversationHistoryName: '会話履歴の最大数',
    maxConversationHistoryDesc: '会話ラウンドのソフト上限（超過時は古いメッセージが自動的に破棄されます）。プリセット：1/10/30/50/100/500。',
    maxConversationHistoryHint: '推奨：50ラウンド以内',
    numberRangeValidation: '1〜50の数値を入力してください',
    numberRangeClamped: '値が範囲外です（1-500）、自動的に {} に設定されました',
    // Query Modal UI
    queryModalTitle: 'Query Wiki - 対話型問い合わせ',
    queryModalPlaceholder: '質問を入力...',
    queryModalSendButton: '送信',
    queryModalStopButton: '停止',
    queryModalSaveButton: 'Wikiに保存',
    queryModalClearButton: '履歴をクリア',
    queryModalHistoryCount: '会話履歴：{}/{} ラウンド',
    queryModalStreaming: 'ストリーミング中...',
    queryModalFallbackStreaming: 'ストリーミングに対応していないため、非ストリーミングに切り替えました。お待ちください...',
    queryPhaseSearching: 'Wikiインデックスを分析し、関連ページを選別中...',
    queryPhaseFoundPages: '{count}件見つかりました：{pages}',
    queryPhaseLoadingPages: 'ページコンテンツを読み込み中...',
    queryPhaseContextReady: 'コンテキスト準備完了。回答を生成中...',
    queryPhaseGenerating: '生成中...（経過 {time}秒）',
    queryPhaseNonStreaming: '非ストリーミングモード、回答生成中...（経過 {time}秒）',
    queryModalErrorPrefix: 'エラー：',
    queryModalHint: '問い合わせはWikiの内容に基づきます。「Wikiに保存」をクリックすると、価値のある会話をWikiページとして抽出できます。',

    // v1.20.0: Query Wiki 思考ブロック折り畳み見出し
    queryThinkingSummary: '思考プロセス',
    queryThinkingSteps: 'ステップ',

    // Error Messages
    errorLLMClientNotInit: 'LLM Clientが初期化されていません。設定を保存してください。',
    errorIngestFailed: '取り込み失敗：',
    errorQueryFailed: '問い合わせ失敗：',
    fileWriteFailed: 'ファイルを作成または更新できません：{path}',

    // Success Messages
    ingestSuccess: '取り込み成功：{}ページ作成、{}ページ更新',
    querySuccess: '問い合わせ完了',
    lintSuccess: 'Wiki Lint完了',
    lintReadingPages: '{count}件のWikiページを読み込み中...',
    lintReadingPagesProgress: 'Wikiページ読み込み中：{current}/{total}...',
    lintScanningLinks: 'リンク切れをスキャン中...',
    lintScanningLinksProgress: 'リンク切れスキャン中：{current}/{total}...',
    lintCheckingDuplicates: '重複ページを確認中...',
    lintCheckingDuplicatesProgress: '重複ページを検証中：バッチ {current} ...',
    lintFixingPolluted: '汚染ページを修正中 {current}/{total}：{title} → {newTitle}',
    lintModalFixPolluted: '🧹 汚染ページを修正（{count}）',
    lintDuplicateCheckFailed: '重複検出に失敗しました — コンソールで詳細を確認してください',
    lintDuplicateCheckFailedDetail: '重複チェックが{step}で失敗：{error}',
    lintMergeItemFailed: 'マージ失敗：{source} → {target} — {error}',
    lintAliasesMissing: '別名未設定：{count}件のページに別名がありません',
    lintAliasesSection: 'エイリアス欠落ページ [{count} 件]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: '別名を補完（{count}件）',
    lintAliasesFilling: '別名生成中 {current}/{total}：{page}',
    lintAliasesFilled: '別名補完完了。{filled}/{total}ページに入力しました。',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: '語彙外タグ（検出）[{count} 件]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: '別名生成に失敗：{page} — {error}',
    lintFixItemFailed: '修復失敗：[[{target}]] — {error}',
    lintLinkItemFailed: 'リンク設定失敗：{page} — {error}',
    lintRetrying: 'エラー後再試行中（{attempt}/{max}）...',
    lintAnalyzingLLM: 'LLMがWikiの健全性を分析中...',
    saveToWikiSuccess: '会話をWikiに保存しました！',
    saveSummary: '{entities} エンティティ, {concepts} コンセプト, {pages} ページ',
    aliasAdded: 'ページ「{page}」に別名「{alias}」を追加しました',

    // Status Messages
    ingestingSources: 'ソースファイルを取り込み中...',
    queryingWiki: 'Wikiに問い合わせ中...',
    lintingWiki: 'WikiをLint中...',
    savingToWiki: '会話をWikiに保存中...',
    clearingHistory: '会話履歴をクリア中...',

    // Buttons
    ingestButton: '取り込み',
    queryButton: '問い合わせ',
    lintButton: 'Lint',
    cancelButton: 'キャンセル',

    // Links
    karpathyGistLink: 'KarpathyのLLM Wiki Gist',
    obsidianPluginAPI: 'Obsidian Plugin API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // Other
    availableModelsLoading: '利用可能なモデルを読み込み中...',
    noModelsAvailable: '利用可能なモデルがありません',

    // LLM Language Hint
    llmLanguageHint: '日本語で回答してください。',

    // Schema Configuration
    schemaSection: 'スキーマ設定',
    enableSchemaName: 'スキーマを有効化',
    enableSchemaDesc: 'schema/config.mdを生成し、すべてのLLMプロンプトに注入して構造化されたWiki出力を実現します',
    viewSchemaButton: 'スキーマの閲覧 / 編集',
    regenerateSchemaButton: 'デフォルトスキーマを再生成',
    schemaRegeneratedNotice: 'デフォルトスキーマを再生成しました。',
    schemaRegenerateFailed: 'スキーマの生成に失敗しました',

    // Wiki 初期化状態
    wikiInitStatusReady: 'Wiki 初期化済み',
    wikiInitStatusNotReady: 'Wiki 未初期化 — 初回取り込み時に自動作成されます',

    // Wiki Output Language
    wikiLanguageName: 'Wiki 出力言語',
    wikiLanguageDesc: '生成されるすべてのWikiページ、インデックス、ログ、問い合わせの応答がこの言語で作成されます',
    customWikiLanguageOption: 'カスタム...',
    customWikiLanguageHint: '言語名を入力してください（例：Italian、Arabic）。LLMに出力言語の指示として渡されます。',
    customWikiLanguagePlaceholder: '例：Italian',

    // Index & Log Labels (per language)
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自动生成的知识库目录', entities: '实体', concepts: '概念', sources: '来源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },
    logLabels: {
      en: { createdPages: 'Created pages', updatedPages: 'Updated pages', contradictionsFound: 'Contradictions found' },
      zh: { createdPages: '创建页面', updatedPages: '更新页面', contradictionsFound: '发现矛盾' },
      ja: { createdPages: '作成ページ', updatedPages: '更新ページ', contradictionsFound: '矛盾を発見' },
      ko: { createdPages: '생성 페이지', updatedPages: '업데이트 페이지', contradictionsFound: '모순 발견' },
      de: { createdPages: 'Erstellte Seiten', updatedPages: 'Aktualisierte Seiten', contradictionsFound: 'Widersprüche gefunden' },
      fr: { createdPages: 'Pages créées', updatedPages: 'Pages mises à jour', contradictionsFound: 'Contradictions trouvées' },
      es: { createdPages: 'Páginas creadas', updatedPages: 'Páginas actualizadas', contradictionsFound: 'Contradicciones encontradas' },
      pt: { createdPages: 'Páginas criadas', updatedPages: 'Páginas atualizadas', contradictionsFound: 'Contradições encontradas' },
    },

    // Extraction Settings
    extractionSectionTitle: '知識抽出',
    extractionGranularityName: '抽出粒度',
    extractionGranularityDesc: 'ソースファイルごとの抽出数を制御。高いほどページ/API消費が増加。\n精细：深度分析（100個）。標準：日常ノート（50個）。粗め：概要把握（10個）。最小：100件以上一括処理（5個）。カスタム：独自設定（最大300個）。\n提示：ファイル数が多い場合は最小/粗めを使用し時間とコストを節約。',
    extractionGranularityFine: '精细 — 深層分析（≤100件）',
    extractionGranularityStandard: '標準 — 日常ノート（≤50件）',
    extractionGranularityCoarse: '粗め — 概要（≤10件）',
    extractionGranularityMinimal: '最小 — 100+ファイル一括処理（≤5件）',
    extractionGranularityCustom: 'カスタム — 上限を独自設定（1~500）',
    customEntityLimitName: 'カスタムエンティティ上限',
    customEntityLimitDesc: 'ソースファイルごとの最大エンティティ抽出数（1-500）',
    customConceptLimitName: 'カスタム概念上限',
    customConceptLimitDesc: 'ソースファイルごとの最大概念抽出数（1-500）',

    // Issue #85 v2: タグ語彙 (chip 入力 UI, Wiki 設定内に埋め込み)
    tagVocabularyInlineDesc: 'entity/concept フロントマターのタグを管理語彙で制御します。"/" を含むネストタグは保持されます。',
    tagVocabularyModeName: 'タグ語彙設定',
    tagVocabularyModeDescDefault: 'デフォルトは組み込みタグを使用: {}。「カスタム」に切り替えると独自の語彙を定義できます。',
    tagVocabularyModeDescCustom: 'カスタム: 下で chip 入力を使って独自の entity/concept タグを定義します。Enter またはカンマで追加、× で削除。',
    tagVocabularyModeDefault: 'デフォルト (組み込みサブタイプタグ)',
    tagVocabularyModeCustom: 'カスタム (ユーザー定義)',
    customEntityTagsName: 'カスタムエンティティタグ',
    customEntityTagsDesc: 'Enter またはカンマで chip 追加、× で削除。"/" を含むネストタグは保持されます。',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: 'カスタム概念タグ',
    customConceptTagsDesc: 'Enter またはカンマで chip 追加、× で削除。"/" を含むネストタグは保持されます。',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: '重複タグをスキップしました',

    // Ingestion Acceleration
    accelerationSectionTitle: '取り込み高速化',
    pageGenerationConcurrencyName: 'LLM 並列度',
    pageGenerationConcurrencyDesc: '取り込みおよびLint操作中の並列LLM呼び出し数。値を高くすると処理が高速化されますが、APIコストの増加やレートリミットのトリガーに注意してください。',
    concurrencyValueSingular: '現在の並列度：{}（直列 — 最も安全）',
    concurrencyValuePlural: '現在の並列度：{}（並列）',
    batchDelayName: 'バッチ遅延（ms）',
    batchDelayDesc: '並列バッチ間の遅延によりAPIレートリミットを回避します（100〜2000ms）。現在値：{}ms。429エラーが発生する場合は値を大きくしてください。',

    // Auto Maintenance
    autoMaintainSection: '自動メンテナンス',
    autoMaintainBetaBadge: 'ベータ版 — 実験機能。問題が発生する可能性があります。上級ユーザーのみ推奨。',
    autoWatchName: '監視フォルダー',
    autoWatchDesc: '監視フォルダー内で新規または変更された.mdファイルを自動検出し、通知または自動取り込みを行います',
    watchedFoldersName: '監視対象フォルダー',
    watchedFoldersDesc: '新コンテンツを監視するフォルダー。「フォルダーを追加」をクリックしてVaultから選択してください。',
    addWatchedFolderButton: 'フォルダーを追加',
    removeWatchedFolderButton: '削除',
    webClipperPresetName: 'Clippingsを監視（Web Clipper）',
    webClipperPresetDesc: 'Obsidian Web Clipperが使用するClippings/フォルダーを監視リストに追加します。ウェブクリップがWikiに自動取り込みされます。',
    noWatchedFoldersHint: '監視フォルダーが設定されていません。フォルダーを追加するかClippingsプリセットを有効にしてください。',
    autoWatchModeName: '監視モード',
    autoWatchModeDesc: '「通知のみ」はプロンプトを表示します。「自動取り込み」はサイレントに処理します。',
    watchModeNotify: '通知のみ',
    watchModeAuto: '自動取り込み',
    autoWatchDebounceName: 'チャタリング防止遅延（秒）',
    autoWatchDebounceDesc: 'ファイル変更後に取り込みをトリガーするまでの待機時間（1〜60秒）',
    periodicLintName: '定期 Lint',
    periodicLintDesc: 'スケジュールに従ってLLM Lintを実行。前回チェック以降にソースファイルの変更がある場合のみ実行します',
    periodicLintOff: 'オフ',
    periodicLintDaily: '毎日',
    periodicLintWeekly: '毎週',
    periodicLintMonthly: '毎月',
    autoSmartFixName: '自動スマート修正',
    autoSmartFixDesc: 'Lint 実行時に、レポートモーダルを表示せず自動的にすべての修正（スマート一括修正）を適用します。修正完了後もサマリーは表示されます。',
    autoSmartFixNotice: '自動スマート修正：すべての修正を適用中...',

    autoIngestLevelName: '自動取り込み通知方法',
    autoIngestLevelDesc: '自動取り込み完了時の通知方法。「通知」は一時的に表示され操作を妨げません。「モーダル」は完全なレポートを開きます。Watch モードが「通知のみ」の場合は無効です。',
    autoIngestLevelNotice: '通知（非ブロッキング）',
    autoIngestLevelModal: 'モーダル（完全レポート）',
    startupCheckName: '起動時にクイック修正を実行',
    startupCheckDesc: 'プラグイン読み込み時に低レベル書式の問題（sources フィールド、二重 wikilink）を自動修正し、Wiki ディレクトリ構造を検証します。デフォルトで有効。',
    suggestSchemaCommand: 'スキーマ更新を提案',
    autoMaintainCostWarning: '⚠️ コストのお知らせ：自動メンテナンス機能はAPIトークンを消費します。「自動取り込み」はソースファイルの変更ごとにLLM呼び出しをトリガーします。「定期Lint」はスケジュールに従ってLLMヘルスチェックを実行します（ソースの変更が検出された場合のみ）。想定外の課金を避けるため、慎重に設定してください。',

    // Notices
    startupCheckSummary: 'Wikiは{pages}ページ（{entities}エンティティ、{concepts}概念、{sources}ソース）',
    watcherActiveNotice: 'Wiki: ファイル監視有効 — 監視フォルダーをモニタリング中',
    watchIngestNotice: 'Wiki: sources/ に{count}件のファイル変更あり。「ソースの取り込み」を実行して処理してください。',
    autoIngestRunning: '{count}件の変更ファイルを自動取り込み中...',
    autoIngestComplete: '自動取り込み完了：成功 {success}件、失敗 {fail}件',
    scheduledLintRunning: 'スケジュールされたWiki Lintを実行中...',
    wikiLintStats: 'Wiki Lint: {pages}ページ（{entities}エンティティ、{concepts}概念、{sources}ソース）',
    wikiHealthStats: 'Wiki健全性: {pages}ページ（{entities}エンティティ、{concepts}概念、{sources}ソース）{indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki クイック修正完了',
    startupCheckStructureLabel: 'Wiki 構造',
    startupCheckStructureOk: '完了',
    startupCheckStructureMissing: '不完全 — 初回取り込み時に自動作成されます',
    startupCheckSourcesLabel: 'Sources 正規化',
    startupCheckSourcesClean: '既に正規化済み',
    startupCheckSourcesCleaned: '{files} ファイル、{entries} エントリを修正',
    startupCheckIncompleteClean: '未完成ページ：なし',
    startupCheckIncompleteArchived: '未完成ページ：{count} 件をアーカイブ（.trash から復元可能）',
    startupCheckDisableHint: '無効化するには 設定 → 自動メンテナンス → 起動時にクイック修正を実行',
    lintWikiStart: 'Wiki Lintを開始中...',
    lintWikiComplete: 'Wiki Lint完了',
    lintWikiFailed: 'Wiki Lint失敗',
    analyzingSchema: 'Wikiを分析し、スキーマの提案を生成中...',
    schemaSuggestionGenerated: 'スキーマの提案を生成しました。wiki/schema/suggestions.mdを確認してください',
    noSchemaUpdateNeeded: 'スキーマの更新は不要です。',
    schemaSuggestionFailed: 'スキーマの提案に失敗しました',
    // v1.22.0 #97: Schema diff Modal — IDE-style preview + Apply/Regenerate
    schemaDiffTitle: 'Schema 更新プレビュー',
    schemaDiffSummary: '+{add} / -{del} 行',
    schemaDiffRegenerateLabel: '提案を修正（任意）：',
    schemaDiffRegenerateBtn: '再生成',
    schemaDiffOpenFileBtn: 'ファイルを開く',
    schemaDiffApplyBtn: '適用',
    schemaDiffApplied: 'Schema を更新しました。バックアップ：{path}',
    schemaDiffEmptyTitle: 'LLM は変更不要と判断',
    schemaDiffFailed: 'Schema の適用に失敗：{reason}',
    schemaDiffRestoreHint: '{path} にバックアップしました。復元するには、ファイルエクスプローラーでそのファイルを "wiki/schema/config.md" にリネームしてください。最近3件のバックアップが保持されます。',
    schemaRegenerateNoBody: '再生成は成功しましたが、LLM は新しい Schema を返しませんでした。',
    schemaNotFoundNotice: 'スキーマファイルが見つかりません。スキーマを有効化して作成してください。',
    selectFolderNoMdFiles: 'フォルダー {path} にMarkdownファイルがありません',
    batchIngestSkipNotice: '取り込み済みの{skipped}/{total}ファイルをスキップ。{new}件の新ファイルを取り込み中...',
    batchIngestAllIngested: 'このフォルダー内の{total}件はすべて取り込み済みです。',
    batchIngestStarting: '「{folder}」から{count}件を取り込み中 — 数分かかる場合があります。完了後にレポートが表示されます。',
    batchIngestComplete: 'バッチ取り込み完了：成功 {success}/{total}件、失敗 {fail}件',
    batchIngestFailedFiles: '失敗したファイル：',
    historyTruncated: '履歴を直近の{max}ラウンドに切り捨てました',
    historyCleared: '履歴をクリアしました',

    // User Feedback Loop
    reviewedPagePreserved: 'ユーザーレビュー済みのコンテンツを保持：{}',

    // Query-to-Wiki feedback
    querySuggestSaveTitle: 'Wikiに保存しますか？',
    querySuggestSaveDesc: 'この会話には価値のある知識が含まれています。Wikiに保存しますか？',
    querySuggestSaveYes: '保存',
    querySuggestSaveNo: '閉じる',

    // Ingestion Report
    ingestReportElapsedTime: '経過時間',
    ingestReportSkippedFiles: 'スキップ済み（取り込み済み）',
    ingestReportRejectedFiles: 'スキップ',
    rejectionReasonEmpty: '空',
    rejectionReasonType: '非対応の形式',
    rejectionReasonDuplicate: '重複コンテンツ',
    ingestReportFailedGuidance: 'これらの項目は自動作成できませんでした。対応するページを手動で作成するか、抽出粒度を下げてソースファイルを再取り込みしてください。',
    ingestReportCollisions: 'クロスタイプ衝突（エイリアスとして統合）',

    // Command Names (sentence case per Obsidian Bot rule 1)
    cmdIngestSource: '単一ソースの取り込み',
    cmdIngestFolder: 'フォルダーからの取り込み',
    cmdIngestMultipleFiles: '複数ファイルを取り込み',
    cmdQueryWiki: 'Wikiに問い合わせ',
    cmdLintWiki: 'WikiのLint',
    cmdRegenerateIndex: 'インデックスの再生成',
    cmdSuggestSchema: 'スキーマ更新の提案',
    cmdCancelIngestion: '現在の取り込みをキャンセル',
    cmdIngestActiveFile: '現在のファイルを取り込む',
    cmdViewHistory: '取り込み履歴を表示',
    noActiveFile: '現在開いているファイルはありません',
    mdOnlyFile: 'Markdownファイルのみ取り込み可能です',

    // Ingestion status bar
    ingestionStatusBar: '取り込み中... クリックでキャンセル',
    lintStatusBar: 'チェック中... クリックでキャンセル',
    ingestStatusAnalyzing: '取り込み中… (クリックでキャンセル)',
    lintStatusReading: 'チェック中… (クリックでキャンセル)',
    lintStatusDuplicates: 'チェック中… (クリックでキャンセル)',
    lintStatusScanningLinks: 'チェック中… (クリックでキャンセル)',
    lintStatusAnalyzing: 'チェック中… (クリックでキャンセル)',
    ingestionCancelling: 'キャンセル中 — 現在のバッチ完了後に停止します',
    ingestionCancelled: '取り込みがキャンセルされました',
    crossTypeCollisionNotice: '{count}件がクロスタイプ別名として統合（エンティティ ↔ コンセプト重複を防止）',

    // Lint Report
    lintReportTitle: 'Wiki Lintレポート',
    lintReportSummary: 'Wiki 状態の概要: 合計 {total} ページ、{aliasesMissing} ページにエイリアス欠落、重複 {duplicates}、デッドリンク {deadLinks}（うち {deadLinkFromDup} は重複関連）、孤立 {orphans}（うち {orphanFromDup} は重複）、空ページ {emptyPages}、根拠のない引用 {ungroundedQuotes}、語彙外タグ {tagViolations}。Lint 実行時間: {elapsedSeconds}秒',

    // Advanced LLM Settings (Issues #99 / #128)
    advancedSettingsModeName: '高度なパラメータ設定',
    advancedSettingsModeDesc: 'デフォルトモードはモデルプロバイダーが推奨する設定に従います。明確に上書きする理由がある場合（例：特定のモデルに固定温度が必要、モデルの思考出力を抑制したい）のみ、カスタムに切り替えてください。',
    advancedSettingsDefault: 'デフォルト（プロバイダーに従う）',
    advancedSettingsCustom: 'カスタム（プロバイダーを上書き）',
    disableThinkingName: '思考を無効にする',
    disableThinkingDesc: 'モデル応答の思考過程/推論テキスト出力をオフにします。デフォルトはオフで、モデルが推論を表示するかを自分で決めるため、それが通常最も良い回答になります。プロバイダーが生の推論テキストを応答に混ぜてしまい、きれいな答えが欲しい場合にのみオンにしてください。',
    // Issue #137: 互換性に関する注意事項（簡潔；プロバイダ一覧は省略）
    extractionTemperatureName: '抽出温度',
    extractionTemperatureDesc: 'モデルがエンティティ/コンセプトページを書くときに、厳密さを優先するか創造性を優先するかを制御します。値が低いほど決定的で原文に忠実、値が高いほど変化に富みます。ほとんどのユーザーは空欄のままで問題ありません。',
    chatTemperatureName: 'クエリ温度',
    chatTemperatureDesc: '「抽出温度」と考え方は同じですが、Query Wiki の質問回答にのみ影響します。値が低いほど文字通りの回答、値が高いほど会話調になります。ほとんどのユーザーは空欄のままで問題ありません。',
    repetitionPenaltyName: '繰り返しペナルティ',
    repetitionPenaltyDesc: 'モデルが同じ単語や言い回しを繰り返すのを抑止します。値が高いほど繰り返しを減らします。このパラメータを受け付けるのは一部のローカルモデルプロバイダー（Ollama、LM Studio、llama.cpp）のみで、クラウドプロバイダーは暗黙に無視します。ほとんどのユーザーは空欄のままで問題ありません。',
    temperaturePlaceholder: '空欄 = プロバイダーのデフォルト',
    lintDeadLinkSection: 'デッドリンク（検出）[{count} 件]',
    lintEmptyPageSection: '空ページ（検出）[{count} 件]',
    lintOrphanSection: '孤立ページ（検出）[{count} 件]',
    lintContradictionSection: '矛盾（検出済み）',
    lintDuplicateSection: '重複ページ（検出済み）',
    lintNoIssuesFound: '重複、リンク切れ、空ページ、孤立ページ、または根拠のない引用は検出されませんでした。',
    lintQuoteGroundingSection: '根拠のない引用（検出）[{count} 件]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}: 「{quote}」',
    lintDeadLinkItem: '- [[{source}]] → **{target}**（ページが存在しません）{dupFlag}',
    lintDeadLinkMore: '- ... 他{count}件のリンク切れ',
    lintEmptyPageItem: '- [[{page}]] — 実質的なコンテンツが50文字未満',
    lintOrphanItem: '- [[{page}]] — 他のWikiページからリンクされていません{dupFlag}',
    lintPollutedSection: '汚染ページ（検出）[{count} 件]',
    lintPollutedItem: '- [[{page}]] → "{clean}"に修正必要',
    lintSourcesNormalizedSection: 'Sources 正規化（自動修正）[{files} ファイル / {entries} 件]',
    lintSourcesNormalizedItem: '{files} ファイル内の {entries} 件の sources エントリを修正しました（外部パス、.md 拡張子、エイリアスパイプを削除し重複排除）。',
    lintDuplicateItem: '- [[{target}]] と [[{source}]] — {reason}',
    lintDeadLinkAffectedByDup: ' （⚠️ 重複ページが関連）',
    lintOrphanIsDuplicate: ' （⚠️ 重複ページ）',
    lintHubLinkDensitySection: 'ハブのリンク密度の問題（Issue #157 / #175）[{count}]',
    lintHubLinkDensityItem: '- [[{page}]] — 被リンク {inDegree}、関連リンク {relatedCount}、識別度 {distinctiveness} → {recommendation}{lowTargets}',
    lintHubLinkDensityStrip: '⚠️ 削除',
    lintHubLinkDensityReview: '🔍 確認',
    lintHubLinkDensityKeep: '✅ 保持',
    lintHubLinkDensitySummary: '要約：削除推奨 {strip} ページ、確認推奨 {review} ページ。',
    lintHubLinkDensityNoRelated: ' （## Related セクションが見つかりません）',
    lintContradictionOpen: '未解決の矛盾：{count}件',
    lintContradictionAutoFixed: '（今回{count}件を自動修復）',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: '検出済み',
    lintContradictionStatusPendingFix: '修復待ち',
    lintLLMAnalysisHeading: '## LLM分析',

    // Lint Analysis Prompt
    lintAnalysisPrompt: 'あなたはWikiメンテナンスの助手です。以下の情報に基づいてWikiの健全性を確認してください。\n\nWikiインデックス：\n{index}\n\nWikiページ内容サンプル（合計{total}ページ、{sample}ページを表示）：\n{contentSample}\n\nプログラムによるチェック結果（検証済み、重複報告不要）：\n{progReport}\n\n以下の項目を確認してください（プログラムにより検出済みのリンク切れ・空ページ・孤立ページは除外）：\n1. **矛盾** — 異なるページ間で同一事実に関する記述が矛盾していないか\n2. **陳腐化** — 明らかに古くなった記述がないか\n3. **不足** — 重要な概念に独立したページがないものはないか\n4. **構造** — ページ構造が妥当で、相互参照が十分か\n\n出力形式：Markdownを使用し、「## LLM分析」で始めてください。各発見は一行で「- [具体的な問題]」と記載。問題がない場合は「明らかな問題は見つかりませんでした。」と記載してください。',
    lintAnalysisProgReportEmpty: 'プログラムによるチェックで問題は検出されませんでした。',

    // Lint Fix Progress
    lintFixProgress: '修復中 {current}/{total}：[[{target}]]',
    lintFixDeadComplete: 'リンク切れ修復完了。{fixed}/{total}件を修復しました。',
    lintFillProgress: '拡充中 {current}/{total}：{page}',
    lintFillComplete: 'ページ拡充完了。{filled}/{total}ページを入力しました。',
    lintDeleteCompleted: '{count}件の空スタブを削除しました',
    lintDeleteFailed: '空 stub の削除に {failed}/{total} 件失敗（詳細はコンソール）',
    lintFillFailed: '拡充に失敗：{page} — {error}',
    lintLinkProgress: 'リンク設定中 {current}/{total}：{page}',
    lintLinkComplete: '孤立ページへのリンク完了。{linked}ページにリンクを設定しました。',
    lintFixNoAction: '操作なし（クライアント未接続）',
    lintFixIndexUpdated: 'Wikiインデックスとログを更新しました。',
    lintPollutedFixed: '汚染ページ修正済み：{fixed}/{total}。インデックス再構築済み。',
    regenerateIndexCompleted: 'インデックス再構築済み',
    operationFailed: '失敗：',
    lintFixAllComplete: 'すべての修復が完了しました。詳細はログを確認してください。',

    // Lint Report Modal
    lintModalActionsTitle: '修復提案（LLMトークンを消費）：',
    lintLogReference: '完全なレポートが log.md に保存されました',
    lintModalFixDeadLinks: 'リンク切れを修復（{count}件）',
    lintModalExpandEmpty: '空ページを拡充（{count}件）',
    lintModalDeleteEmpty: '空のスタブを削除（{count}件）',   
    lintModalLinkOrphans: '孤立ページにリンク（{count}件）',
    lintModalAnalyzeSchema: 'スキーマを分析',
    lintModalMergeDuplicates: '重複をマージ（{count}件）',
    lintModalFixAll: '一括スマート修復（{count}件の問題）',
    lintMergeProgress: 'マージ中 {current}/{total}：{source} → {target}',
    lintMergeComplete: '重複マージ完了。{merged}/{total}組をマージしました。',

    // Ingest Report Modal
    ingestReportTitle: '取り込みレポート',
    ingestReportSourceFile: 'ソースファイル',
    ingestReportCreated: '作成',
    ingestReportUpdated: '更新',
    ingestReportContradictions: '矛盾を発見',
    ingestReportFailedTitle: '取り込み失敗',
    ingestReportErrorDetail: 'エラー詳細',
    ingestReportClose: '閉じる',
    ingestReportCreatedPages: '作成ページ：{count}',
    ingestReportUpdatedPages: '更新ページ：{count}',
    // v1.22.2: log.md header content (Operation History Panel hint)
    logHeaderTitle: 'Wiki 操作ログ',
    logHeaderSubtitle: '取り込み、Lint実行、メンテナンス操作はすべてここに自動記録されます。より良い表示には**操作履歴**パネルをご利用ください：',
    logHeaderShortcut: 'Cmd+P → "操作履歴を表示"',
    logHeaderSettingsShortcut: 'または 設定 → 自動メンテナンス → 操作履歴 から',
    ingestionCreatedPages: '{count} ページ作成',
    ingestionUpdatedPages: '{count} ページ更新',
    ingestionNoticeHistoryHint: '詳細は操作履歴を表示',
    ingestReportEntitiesCount: '{count}件のエンティティ',
    ingestReportConceptsCount: '{count}件の概念',
    ingestReportContradictionsFound: '矛盾を発見：{count}件',
    ingestReportEntityType: 'エンティティ',
    ingestReportConceptType: '概念',
    timeMinutes: '分',
    timeSeconds: '秒',

    // レートリミット警告
    rateLimitDetected: '⚠️ レートリミットを検出：{count}ページが429エラーで失敗しました。対処法：(1) 並列度を{suggestedConcurrency}または1（直列）に下げる、(2) バッチ遅延を{suggestedDelay}msに増やす、(3) より高いレートリミットを持つプロバイダーに切り替える。',
    rateLimitDetectedShort: '⚠️ レートリミット発生 — 設定→取り込み加速で並列度を下げるかバッチ遅延を増やすことを推奨。',

    sourceRejectedEmpty: '⏭️ 「{filename}」には取り込む内容がないためスキップしました。空のノートやフロントマターのみのノートはWikiページを生成しません。',
    sourceRejectedType: '⏭️ 「{filename}」はサポートされていないファイル形式のためスキップしました。取り込めるのはテキストノート（.md、.txt など）のみです。',
    sourceRejectedDuplicate: '⏭️ 「{filename}」をスキップしました — 内容はすでにWikiに存在します。',
    ingestRejectedSummary: '{count} 個のファイルをスキップしました（空・重複・非対応形式）。',
    reingestConfirmTitle: 'このファイルを再取り込みしますか？',
    reingestConfirmBody: '「{filename}」の内容はすでにWikiに存在します。それでも再取り込みしますか？',
    reingestConfirmYes: '再取り込み',
    reingestConfirmNo: 'スキップ',
    longSourceNotice: '"📄 「{filename}」は{lines}行（{size}）です。長文は複数パスの反復抽出が必要で、LLMが全文書を分析するため数分かかる場合があります。しばらくお待ちください。"',
    longSourceNoticeShort: '"📄 大きなファイル（{lines}行）を検出しました。取り込みに時間がかかることがあります。"',

    // 取り込み履歴パネル (#122) — UI テキスト
    historyButton: '操作履歴',
    historyButtonDesc: 'LLM-Wiki の最近の取り込み・Lint レポート・その他の変更を表示',
    historyButtonOpen: '履歴を表示',
    historyModalTitle: '操作履歴',
    historyModalSubtitle: 'LLM-Wiki の最近の変更',
    historyEmpty: 'まだ操作記録がありません。ノートを取り込むか Lint を実行して記録を作成してください。',
    historyReadError: '操作ログを読み込めません：{error}',
    historyEntryKindIngest: '取り込み',
    historyEntryKindMaintenance: 'メンテナンス',
    historyEntryKindFix: '修正',
    historyEntryKindOther: 'その他',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: 'ソース：{source}',
    historyEntrySourceUnknown: '無題の取り込み',
    historyEntryCreatedLabel: '作成',
    historyEntryUpdatedLabel: '更新',
    historyEntryCreatedCount: '{count} 件作成',
    historyEntryUpdatedCount: '{count} 件更新',
    historyEntryNoChanges: 'ページ変更なし',
    historyEntryContradictions: '⚠️ 矛盾 {count} 件',
    historyEntrySectionCreated: '作成したページ',
    historyEntrySectionUpdated: '更新したページ',
    historyEntrySectionContradictions: '矛盾',
    historyEntrySectionDetails: '詳細',
    historyEntryOpenPage: '開く',
    historyEntryDetailsNoContradictions: '矛盾は見つかりませんでした',
    historySearchPlaceholder: '🔍 ソース名またはページパスで検索…',
    historyFilterAll: 'すべて',
    historyFilterIngest: '取り込みのみ',
    historyFilterMaintenance: 'メンテナンスのみ',
    historyFilterFix: '修正のみ',
    historyFilterContradictions: '⚠️ 矛盾あり',
    historyRefreshButton: '⟳ 更新',
    historyExpandDay: 'クリックで展開',
    historyCollapseDay: 'クリックで折りたたむ',
    historyShowMore: '古い {count} 件を表示',
    historyNoMatch: '検索/フィルタに一致する操作がありません。',
    historyCloseButton: '閉じる',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: 'レポート所見',
    historyKpiPages: 'ページ数',
    historyKpiDeadLinks: 'デッドリンク',
    historyKpiOrphans: '孤立',
    historyKpiEmpty: '空ページ',
    historyKpiDuplicates: '重複',
    historyKpiTagViolations: 'タグ違反',
    historyKpiUnsourced: '未出典',
    historyKpiDuration: 'Lint 時間',
    historyKpiDurationSec: '{seconds} 秒',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: 'デッドリンク ({count})',
    historySectionTagViolations: 'タグ違反 ({count})',
    historySectionOrphans: '孤立ページ ({count})',
    historySectionEmptyPages: '空ページ ({count})',
    historySectionLlmAnalysis: 'LLM 分析 ({count})',
    historyDeadLinkSource: '参照元',
    historyDeadLinkTarget: '欠落',
    historyOpenInLog: 'log.md で表示',
    historyShowMoreItems: '残り {count} 件を展開',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ 変化なし',
    historyChipContradiction: '矛盾',
    historyChipOutdated: '古い',
    historyChipMissing: '欠落',
    historyChipStructure: '構造',
    historySeverityHigh: '高',
    historySeverityMedium: '中',
    historySeverityLow: '低',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: 'Wiki には {dead} 件のデッドリンク、{orphans} 件の孤立ページ、{tags} 件のタグ違反があります。前回の Lint は {duration} かかりました。',
    historyGlobalInsightClean: 'Wiki は正常です — デッドリンク、孤立ページ、タグ違反は検出されていません。',
    historyGlobalInsightNoData: 'メンテナンスレポートがまだありません — Lint を実行してください。',
    historyModalHeaderTitle: '操作履歴',
    historyModalSubtitleWithCount: 'LLM-Wiki の最近の変更 · 全 {count} 件',
    historyTimeRangeAll: '全期間',
    historyTimeRange1d: '過去 1 日',
    historyTimeRange3d: '過去 3 日',
    historyTimeRange1w: '過去 1 週間',
    historyTimeRange1m: '過去 1 か月',
    historyIngestTotal: 'ページ総数',
    historyIngestByType: 'タイプ別',
    historyIngestSource: 'ソースファイル',
    historyIngestNoTimestamp: 'タイムスタンプなし',
    historyIngestFirstTime: '最初の取り込み',
    historyIngestLatestTime: '最新の取り込み',
    historyTimeRangeCustom: 'カスタム範囲',
    historyCustomRangeFrom: '開始',
    historyCustomRangeTo: '終了',
    historyCustomRangeApply: '適用',
    historyCustomRangeClear: 'クリア',
    // v1.23.0 — first-run welcome note (Phase 5.1.5)
    welcomeNoteTierANotice: 'Karpathy Wiki：vault が空です。最初のソースノートを作成して Ingest を実行してください。',
    welcomeNoteTierBNotice: 'Karpathy Wiki：Welcome note を作成しました。開いてドメインを宣言し、2-3 個のソースノートを選んでリンクグラフのシードとしてください。',
    welcomeNoteRecreateCommand: 'Wiki Welcome note を再作成',
    welcomeNoteRecreateCommandTooltip: '現在のドメインシードと LLM 設定テストで <wikiFolder>/Welcome.md に Welcome note を再作成します。既存ファイルは上書きされます。',
    welcomeNoteSettingsToggle: '初回実行時に Wiki Welcome note を作成',
    welcomeNoteSettingsToggleDesc: '初回起動時（wiki フォルダーが空のとき）に、<wikiFolder>/Welcome.md に1枚の入門ノートを自動作成します。LLM-Wiki の説明、ドメインフォーカスの宣言方法、最初の 2-3 個のソースノートの取り込み方を案内します。ノートはデフォルトで英語で書かれ、LLM が設定されていればあなたの wiki 言語で書かれます。プラグインの使い方を既に理解していて、入門ノートが不要ならオフにできます。',
    welcomeNoteRunConfigTest: 'Welcome note は英語で書き込まれました。次回の再作成時にローカライズするには、設定 → LLM Provider → Test Connection を開いてください。',
    welcomeNoteRecreated: '{path} に Wiki Welcome note を再作成しました',
    welcomeNoteNotRecreated: 'Welcome note は再作成されませんでした。LLM 設定を確認してください。',
    welcomeNoteGenerating: 'Wiki Welcome note をバックグラウンドで生成中 — 完了時に通知が表示されます。',
    welcomeNoteGenerationFailed: 'Wiki Welcome note の生成に失敗しました：{error}',
    startupCheckWelcomePending: 'Welcome note：バックグラウンドで生成中（完了時に通知が表示されます）。',
    welcomeNoteFileName: 'Karpathy LLM Wiki へようこそ',
    startupCheckWelcomeCreated: '{path} に Welcome note を作成しました',
    // v1.23.0 Phase 5.1.5: 複数ファイル取り込みモーダルの「すべてキャンセル」ボタン。
    // キュー内のすべての pending + running ジョブを一度にキャンセルします。
    // 完了済みと失敗のジョブは表示用に保持されます。
    cancelAllQueueJobs: 'すべてキャンセル',
    // v1.23.0 Phase 5.1.5: 複数ファイル取り込みモーダル (cmdIngestMultipleFiles)。
    // タイトル、ヒント、検索プレースホルダー、ボタン、状態ラベル、キュー空のプレースホルダー。
    multiFileModalTitle: '複数ファイルを取り込み',
    multiFileModalHint: '取り込むソースノートを選択してください。右側パネルにライブキューと進行状況が表示されます。',
    multiFileSearchPlaceholder: 'パスでファイルを絞り込む…',
    multiFileAddToQueue: 'キューに追加',
    multiFileSelectAll: 'すべて選択',
    multiFileFileCount: '{count} 件のファイル',
    multiFileNoFilesAvailable: '取り込み可能なファイルがありません。',
    multiFileNoFilesMatch: '"{q}" に一致するファイルはありません。',
    multiFileQueueEmpty: 'キューは空です。左側のファイルを選択してください。',
    multiFileStatusPending: '待機中',
    multiFileStatusRunning: '取り込み中',
    multiFileStatusCompleted: '完了',
    multiFileStatusFailed: '失敗',
    multiFileCancelAria: 'このファイルを取り消す',
    startupCheckNoticeLevelName: 'クイック修正結果の表示',
    startupCheckNoticeLevelDesc: 'QuickFixes はプラグイン起動時に常に実行されます（Welcome note、フォルダ構造、ソース正規化、不完全ページ、ログヘッダー）。起動後にサマリー通知を表示するかどうかを選択します。サイレントモードでは開発者コンソールと操作履歴パネルのみに記録されます。',
    startupCheckNoticeVisible: '表示（通知を表示）',
    startupCheckNoticeSilent: 'サイレント（通知なし）',
} as const;