export const ZH_HANT_TEXTS = {
    // 插件信息
    pluginTitle: 'Karpathy LLM Wiki 設定',
    pluginIntro: '本外掛為 Obsidian 實現了 {{link}} 概念。它讀取你的筆記，用 AI 提取實體和概念，在 Vault 中構建結構化、互聯的知識庫。',
    karpathyLinkText: 'Andrej Karpathy 的 LLM Wiki',

    // 功能部分
    featuresTitle: '使用方式',
    workflow1Title: '1. 攝入 (Ingest)',
    workflow1Desc: '選擇筆記 → AI 提取實體、概念、關係 → 生成 Wiki 頁面。',
    workflow2Title: '2. 查詢 (Query)',
    workflow2Desc: '與 Wiki 對話，答案基於你已攝入的知識，而非通用知識。',
    workflow3Title: '3. 維護 (Maintain)',
    workflow3Desc: '自動生成索引、交叉連結、健康檢查，保持 Wiki 整潔。',

    // 语言切换
    languageTitle: '介面語言',
    languageDesc: '選擇設定面板的顯示語言。重啟外掛以將語言更改應用到命令面板。',
    languageEn: 'English',
    languageZh: '中文',
    languageZhHant: '繁體中文',
    languageJa: '日本語',
    languageKo: '한국어',
    languageDe: 'Deutsch',
    languageFr: 'Français',
    languageEs: 'Español',
    languagePt: 'Português',
    languageIt: 'Italiano',

    // 状态
    statusTitle: 'LLM Client 狀態',
    llmWikiStatusSection: 'LLM-Wiki 狀態',
    statusInitialized: '已初始化',
    statusReady: 'LLM 已就緒',
    statusNotReady: 'LLM 未配置 — 請完成上方設定並透過連線測試',
    statusNotInitialized: '未初始化',
    currentProvider: '當前提供商',

    // Provider 设置
    providerSection: 'LLM 配置',
    providerName: 'LLM Provider',
    providerDesc: '選擇預定義提供商或自定義 OpenAI 相容服務。對於 Coding Plan 等套餐，建議選擇自定義 OpenAI/Anthropic 並手工填寫對應 URL 和 API Key',

    // API Key
    apiKeyName: 'API Key',
    apiKeyDesc: '輸入提供商的 API Key',
    apiKeyPlaceholder: '輸入 API Key',

    // Base URL
    baseUrlName: 'API Base URL',
    baseUrlDescCustom: '必填：自定義 OpenAI 相容服務的 endpoint',
    baseUrlDescOverride: '可選：覆蓋預設的 Base URL',

    // Ollama 提示
    ollamaHint: 'Ollama 本地執行，無需 API Key',
    lmstudioHint: 'LM Studio 本地執行，API Key 可選',
    maxTokensPerCallName: '上下文視窗',
    maxTokensPerCallDesc: '限制生成 Token 以適配模型上下文視窗。0 = 無限制（雲端預設）。',

    slugCaseName: '檔名大小寫',
    slugCaseDesc: '控制生成的 Wiki 檔名是否轉為小寫。對於大小寫有語義的語言（如德語名詞），建議選擇“保留”。',
    slugCaseLower: '小寫（預設）',
    slugCasePreserve: '保留大小寫',

    // 模型选择
    modelSection: '模型選擇',
    fetchModelsName: '獲取可用模型',
    fetchModelsDesc: '從 Provider API 獲取最新的模型列表',
    fetchModelsButton: '獲取模型列表',
    fetchingModels: '獲取中...',
    fetchSuccess: '獲取成功！共 {} 個可用模型',
    fetchFailed: '獲取失敗或列表為空，請手動輸入模型名稱',
    fetchNotSupported: '該 Provider 不支援模型列表查詢',
    fetchErrorAuth: '認證失敗（HTTP 401/403）。請檢查 API Key 是否正確，或直接輸入模型 ID 後點選測試連線進行驗證。',
    fetchErrorEndpoint: '接入點未找到（HTTP 404）。請檢查 BaseURL 是否正確，或直接輸入模型 ID 後點選測試連線。',
    fetchErrorServer: 'Provider 服務端錯誤（HTTP 5xx）。稍後重試，或直接輸入模型 ID 後點選測試連線。',
    fetchErrorEmpty: '該接入點不支援列出模型列表。請直接輸入模型 ID 後點選測試連線進行驗證。',
    fetchErrorNetwork: '網路請求失敗。請檢查網路連線、BaseURL 或代理設定。您也可以直接輸入模型 ID 後點選測試連線進行驗證。',

    selectModelName: '選擇模型',
    selectModelDesc: '從 {} 個可用模型中選擇',
    customInputOption: '自定義輸入...',
    customInputHint: '如需使用其他模型，請選擇"自定義輸入..."',

    modelName: '模型名稱',
    modelDescCustom: '當前使用自定義模型（可重新獲取列表）',
    modelDescFetchFailed: '模型列表獲取失敗。請檢查 API Key 和接入點 URL，或直接輸入模型 ID 後點選測試連線進行驗證。',
    modelInputPlaceholder: '輸入模型 ID，然後點選測試連線',

    switchToDropdown: '切換到下拉選擇',
    useDropdownButton: '使用下拉選擇',

    // 测试 & 保存
    testConnectionName: '測試連線',
    testConnectionDesc: '驗證配置能否成功呼叫 LLM API',
    testButton: '測試連線',
    testing: '測試中...',

    saveSettingsName: '儲存設定',
    saveSettingsDesc: '儲存當前配置',
    saveButton: '儲存設定',
    testConnectionSuccessful: '連線成功',
    testConnectionFailed: '連線失敗',
    testConnectionProvider: '提供商：',
    errorUnknown: '未知錯誤',
    savedNotice: '設定已儲存！',

    // Issue #137: LLM 回退通知（请求中触发 thinking-dialect 回退或字段剥离时显示）
    fallbackThinkingDialect: '思考控制：已切換至 "{dialect}" 方言（該提供商使用不同的思考控制欄位格式）。輸出內容不受影響。',
    fallbackThinkingNone: '該提供商已完全關閉思考控制。模型仍可能產生推理內容；若出現，請嘗試其他模型。',
    fallbackParamStripped: '引數 "{field}" 不被該提供商支援。已從請求中移除；行為可能與配置不同。',

    // Wiki 文件夹
    wikiSection: 'Wiki 配置',
    wikiFolderName: 'Wiki 資料夾',
    wikiFolderDesc: '存放生成的 Wiki 頁面',
    wikiFolderPlaceholder: 'wiki',

    // 错误
    errorNoApiKey: '請先配置 API Key',
    llmNotReady: 'LLM 尚未配置。請前往 設定 → Karpathy LLM Wiki 完成 Provider 配置、獲取模型列表並透過連線測試。',
    errorFetchFailed: '獲取失敗：{}',

    // Query 设置
    querySectionTitle: 'Wiki 查詢配置',
    maxConversationHistoryName: '對話歷史上限',
    maxConversationHistoryDesc: '限制對話訊息數，避免超出LLM token限制',
    maxConversationHistoryHint: '推薦：不超過50輪',
    numberRangeValidation: '請輸入1-50之間的數字',
    numberRangeClamped: '數值超出範圍（1-500），已自動設定為 {}',

    // Query Modal UI
    queryModalTitle: 'Query Wiki - 對話式查詢',
    queryModalPlaceholder: '輸入問題...',
    queryModalSendButton: '傳送',
    queryModalStopButton: '停止',
    queryModalSaveButton: '儲存到Wiki',
    queryModalClearButton: '清空歷史',
    queryModalHistoryCount: '對話歷史: {}/{} 輪',
    queryModalStreaming: '流式生成中...',
    queryModalFallbackStreaming: '端點不支援流式傳輸，已回退至非流式模式，請耐心等待...',
    queryPhaseSearching: '正在分析 Wiki 索引，查詢相關資料...',
    queryPhaseFoundPages: '找到 {count} 個資料：{pages}',
    queryPhaseLoadingPages: '正在載入頁面內容...',
    queryPhaseContextReady: '資料就緒，正在生成回覆...',
    queryPhaseGenerating: '正在生成回覆...（已等待 {time}s）',
    queryPhaseNonStreaming: '非流式模式，生成中，請耐心等待...（已等待 {time}s）',
    queryModalErrorPrefix: '錯誤：',
    queryModalHint: '查詢基於Wiki內容。點選"儲存到Wiki"可將有價值對話提煉為Wiki頁面。',

    // v1.20.0: Query Wiki 思考内容折叠摘要
    queryThinkingSummary: '思考過程',
    queryThinkingSteps: '步',

    // 错误消息
    errorLLMClientNotInit: 'LLM Client 未初始化。請儲存設定。',
    errorIngestFailed: '攝入失敗：',
    errorQueryFailed: '查詢失敗：',
    fileWriteFailed: '無法建立或更新檔案：{path}',

    // 成功消息
    ingestSuccess: '攝入成功：建立{}頁，更新{}頁',
    querySuccess: '查詢完成',
    lintSuccess: 'Wiki 維護完成',
    lintReadingPages: '正在讀取 {count} 個 Wiki 頁面...',
    lintReadingPagesProgress: '正在讀取 Wiki 頁面：{current}/{total}...',
    lintScanningLinks: '正在掃描斷鏈...',
    lintScanningLinksProgress: '正在掃描斷鏈：{current}/{total}...',
    lintCheckingDuplicates: '正在檢查重複頁面...',
    lintCheckingDuplicatesProgress: '正在校驗重複項：批次 {current} ...',
    lintFixingPolluted: '正在修復汙染頁面 {current}/{total}：{title} → {newTitle}',
    lintModalFixPolluted: '🧹 修復汙染頁面（{count}）',
    lintDuplicateCheckFailed: '重複檢測失敗 — 詳見控制檯',
    lintDuplicateCheckFailedDetail: '重複檢測在{step}失敗：{error}',
    lintMergeItemFailed: '合併失敗：{source} → {target} — {error}',
    lintAliasesMissing: '檢測到 {count} 個頁面缺少別名',
    lintAliasesSection: '缺失別名的頁面（程式檢測）[共 {count} 個]',
    lintAliasesItem: '- [[{page}]]',
    lintAliasesCompleteBtn: '補全別名（{count}）',
    lintAliasesFilling: '生成別名 {current}/{total}：{page}',
    lintAliasesFilled: '別名補全完成。已填充 {filled}/{total} 頁。',
    lintTagViolationFiring: 'Retagging {current}/{total}: {path}',
    lintTagViolationFailed: 'Retag failed for {path}: {error}',
    lintTagViolationFixed: 'Retag complete. Fixed {fixed}/{total} page(s).',
    lintTagViolationFixedNone: 'Retag complete. No pages needed fixing (LLM kept current tags).',
    lintTagViolationSection: '標籤越界（程式檢測）[共 {count} 個]',
    lintTagViolationItem: '- [[{path}]] — invalid: {tags}',
    lintTagViolationRetagBtn: '🏷️ Retag {count} page(s) with LLM',
    lintAliasesFillFailed: '別名生成失敗：{page} — {error}',
    lintFixItemFailed: '修復失敗：[[{target}]] — {error}',
    lintLinkItemFailed: '連結失敗：{page} — {error}',
    lintRetrying: '出錯後重試中（{attempt}/{max}）...',
    lintAnalyzingLLM: 'LLM 正在分析 Wiki 健康狀態...',
    saveToWikiSuccess: '對話已儲存到Wiki！',
    saveSummary: '{entities} 個實體, {concepts} 個概念, {pages} 個頁面',
    aliasAdded: '已為頁面\'{page}\'新增別名\'{alias}\'',

    // 状态消息
    ingestingSources: '正在攝入原始檔...',
    queryingWiki: '正在查詢 Wiki...',
    lintingWiki: '正在維護 Wiki...',
    savingToWiki: '正在儲存對話到Wiki...',
    clearingHistory: '清空對話歷史...',

    // 按钮
    ingestButton: '攝入',
    queryButton: '查詢',
    lintButton: '維護',
    cancelButton: '取消',

    // 链接
    karpathyGistLink: 'Karpathy\'s LLM Wiki Gist',
    obsidianPluginAPI: 'Obsidian Plugin API',
    anthropicSDK: 'Anthropic SDK',
    openaiSDK: 'OpenAI SDK',

    // 其他
    availableModelsLoading: '載入可用模型...',
    noModelsAvailable: '無可用模型',

    // LLM 语言提示
    llmLanguageHint: '請用中文回答。',

    // Schema 配置
    schemaSection: 'Schema 配置',
    enableSchemaName: '啟用 Schema',
    enableSchemaDesc: '生成 schema/config.md 並注入到所有 LLM 提示詞中，指導 Wiki 結構化輸出',
    viewSchemaButton: '檢視 / 編輯 Schema',
    regenerateSchemaButton: '重新生成預設 Schema',
    schemaRegeneratedNotice: '預設 Schema 已重新生成。',
    schemaRegenerateFailed: 'Schema 生成失敗',

    // Wiki 初始化状态
    wikiInitStatusReady: 'Wiki 已初始化',
    wikiInitStatusNotReady: 'Wiki 未初始化 — 將在首次攝入時自動建立',

    // Wiki 输出语言
    wikiLanguageName: 'Wiki 輸出語言',
    wikiLanguageDesc: '所有生成的 Wiki 頁面、索引、日誌和查詢回覆均使用此語言',
    customWikiLanguageOption: '自定義...',
    customWikiLanguageHint: '輸入語言名稱（如 Italian、Arabic），將作為輸出語言指令傳遞給 LLM。',
    customWikiLanguagePlaceholder: '例如：Italian',

    // 索引 & 日志标签（各语言）
    indexLabels: {
      en: { subtitle: 'Auto-generated knowledge base directory', entities: 'Entities', concepts: 'Concepts', sources: 'Sources' },
      zh: { subtitle: '自動生成的知識庫目錄', entities: '實體', concepts: '概念', sources: '來源' },
      ja: { subtitle: '自動生成ナレッジベースディレクトリ', entities: 'エンティティ', concepts: '概念', sources: 'ソース' },
      ko: { subtitle: '자동 생성 지식 베이스 디렉토리', entities: '엔티티', concepts: '컨셉', sources: '소스' },
      de: { subtitle: 'Automatisch generiertes Wissensdatenbank-Verzeichnis', entities: 'Entitäten', concepts: 'Konzepte', sources: 'Quellen' },
      fr: { subtitle: 'Répertoire de base de connaissances généré automatiquement', entities: 'Entités', concepts: 'Concepts', sources: 'Sources' },
      es: { subtitle: 'Directorio de base de conocimiento generado automáticamente', entities: 'Entidades', concepts: 'Conceptos', sources: 'Fuentes' },
      pt: { subtitle: 'Diretório de base de conhecimento gerado automaticamente', entities: 'Entidades', concepts: 'Conceitos', sources: 'Fontes' },
    },
    logLabels: {
      en: { createdPages: 'Created pages', updatedPages: 'Updated pages', contradictionsFound: 'Contradictions found' },
      zh: { createdPages: '建立頁面', updatedPages: '更新頁面', contradictionsFound: '發現矛盾' },
      ja: { createdPages: '作成ページ', updatedPages: '更新ページ', contradictionsFound: '矛盾を発見' },
      ko: { createdPages: '생성 페이지', updatedPages: '업데이트 페이지', contradictionsFound: '모순 발견' },
      de: { createdPages: 'Erstellte Seiten', updatedPages: 'Aktualisierte Seiten', contradictionsFound: 'Widersprüche gefunden' },
      fr: { createdPages: 'Pages créées', updatedPages: 'Pages mises à jour', contradictionsFound: 'Contradictions trouvées' },
      es: { createdPages: 'Páginas creadas', updatedPages: 'Páginas actualizadas', contradictionsFound: 'Contradicciones encontradas' },
      pt: { createdPages: 'Páginas criadas', updatedPages: 'Páginas atualizadas', contradictionsFound: 'Contradições encontradas' },
    },

    // 知识提取
    extractionSectionTitle: '知識提取',
    extractionGranularityName: '提取顆粒度',
    extractionGranularityDesc: '控制每篇原始檔提取的實體/概念數量。越高 = 生成頁面越多，API消耗越大。\n精細：單篇深度。標準：日常筆記。粗放：快速概覽。極簡：批次100+檔案。自定義：自行設定（最高300個）。\n提示：批次處理大量檔案時，建議使用極簡或粗放以節省時間和成本。',
    extractionGranularityFine: '精細 — 單篇深度分析（≤100個）',
    extractionGranularityStandard: '標準 — 日常筆記（≤50個）',
    extractionGranularityCoarse: '粗放 — 快速概覽（≤10個）',
    extractionGranularityMinimal: '極簡 — 批次100+檔案（≤5個）',
    extractionGranularityCustom: '自定義 — 自行設定上限（1~500）',
    customEntityLimitName: '自定義實體上限',
    customEntityLimitDesc: '每篇原始檔最多提取的實體數量（1-500）',
    customConceptLimitName: '自定義概念上限',
    customConceptLimitDesc: '每篇原始檔最多提取的概念數量（1-500）',

    // Issue #85 v2: 标签词汇表 (chip input 交互, 嵌入 Wiki 配置)
    tagVocabularyInlineDesc: '為 entity 和 concept frontmatter 標籤設定受控詞彙。Obsidian 巢狀標籤 "/" 會被保留。',
    tagVocabularyModeName: '標籤（Tags)詞彙表配置',
    tagVocabularyModeDescDefault: '預設使用內建標籤: {}。切換到"自定義"可定義您自己的詞彙。',
    tagVocabularyModeDescCustom: '自定義：在下方使用 chip 輸入定義您自己的 entity 與 concept 標籤。回車或逗號新增, × 刪除。',
    tagVocabularyModeDefault: '預設 (內建子型別標籤)',
    tagVocabularyModeCustom: '自定義 (使用者定義)',
    customEntityTagsName: '自定義實體標籤',
    customEntityTagsDesc: '按回車或逗號新增 chip, 點 × 刪除。巢狀標籤 "/" 會被保留。',
    customEntityTagsPlaceholder: 'person, organization, project, place',
    customConceptTagsName: '自定義概念標籤',
    customConceptTagsDesc: '按回車或逗號新增 chip, 點 × 刪除。巢狀標籤 "/" 會被保留。',
    customConceptTagsPlaceholder: 'theory, method, field, phenomenon, term',
    chipDuplicateHint: '重複標籤已跳過',

    // 摄入加速
    accelerationSectionTitle: '攝入加速',
    pageGenerationConcurrencyName: 'LLM 併發度',
    pageGenerationConcurrencyDesc: '攝入和 Lint 操作中的並行 LLM 呼叫數。數值越高處理越快，但會增加 API 消耗並可能觸發限流。',
    concurrencyValueSingular: '當前併發度：{}（序列 — 最安全）',
    concurrencyValuePlural: '當前併發度：{}（並行）',
    batchDelayName: '批次延遲 (ms)',
    batchDelayDesc: '並行批次間的延遲，防止 API 限流（100-2000ms）。當前值：{}ms。如遇 429 錯誤請增大此值。',

    // 自动维护
    autoMaintainSection: '自動維護',
    autoMaintainBetaBadge: 'BETA 測試 — 實驗性功能，可能存在問題，僅建議高階使用者使用。',
    autoWatchName: '監聽資料夾',
    autoWatchDesc: '自動檢測監聽列表中資料夾的新增或變更 .md 檔案，通知或自動攝入',
    watchedFoldersName: '監聽資料夾列表',
    watchedFoldersDesc: '監聽新內容的資料夾。點選「新增資料夾」從倉庫中選擇。',
    addWatchedFolderButton: '新增資料夾',
    removeWatchedFolderButton: '移除',
    webClipperPresetName: '監聽 Clippings（Web Clipper）',
    webClipperPresetDesc: '將 Obsidian Web Clipper 使用的 Clippings/ 資料夾加入監聽列表。網頁剪藏內容將自動攝入 Wiki。',
    noWatchedFoldersHint: '尚未配置監聽資料夾。請新增資料夾或啟用 Clippings 預設。',
    autoWatchModeName: '監聽模式',
    autoWatchModeDesc: '"僅通知"顯示提示。"自動攝入"靜默處理。',
    watchModeNotify: '僅通知',
    watchModeAuto: '自動攝入',
    autoWatchDebounceName: '防抖延遲 (秒)',
    autoWatchDebounceDesc: '檔案變更後等待多久觸發攝入 (1-60秒)',
    periodicLintName: '定時維護',
    periodicLintDesc: '定期檢查 Wiki 健康狀況，有原始檔變更時才執行 LLM 維護',
    periodicLintOff: '關閉',
    periodicLintHourly: '每小時',
    periodicLintDaily: '每天',
    periodicLintWeekly: '每週',
    autoSmartFixName: '自動智慧修復',
    autoSmartFixDesc: '執行 Lint 時，自動執行所有修復（智慧一鍵修復），無需顯示報告彈窗。修復完成後仍會顯示摘要。',
    autoSmartFixNotice: '自動智慧修復：正在應用所有修復...',
    startupCheckName: '啟動時執行快速修復',
    startupCheckDesc: '外掛載入時自動修復低階格式問題（sources 欄位、雙層 wikilink），並驗證 Wiki 目錄結構。預設開啟。',
    suggestSchemaCommand: '建議 Schema 更新',
    autoMaintainCostWarning: '⚠️ 費用提醒：自動維護功能會消耗 API Token。"自動攝入"模式在每次原始檔變更時觸發 LLM 呼叫。"定時維護"定期執行 LLM 健康檢查（僅在有新變更時執行）。請謹慎配置以避免意外費用。',

    // 通知
    startupCheckSummary: 'Wiki 共 {pages} 頁（{entities} 個實體、{concepts} 個概念、{sources} 個來源）',
    watcherActiveNotice: 'Wiki: 檔案監聽已啟動 — 正在監控指定資料夾',
    watchIngestNotice: 'Wiki: sources/ 中有 {count} 個檔案變更。請執行"攝入原始檔"處理。',
    autoIngestRunning: '正在自動攝入 {count} 個變更檔案...',
    autoIngestComplete: '自動攝入完成：成功 {success}，失敗 {fail}',
    scheduledLintRunning: '正在執行定時 Wiki 維護...',
    wikiLintStats: 'Wiki 維護: 共 {pages} 頁（{entities} 實體, {concepts} 概念, {sources} 來源）',
    wikiHealthStats: 'Wiki 健康: 共 {pages} 頁（{entities} 實體, {concepts} 概念, {sources} 來源）{indexStatus}',

    // Startup quick fixes detail (Issue #81)
    startupCheckTitle: 'Wiki 快速修復完成',
    startupCheckStructureLabel: 'Wiki 結構',
    startupCheckStructureOk: '完整',
    startupCheckStructureMissing: '不完整 — 將在首次攝入時自動建立',
    startupCheckSourcesLabel: 'Sources 歸一化',
    startupCheckSourcesClean: '已規範',
    startupCheckSourcesCleaned: '清理了 {files} 個檔案，{entries} 處條目',
    startupCheckIncompleteClean: '未完成頁面：無',
    startupCheckIncompleteArchived: '未完成頁面：歸檔了 {count} 個（可從 .trash 恢復）',
    startupCheckDisableHint: '如需關閉，前往 設定 → 自動維護 → 啟動時執行快速修復',
    lintWikiStart: '開始維護 wiki...',
    lintWikiComplete: '維護完成',
    lintWikiFailed: '維護失敗',
    analyzingSchema: '正在分析 Wiki 並生成 Schema 建議...',
    schemaSuggestionGenerated: 'Schema 建議已生成，請檢視 wiki/schema/suggestions.md',
    noSchemaUpdateNeeded: '未檢測到 Schema 需要更新。',
    schemaSuggestionFailed: 'Schema 建議生成失敗',
    schemaNotFoundNotice: 'Schema 檔案未找到。啟用 Schema 功能以建立它。',
    selectFolderNoMdFiles: '資料夾 {path} 中沒有 Markdown 檔案',
    batchIngestSkipNotice: '跳過 {skipped}/{total} 個已攝入檔案。正在攝入 {new} 個新檔案...',
    batchIngestAllIngested: '該資料夾中的所有 {total} 個檔案均已攝入。',
    batchIngestStarting: '正在從 "{folder}" 攝入 {count} 個檔案 — 可能需要數分鐘。完成後會顯示報告。',
    batchIngestComplete: '批次攝入完成: 成功 {success}/{total}, 失敗 {fail}',
    batchIngestFailedFiles: '失敗的檔案:',
    historyTruncated: '歷史已截斷至最近 {max} 輪對話',
    historyCleared: '歷史已清空',

    // 用户反馈闭环
    reviewedPagePreserved: '已保留使用者審閱內容: {}',

    // Query 回流
    querySuggestSaveTitle: '儲存到 Wiki？',
    querySuggestSaveDesc: '此對話包含有價值的知識點，是否儲存到 Wiki？',
    querySuggestSaveYes: '儲存',
    querySuggestSaveNo: '忽略',

    // 摄入报告
    ingestReportElapsedTime: '耗時',
    ingestReportSkippedFiles: '跳過（已攝入）',
    ingestReportRejectedFiles: '已跳過',
    rejectionReasonEmpty: '空內容',
    rejectionReasonType: '不支援的型別',
    rejectionReasonDuplicate: '重複內容',
    ingestReportFailedGuidance: '這些條目未能自動建立。您可手動建立對應頁面，或降低提取顆粒度後重新攝入原始檔。',
    ingestReportCollisions: '跨型別碰撞（已合併為別名）',

    // 命令名称（sentence case 遵循 Obsidian Bot 规则）
    cmdIngestSource: '攝入單個原始檔',
    cmdIngestFolder: '從資料夾攝入',
    cmdQueryWiki: '查詢 Wiki',
    cmdLintWiki: '維護 Wiki',
    cmdRegenerateIndex: '重新生成索引',
    cmdSuggestSchema: '建議 Schema 更新',
    cmdCancelIngestion: '取消當前提取',
    cmdIngestActiveFile: '攝入當前檔案',
    cmdViewHistory: '檢視攝入歷史',
    noActiveFile: '當前沒有開啟的檔案',
    mdOnlyFile: '僅支援攝入 Markdown 檔案',

    // Ingestion status bar
    ingestionStatusBar: '提取中... 點選取消',
    lintStatusBar: '維護中... 點選取消',
    ingestStatusAnalyzing: '提取中… (點選取消)',
    lintStatusReading: '維護中… (點選取消)',
    lintStatusDuplicates: '維護中… (點選取消)',
    lintStatusScanningLinks: '維護中… (點選取消)',
    lintStatusAnalyzing: '維護中… (點選取消)',
    ingestionCancelling: '正在取消 — 當前批次完成後將停止',
    ingestionCancelled: '提取已取消',
    crossTypeCollisionNotice: '{count} 個條目合併為跨型別別名（實體 ↔ 概念重複已防止）',

    // 维护报告
    lintReportTitle: 'Wiki 維護報告',
    lintReportSummary: 'Wiki 狀態概覽：共 {total} 個頁面，{aliasesMissing} 個缺失別名，重複 {duplicates} 個，斷鏈 {deadLinks} 個（其中 {deadLinkFromDup} 個涉及重複頁面），孤立 {orphans} 個（其中 {orphanFromDup} 個是重複頁面），空洞 {emptyPages} 個，無來源引證 {ungroundedQuotes} 個，標籤越界 {tagViolations} 個。本次 Lint 耗時 {elapsedSeconds} 秒',

    // Advanced LLM Settings (Issues #99 / #128)
    advancedSettingsModeName: '高階引數設定',
    advancedSettingsModeDesc: '預設模式使用 provider 自身的行為，不傳送任何思考控制、溫度或重複懲罰欄位。適合大多數使用者。僅當需要顯式覆蓋 provider 預設值時（例如強制特定思考控制方言、設定非預設溫度等），再切換到自定義模式。',
    advancedSettingsDefault: '預設（使用 provider 行為）',
    advancedSettingsCustom: '自定義（覆蓋 provider 預設）',
    disableThinkingName: '禁用思考',
    disableThinkingDesc: '顯式啟用。開啟後，外掛會向 provider 傳送思考控制指令，並在 provider 拒絕時回退到 3 層級方言鏈（anthropic → openai → none）。僅當你的 provider 把思考內容洩露到回答中並需要抑制時才使用。大多數 provider 自身能正確處理思考，關閉它（預設）通常能獲得更高質量。',
    // Issue #137: 兼容性提示（简短；不列举 provider，避免维护负担）
    extractionTemperatureName: '提取溫度',
    extractionTemperatureDesc: '範圍 0–2。越低則 LLM 輸出越確定、越忠於原文；越高則越有創意。留空表示使用提供商預設值。若提供商拒絕此值，外掛會自動剝離該欄位並顯示一次性通知。',
    chatTemperatureName: '查詢溫度',
    chatTemperatureDesc: '範圍 0–2。與提取溫度相同，但隻影響聊天/查詢回覆。留空表示使用提供商預設值。若提供商拒絕此值，外掛會自動剝離該欄位並顯示一次性通知。',
    repetitionPenaltyName: '重複懲罰',
    repetitionPenaltyDesc: '範圍 0–2。越高則越能減少重複模式。留空表示使用提供商預設值。相容性提示：許多雲端提供商不接受此欄位，外掛會在 400 時自動剝離並顯示一次性通知。',
    temperaturePlaceholder: '留空 = 提供商預設',
    lintDeadLinkSection: '斷鏈（程式檢測）[共 {count} 個]',
    lintEmptyPageSection: '空洞頁面（程式檢測）[共 {count} 個]',
    lintOrphanSection: '孤立頁面（程式檢測）[共 {count} 個]',
    lintContradictionSection: '矛盾（程式檢測）',
    lintDeadLinkItem: '- [[{source}]] → **{target}**（頁面不存在）{dupFlag}',
    lintDeadLinkMore: '- ... 共 {count} 處斷鏈',
    lintEmptyPageItem: '- [[{page}]] — 內容不足 50 字元',
    lintOrphanItem: '- [[{page}]] — 無其他 Wiki 頁面連結至此{dupFlag}',
    lintContradictionAutoFixed: '（本次自動修復 {count} 個）',
    lintDeadLinkAffectedByDup: ' （⚠️ 涉及重複頁面）',
    lintOrphanIsDuplicate: ' （⚠️ 重複頁面）',
    lintNoIssuesFound: '未檢測到重複、斷鏈、空洞、孤立頁面或無來源引證。',
    lintQuoteGroundingSection: '無來源引證（程式檢測）[共 {count} 個]',
    lintQuoteGroundingItem: '- [[{page}]]{sourceHint}："{quote}"',
    lintContradictionOpen: '未解決的矛盾：{count} 個',
    lintContradictionItem: '- [{status}] [[{page}]] — {claim}',
    lintContradictionStatusDetected: '待處理',
    lintContradictionStatusPendingFix: '待修復',
    lintLLMAnalysisHeading: '## LLM 分析',

    // 维护分析 Prompt
    lintAnalysisPrompt: '你是一個 Wiki 維護助手。請基於以下資訊檢查 Wiki 的健康狀況。\n\nWiki 索引：\n{index}\n\nWiki 頁面內容樣本（共 {total} 頁，展示 {sample} 頁）：\n{contentSample}\n\n程式檢測結果（已驗證，請勿重複報告）：\n{progReport}\n\n請檢查以下方面（跳過程式已檢測的斷鏈/空洞/孤立）：\n1. **矛盾** — 不同頁面對同一事實的說法是否矛盾\n2. **過時** — 是否有宣告明顯過時\n3. **缺失** — 哪些重要概念缺少獨立頁面\n4. **結構** — 頁面結構是否合理，交叉引用是否充分\n\n輸出格式：使用 Markdown，以 "## LLM 分析" 開頭。每個發現用一行 "- [具體問題]"。如無問題則寫 "✅ 未發現明顯問題。"',

    // 维护修复进度
    lintFixProgress: '修復斷鏈 {current}/{total}：[[{target}]]',
    lintFixDeadComplete: '斷鏈修復完成。已修復 {fixed}/{total} 項。',
    lintFillProgress: '擴充空洞 {current}/{total}：{page}',
    lintFillComplete: '頁面擴充完成。已填充 {filled}/{total} 頁。',
    lintDeleteCompleted: '已刪除 {count} 個空洞頁面',
    lintDeleteFailed: '刪除失敗 {failed}/{total} 個空白 stub（詳情見控制檯）',
    lintFillFailed: '擴充失敗：{page} — {error}',
    lintLinkProgress: '連結孤立 {current}/{total}：{page}',
    lintLinkComplete: '孤立頁面連結完成。已連結 {linked} 頁。',
    lintFixNoAction: '未執行操作（無 client）',
    lintFixIndexUpdated: 'Wiki 索引和日誌已更新。',
    lintPollutedFixed: '已修復汙染頁面：{fixed}/{total}。索引已重建。',
    regenerateIndexCompleted: '索引已重建',
    operationFailed: '失敗：',
    lintFixAllComplete: '所有修復已完成。詳情見日誌。',

    // 维护报告弹窗
    lintModalActionsTitle: '修復建議（需消耗LLM Token）：',
    lintLogReference: '完整報告已儲存至 log.md',
    lintModalFixDeadLinks: '修復斷鏈（{count}）',
    lintModalExpandEmpty: '擴充空洞頁面（{count}）',
    lintModalDeleteEmpty: '刪除空洞頁面（{count}）',   
    lintModalLinkOrphans: '連結孤立頁面（{count}）',
    lintModalAnalyzeSchema: '分析 Schema',
    lintModalMergeDuplicates: '合併重複頁面（{count}）',
    lintModalFixAll: '一鍵修復所有問題（{count}）',
    lintDuplicateSection: '重複頁面（程式檢測）',
    lintPollutedSection: '汙染頁面（程式檢測）[共 {count} 個]',
    lintPollutedItem: '- [[{page}]] → 應為 "{clean}"',
    lintSourcesNormalizedSection: 'Sources 已歸一化（自動修復）[共 {files} 個檔案 / {entries} 處]',
    lintSourcesNormalizedItem: '清理了 {files} 個檔案中的 {entries} 處 sources 條目（已移除外部路徑、.md 字尾、別名管道，並去重）。',
    lintDuplicateItem: '- [[{target}]] 與 [[{source}]] — {reason}',
    lintMergeProgress: '合併 {current}/{total}：{source} → {target}',
    lintMergeComplete: '重複頁面合併完成。已合併 {merged}/{total} 對。',

    // 摄入报告弹窗
    ingestReportTitle: '攝入報告',
    ingestReportSourceFile: '原始檔',
    ingestReportCreated: '已建立',
    ingestReportUpdated: '已更新',
    ingestReportContradictions: '發現矛盾',
    ingestReportFailedTitle: '未能攝入',
    ingestReportErrorDetail: '錯誤詳情',
    ingestReportClose: '關閉',
    ingestReportCreatedPages: '建立頁面：{count}',
    ingestReportUpdatedPages: '更新頁面：{count}',
    ingestReportEntitiesCount: '{count} 個實體',
    ingestReportConceptsCount: '{count} 個概念',
    ingestReportContradictionsFound: '發現矛盾：{count}',
    ingestReportEntityType: '實體',
    ingestReportConceptType: '概念',
    timeMinutes: '分',
    timeSeconds: '秒',

    // 速率限制警告
    rateLimitDetected: '⚠️ 檢測到速率限制：{count} 個頁面因 429 錯誤失敗。建議：(1) 降低併發度至 {suggestedConcurrency} 或 1（序列），(2) 增大批次延遲至 {suggestedDelay}ms，(3) 切換到速率限制更高的提供商。',
    rateLimitDetectedShort: '⚠️ 觸發速率限制 — 建議在設定 → 攝入加速中降低併發度或增大批次延遲。',

    // 长文本摄入提示
    sourceRejectedEmpty: '⏭️ "{filename}" 沒有可提取的內容，已跳過。空筆記或僅含 frontmatter 的筆記不會生成 Wiki 頁面。',
    sourceRejectedType: '⏭️ "{filename}" 不是受支援的檔案型別，已跳過。僅可提取文字筆記（如 .md、.txt）。',
    sourceRejectedDuplicate: '⏭️ "{filename}" 已跳過——其內容已存在於 Wiki 中。',
    ingestRejectedSummary: '已跳過 {count} 個檔案（空檔案、重複或不支援的型別）。',
    reingestConfirmTitle: '重新提取該檔案？',
    reingestConfirmBody: '"{filename}" 的內容已存在於 Wiki 中。仍要重新提取嗎？',
    reingestConfirmYes: '重新提取',
    reingestConfirmNo: '跳過',
    longSourceNotice: '📄 "{filename}" 包含 {lines} 行（{size}）。長文字需要多輪迭代提取，LLM 將完整讀取文件進行多次分析，耗時可能較長，請耐心等待。',
    longSourceNoticeShort: '📄 檢測到大檔案（{lines} 行），攝入可能需要較長時間。',

    // 摄入历史面板 (#122) — UI 文案
    historyButton: '操作歷史',
    historyButtonDesc: '檢視 LLM-Wiki 最近的攝入、Lint 報告和其他變更記錄',
    historyButtonOpen: '檢視歷史',
    historyModalTitle: '操作歷史',
    historyModalSubtitle: 'LLM-Wiki 最近的變更記錄',
    historyEmpty: '暫無操作記錄。攝入筆記或執行 Lint 以填充此列表。',
    historyReadError: '無法讀取操作日誌：{error}',
    historyEntryKindIngest: '攝入',
    historyEntryKindMaintenance: '維護',
    historyEntryKindFix: '修復',
    historyEntryKindOther: '其他',
    historyEntryTime: '{date} · {time}',
    historyEntryTimeNoTime: '{date}',
    historyEntrySource: '來源：{source}',
    historyEntrySourceUnknown: '未命名攝入',
    historyEntryCreatedLabel: '已建立',
    historyEntryUpdatedLabel: '已更新',
    historyEntryCreatedCount: '新建 {count} 個',
    historyEntryUpdatedCount: '更新 {count} 個',
    historyEntryNoChanges: '無頁面變更',
    historyEntryContradictions: '⚠️ {count} 處矛盾',
    historyEntrySectionCreated: '建立的頁面',
    historyEntrySectionUpdated: '更新的頁面',
    historyEntrySectionContradictions: '矛盾',
    historyEntrySectionDetails: '詳情',
    historyEntryOpenPage: '開啟',
    historyEntryDetailsNoContradictions: '未發現矛盾',
    historySearchPlaceholder: '🔍 按來源標題或頁面路徑搜尋…',
    historyFilterAll: '全部',
    historyFilterIngest: '僅攝入',
    historyFilterMaintenance: '僅維護報告',
    historyFilterFix: '僅修復',
    historyFilterContradictions: '⚠️ 含矛盾',
    historyRefreshButton: '⟳ 重新整理',
    historyExpandDay: '點選展開',
    historyCollapseDay: '點選收起',
    historyShowMore: '顯示更早的 {count} 條',
    historyNoMatch: '沒有操作匹配您的搜尋/篩選條件。',
    historyCloseButton: '關閉',
    historyLimit: 50,
    historyBadgeIngestShort: '📥',
    historyBadgeMaintenanceShort: '🔍',
    historyBadgeFixShort: '🔧',
    historyBadgeOtherShort: '📌',
    historyEntrySectionReport: '報告發現',
    historyKpiPages: '頁面數',
    historyKpiDeadLinks: '斷鏈',
    historyKpiOrphans: '孤立',
    historyKpiEmpty: '空洞',
    historyKpiDuplicates: '重複',
    historyKpiTagViolations: '標籤問題',
    historyKpiUnsourced: '無來源',
    historyKpiDuration: 'Lint 耗時',
    historyKpiDurationSec: '{seconds} 秒',
    // Operation History v3 — rich section rendering
    historySectionDeadLinks: '斷鏈 ({count})',
    historySectionTagViolations: '標籤越界 ({count})',
    historySectionOrphans: '孤立頁面 ({count})',
    historySectionEmptyPages: '空洞頁面 ({count})',
    historySectionLlmAnalysis: 'LLM 分析 ({count})',
    historyDeadLinkSource: '來源',
    historyDeadLinkTarget: '缺失',
    historyOpenInLog: '在 log.md 中檢視',
    historyShowMoreItems: '展開剩餘 {count} 項',
    historyTrendUp: '↗ {delta}',
    historyTrendDown: '↘ {delta}',
    historyTrendSame: '→ 持平',
    historyChipContradiction: '矛盾',
    historyChipOutdated: '過時',
    historyChipMissing: '缺失',
    historyChipStructure: '結構',
    historySeverityHigh: '高',
    historySeverityMedium: '中',
    historySeverityLow: '低',
    historyPageTypeEntity: '📦 entity',
    historyPageTypeConcept: '💡 concept',
    historyPageTypeSource: '📄 source',
    historyGlobalInsight: '您的 Wiki 當前有 {dead} 個斷鏈、{orphans} 個孤立頁面、{tags} 個標籤問題。最近一次 Lint 耗時 {duration}。',
    historyGlobalInsightClean: '您的 Wiki 當前狀態良好——沒有斷鏈、孤立頁面或標籤問題。',
    historyGlobalInsightNoData: '暫無維護報告——執行 Lint 以生成。',
    historyModalHeaderTitle: '操作歷史',
    historyModalSubtitleWithCount: 'LLM-Wiki 最近的變更記錄 · 共 {count} 條',
    historyTimeRangeAll: '全部時間',
    historyTimeRange1d: '近 1 天',
    historyTimeRange3d: '近 3 天',
    historyTimeRange1w: '近 1 周',
    historyTimeRange1m: '近 1 個月',
    historyIngestTotal: '頁面總數',
    historyIngestByType: '按型別分佈',
    historyIngestSource: '來原始檔',
    historyIngestNoTimestamp: '無時間戳',
    historyIngestFirstTime: '首次攝入',
    historyIngestLatestTime: '最近攝入',
    historyTimeRangeCustom: '自定義範圍',
    historyCustomRangeFrom: '起始',
    historyCustomRangeTo: '結束',
    historyCustomRangeApply: '應用',
    historyCustomRangeClear: '清除',
} as const;