export const CODEX_OAUTH_CLIENT_ID = 'app_EMoamEEZ73f0CkXaXp7hrann';
export const CODEX_OAUTH_ISSUER = 'https://auth.openai.com';
export const CODEX_TOKEN_URL = `${CODEX_OAUTH_ISSUER}/oauth/token`;
export const CODEX_DEVICE_URL = `${CODEX_OAUTH_ISSUER}/codex/device`;
export const CODEX_RESPONSES_URL = 'https://chatgpt.com/backend-api/codex/responses';
export const CODEX_MODELS_URL = 'https://chatgpt.com/backend-api/codex/models';
export const CODEX_REDIRECT_URI = 'http://localhost:1455/auth/callback';
export const CODEX_SECRET_ID = 'karpathywiki-openai-codex';
export const CODEX_MODELS = ['gpt-5.5', 'gpt-5.4', 'gpt-5.4-mini', 'gpt-5.3-codex-spark'] as const;
