"""
Constants — port of src/constants.ts
"""

# Wiki subfolder names
WIKI_SUBFOLDERS = {
    "entities": "entities",
    "concepts": "concepts",
    "sources": "sources",
}

# Accepted source file extensions
COMPATIBLE_SOURCE_EXTENSIONS = ["md", "markdown", "txt", "text"]

# Lint thresholds
MIN_SUBSTANTIVE_CHARS = 50
PAGES_CACHE_TTL_MS = 5000

# Custom granularity limits
CUSTOM_LIMIT_MAX = 500
CUSTOM_LIMIT_MIN = 1
CUSTOM_BATCH_SIZE_MAX = 50
CUSTOM_BATCH_SIZE_MIN = 10

TOKENS_PER_ITEM_BUDGET = 400
SOURCE_ANALYZER_RETRY_MULTIPLIER = 3

# LLM token budgets
MAX_TOKENS_BATCH = 16000
TOKENS_PAGE_GENERATION = 8000
TOKENS_APPEND_REVIEWED = 4000
TOKENS_CONTRADICTION = 4000
TOKENS_CONVERSATION_EXTRACTION = 5000
TOKENS_CONVERSATION_PAGE = 8000
TOKENS_DEDUP_RESOLUTION = 1000
TOKENS_LINT_ALIAS_BATCH = 500
TOKENS_LINT_DEDUP_LLM = 4000
TOKENS_LINT_PAGE_FIX = 8000
TOKENS_LINT_ORPHAN_FIX = 800
TOKENS_QUERY_MODEL_DETECT = 100
TOKENS_QUERY_PAGE_SELECT = 500
TOKENS_QUERY_LLM_SELECT = 3000
TOKENS_QUERY_SAVE_DEDUP = 300
TOKENS_SCHEMA_SUGGESTION = 4096
MAX_PAGE_CONTENT_CHARS = 12800

# Retry settings
MAX_RETRIES = 2
RETRY_BASE_DELAY_MS = 1000
